{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-metrics-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "VOCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "hass_sensor_volatile_organic_compounds_u0xb5g_per_mu0xb3",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "CO²",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "hass_sensor_carbon_dioxide_ppm", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "hass_sensor_pm25_u0xb5g_per_mu0xb3",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}