{
 "title": "Printers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "printer",
    "query": {
     "query": "label_values(klipper_total_time,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Lifetime Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Print Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_print_time{instance=~\"${printer}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Filament Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_filament_used{instance=~\"${printer}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_jobs{instance=~\"${printer}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}