{
 "title": "authentik",
 "description": "Grafana Dashboard for Prometheus metrics exposed by authentik.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "authentik_outpost_connection" } }
  ]
 },
 "panels": [
  { "title": "authentik Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FlowPlanner time by flow",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (flow_slug) (rate(authentik_flows_plan_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_flows_plan_time_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ flow_slug }}"
    }
   ]
  },
  {
   "title": "Task status (1h)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(authentik_tasks_total{namespace=~\"$namespace\"}[1h])) - sum(increase(authentik_tasks_errors_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(authentik_tasks_errors_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "\n\n<img src=\"https://goauthentik.io/img/icon_top_brand.svg\">"
   }
  },
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(authentik_admin_workers{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cached policies",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_policies_cached{namespace=~\"$namespace\"})",
     "legendFormat": "Cached policies"
    },
    {
     "expr": "sum(authentik_flows_cached{namespace=~\"$namespace\"})",
     "legendFormat": "Cached flows"
    }
   ]
  },
  {
   "title": "Connected Outposts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_outposts_connected{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "System task duration",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (actor_name) (rate(authentik_tasks_duration_milliseconds_sum{namespace=~\"$namespace\"}[5m])) / sum by (actor_name) (rate(authentik_tasks_duration_milliseconds_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ actor_name }}"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding type (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg by(binding_target_type) (rate(authentik_policies_execution_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_policies_execution_time_count{namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ binding_target_type }}"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding target (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg by(object_type) (rate(authentik_policies_execution_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_policies_execution_time_count{namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ object_type }}"
    }
   ]
  },
  { "title": "authentik HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "HTTP Requests per 5 min by Destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (dest) (rate(authentik_main_request_duration_seconds_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ dest }}"
    }
   ]
  },
  {
   "title": "HTTP Request P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (dest, le) (rate(authentik_main_request_duration_seconds_bucket{namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ dest }}"
    }
   ]
  },
  { "title": "authentik Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Task Execution Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (actor_name) (rate(authentik_tasks_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ actor_name }}"
    }
   ]
  },
  {
   "title": "Task Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by (actor_name) (rate(authentik_tasks_errors_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ actor_name }}"
    }
   ]
  },
  {
   "title": "Flow Stage Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg by (stage_type) (rate(authentik_flows_stage_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_flows_stage_time_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ stage_type }}"
    },
    {
     "expr": "avg by (stage_type, method) (rate(authentik_flows_execution_stage_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_flows_execution_stage_time_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ stage_type }} {{ method }}"
    }
   ]
  },
  {
   "title": "Task Executions by Actor (1h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (actor_name) (increase(authentik_tasks_total{namespace=~\"$namespace\"}[1h])))",
     "legendFormat": "{{ actor_name }}"
    }
   ]
  },
  {
   "title": "Tasks by Queue (1h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue_name) (increase(authentik_tasks_total{namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  }
 ]
}