{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 } },
  { "title": "Internet Traffic", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 } },
  { "title": "Quick Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Proxmox Cluster Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(memory_memtotal{object=\"nodes\"}) - sum(memory_memused{object=\"nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ceph Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  ceph_cluster_total_bytes{cluster=~\"ceph\"}\n    -\n  ceph_cluster_total_used_bytes{cluster=~\"ceph\"}\n)\n  /\nceph_cluster_total_bytes{cluster=~\"ceph\"}"
    }
   ]
  },
  {
   "title": "Disk free - warp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"vmhost\",instance=\"vmhost03.cmdcentral.xyz:9100\",device=~\"warp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{instance=\"infra2.cmdcentral.xyz:3493\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Ceph Aggregate IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{cluster=~\"ceph\", }[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{cluster=~\"ceph\", }[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "WiFi Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_stations{name!=\"Gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rack Temperature Differential",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"infra2.cmdcentral.xyz:9100\",chip=\"w1_bus_master1_28_030a979463f8\"} - ignoring(chip) node_hwmon_temp_celsius{instance=\"infra2.cmdcentral.xyz:9100\",chip=\"w1_bus_master1_28_030f97943496\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (vmhost01)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"vmhost\",instance=\"vmhost01.cmdcentral.xyz:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"vmhost\",instance=\"vmhost01.cmdcentral.xyz:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"vmhost\",instance=\"vmhost01.cmdcentral.xyz:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (vmhost02)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"vmhost\",instance=\"vmhost02.cmdcentral.xyz:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"vmhost\",instance=\"vmhost02.cmdcentral.xyz:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"vmhost\",instance=\"vmhost02.cmdcentral.xyz:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (vmhost03)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"vmhost\",instance=\"vmhost03.cmdcentral.xyz:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"vmhost\",instance=\"vmhost03.cmdcentral.xyz:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"vmhost\",instance=\"vmhost03.cmdcentral.xyz:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "stat",
   "description": "Total rack power consumption through UPSes",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "0": "(",
     "1": "\n",
     "10": "s",
     "100": "s",
     "101": "i",
     "102": "d",
     "103": "e",
     "104": ")",
     "105": " ",
     "106": "w",
     "107": "i",
     "108": "t",
     "109": "h",
     "11": "u",
     "110": "o",
     "111": "u",
     "112": "t",
     "113": "(",
     "114": "u",
     "115": "p",
     "116": "s",
     "117": ")",
     "118": "\n",
     "119": " ",
     "12": "m",
     "120": " ",
     "121": ")",
     "122": "\n",
     "123": " ",
     "124": " ",
     "125": " ",
     "126": " ",
     "127": "+",
     "128": "\n",
     "129": " ",
     "13": "(",
     "130": " ",
     "131": "s",
     "132": "u",
     "133": "m",
     "134": "(",
     "135": "u",
     "136": "p",
     "137": "s",
     "138": ":",
     "139": "p",
     "14": "u",
     "140": "o",
     "141": "w",
     "142": "e",
     "143": "r",
     "144": "_",
     "145": "u",
     "146": "s",
     "147": "a",
     "148": "g",
     "149": "e",
     "15": "p",
     "150": "_",
     "151": "w",
     "152": "a",
     "153": "t",
     "154": "t",
     "155": "s",
     "156": ":",
     "157": "b",
     "158": "_",
     "159": "s",
     "16": "s",
     "160": "i",
     "161": "d",
     "162": "e",
     "163": ")",
     "164": " ",
     "165": "w",
     "166": "i",
     "167": "t",
     "168": "h",
     "169": "o",
     "17": ":",
     "170": "u",
     "171": "t",
     "172": "(",
     "173": "u",
     "174": "p",
     "175": "s",
     "176": ")",
     "177": "\n",
     "178": ")",
     "179": "\n",
     "18": "p",
     "180": " ",
     "181": " ",
     "182": "+",
     "183": "\n",
     "184": "s",
     "185": "u",
     "186": "m",
     "187": "(",
     "188": "u",
     "189": "p",
     "19": "o",
     "190": "s",
     "191": ":",
     "192": "p",
     "193": "o",
     "194": "w",
     "195": "e",
     "196": "r",
     "197": "_",
     "198": "u",
     "199": "s",
     "2": " ",
     "20": "w",
     "200": "a",
     "201": "g",
     "202": "e",
     "203": "_",
     "204": "w",
     "205": "a",
     "206": "t",
     "207": "t",
     "208": "s",
     "209": ":",
     "21": "e",
     "210": "n",
     "211": "e",
     "212": "t",
     "213": "w",
     "214": "o",
     "215": "r",
     "216": "k",
     "217": ")",
     "218": " ",
     "219": "w",
     "22": "r",
     "220": "i",
     "221": "t",
     "222": "h",
     "223": "o",
     "224": "u",
     "225": "t",
     "226": "(",
     "227": "u",
     "228": "p",
     "229": "s",
     "23": "_",
     "230": ")",
     "24": "u",
     "25": "s",
     "26": "a",
     "27": "g",
     "28": "e",
     "29": "_",
     "3": " ",
     "30": "w",
     "31": "a",
     "32": "t",
     "33": "t",
     "34": "s",
     "35": ":",
     "36": "r",
     "37": "a",
     "38": "c",
     "39": "k",
     "4": "(",
     "40": "m",
     "41": "o",
     "42": "u",
     "43": "n",
     "44": "t",
     "45": ")",
     "46": " ",
     "47": "w",
     "48": "i",
     "49": "t",
     "5": "\n",
     "50": "h",
     "51": "o",
     "52": "u",
     "53": "t",
     "54": "(",
     "55": "u",
     "56": "p",
     "57": "s",
     "58": ")",
     "59": "\n",
     "6": " ",
     "60": " ",
     "61": " ",
     "62": " ",
     "63": " ",
     "64": " ",
     "65": " ",
     "66": "+",
     "67": "\n",
     "68": " ",
     "69": " ",
     "7": " ",
     "70": " ",
     "71": " ",
     "72": "s",
     "73": "u",
     "74": "m",
     "75": "(",
     "76": "u",
     "77": "p",
     "78": "s",
     "79": ":",
     "8": " ",
     "80": "p",
     "81": "o",
     "82": "w",
     "83": "e",
     "84": "r",
     "85": "_",
     "86": "u",
     "87": "s",
     "88": "a",
     "89": "g",
     "9": " ",
     "90": "e",
     "91": "_",
     "92": "w",
     "93": "a",
     "94": "t",
     "95": "t",
     "96": "s",
     "97": ":",
     "98": "a",
     "99": "_",
     "expr": "sum(ups:power_usage_watts:a_side) without(ups)\n  +\nsum(ups:power_usage_watts:b_side) without(ups)"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (radio_desc) (unpoller_client_uptime_seconds{site_name=\"Default (default)\",radio_desc!=\"\"})",
     "legendFormat": "{{radio_desc}}"
    }
   ]
  },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 6, "x": 13, "y": 15 } },
  {
   "title": "Memory (vmhost01)",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"vmhost01.cmdcentral.xyz:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"vmhost01.cmdcentral.xyz:9100\"})"
    }
   ]
  },
  {
   "title": "Memory (vmhost02)",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"vmhost02.cmdcentral.xyz:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"vmhost02.cmdcentral.xyz:9100\"})"
    }
   ]
  },
  {
   "title": "Memory (vmhost03)",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"vmhost03.cmdcentral.xyz:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"vmhost03.cmdcentral.xyz:9100\"})"
    }
   ]
  },
  {
   "title": "Rack Thermals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(1.8 * node_hwmon_temp_celsius{instance=\"infra2.cmdcentral.xyz:9100\",chip=~\"w1_bus.*\"}) + 32"
    },
    {
     "expr": "(1.8 * hass_sensor_temperature_celsius{entity=~\"sensor.(up|down)stairs_temperature\"} ) + 32"
    }
   ]
  },
  {
   "title": "Node temperatures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(label_replace(node_hwmon_temp_celsius{job!=\"printers\"}, \"friendly\", \"$1\", \"instance\", \"([^\\\\.]*)(.cmdcentral.xyz:9100)?\")) by (friendly)",
     "legendFormat": "{{friendly}}"
    }
   ]
  },
  {
   "title": "Recent Image Autoupdates",
   "type": "logs",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kubernetes.pod_namespace: \"argocd\" AND kubernetes.pod_labels.app.kubernetes.io/name:=\"argocd-image-updater\" AND \"Successfully updated image\" | extract_regexp `.* to '(?P<image>[^:@]+)(?::(?P<tag>[^@]+))?(?:@(?P<digest>sha256:[^']+))` from _msg | format \"<image> updated to <tag> at <digest>\""
    }
   ]
  }
 ]
}