{
 "title": "Navidrome",
 "description": "Main navidrome dashboard. Most of exposed metrics are here",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prom", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"^$job$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Navidrome version",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "navidrome_info{job=~\"^$job$\"}"
    }
   ]
  },
  { "title": "Media", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_model_totals{job=~\"^$job$\", model=\"user\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Media",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "db_model_totals{job=~\"^$job$\",model=\"media\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "db_model_totals{job=~\"^$job$\",model=\"album\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Time since last successful scan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - media_scan_last{job=~\"^$job$\", success=\"true\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed scans for period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(media_scans{job=~\"^$job$\", success=\"false\"}[$__range])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Go-specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(\nprocess_cpu_seconds_total{job=~\"^$job$\"}[1m]\n)) by (instance)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"^$job$\"}) by (instance)",
     "legendFormat": "RES@{{instance}}"
    }
   ]
  },
  {
   "title": "Open descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"^$job$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 30 },
   "targets": [
    {
     "expr": "sum(go_threads{job=~\"^$job$\"}) by (instance)",
     "legendFormat": "os threads@{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{job=~\"^$job$\"}) by (instance)",
     "legendFormat": "goroutines@{{instance}}"
    }
   ]
  },
  {
   "title": "GC total seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"navidrome.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_count{job=~\"navidrome.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go version",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "go_info{job=~\"^$job$\"}"
    }
   ]
  }
 ]
}