/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BitwardenSmValuesSchema {
  containers?: {
    kubeRbacProxy?: {
      image?: {
        repository?: string;
        tag?: string;
        [k: string]: unknown;
      };
      resources?: {
        limits?: {
          cpu?: string;
          memory?: string;
          [k: string]: unknown;
        };
        requests?: {
          cpu?: string;
          memory?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    manager?: {
      image?: {
        repository?: string;
        tag?: null | string;
        [k: string]: unknown;
      };
      resources?: {
        limits?: {
          cpu?: string;
          memory?: string;
          [k: string]: unknown;
        };
        requests?: {
          cpu?: string;
          memory?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    serviceAccount?: {
      annotations?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    enableSeccompProfileRuntimeDefault?: boolean;
    imagePullSecrets?: null | string;
    [k: string]: unknown;
  };
  metricsService?: {
    ports?: {
      name?: string;
      port?: number;
      protocol?: string;
      targetPort?: string;
      [k: string]: unknown;
    }[];
    type?: string;
    [k: string]: unknown;
  };
  settings?: {
    bwApiUrlOverride?: null | string;
    bwIdentityUrlOverride?: null | string;
    bwSecretsManagerRefreshInterval?: number;
    cloudRegion?: string;
    kubernetesClusterDomain?: string;
    replicas?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
