/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Setting a digest pins the image. If a tag is also set, the rendered reference will include both ("image:tag@digest"), though only the digest will be used for pulling.
 */
export type HelmValuesAcmesolverImageDigest = string;
/**
 * The image name for the cert-manager acmesolver.
 */
export type HelmValuesAcmesolverImageName = string;
/**
 * Kubernetes imagePullPolicy on Deployment.
 */
export type HelmValuesAcmesolverImagePullPolicy = string;
/**
 * Deprecated: per-component registry prefix.
 *
 * If set, this value is *prepended* to the image repository that the chart would otherwise render. This applies both when `acmesolver.image.repository` is set and when the repository is computed from
 * `imageRegistry` + `imageNamespace` + `acmesolver.image.name`.
 *
 * This can produce "double registry" style references such as `legacy.example.io/quay.io/jetstack/...`. Prefer using the global `imageRegistry`/`imageNamespace` values.
 */
export type HelmValuesAcmesolverImageRegistry = string;
/**
 * Full repository override (takes precedence over `imageRegistry`, `imageNamespace`, and `acmesolver.image.name`).
 */
export type HelmValuesAcmesolverImageRepository = string;
/**
 * Override the image tag to deploy by setting this variable. If no value is set, the chart's appVersion is used.
 */
export type HelmValuesAcmesolverImageTag = string;
/**
 * A Kubernetes Runtime Class to apply to ACME HTTP01 solver pods, if required. For more information, see [Runtime Class](https://kubernetes.io/docs/concepts/containers/).
 *
 * For example:
 * runtimeClassName: gvisor
 */
export type HelmValuesAcmesolverRuntimeClassName = string;
/**
 * List of signer names that cert-manager will approve by default. CertificateRequests referencing these signer names will be auto-approved by cert-manager. Defaults to just approving the cert-manager.io Issuer and ClusterIssuer issuers. When set to an empty array, ALL issuers will be auto-approved by cert-manager. To disable the auto-approval, because, e.g., you are using approver-policy, you can enable 'disableAutoApproval'.
 * ref: https://cert-manager.io/docs/concepts/certificaterequest/#approval
 */
export type HelmValues2 = unknown[];
/**
 * Automounting API credentials for a particular pod.
 */
export type HelmValuesAutomountServiceAccountToken = boolean;
/**
 * Automounting API credentials for a particular pod.
 */
export type HelmValuesCainjectorAutomountServiceAccountToken = boolean;
/**
 * enableServiceLinks indicates whether information about services should be injected into the pod's environment variables, matching the syntax of Docker links.
 */
export type HelmValuesCainjectorEnableServiceLinks = boolean;
/**
 * Create the CA Injector deployment
 */
export type HelmValuesCainjectorEnabled = boolean;
/**
 * Additional command line flags to pass to cert-manager cainjector binary. To see all available flags run `docker run quay.io/jetstack/cert-manager-cainjector:<version> --help`.
 */
export type HelmValuesCainjector4 = unknown[];
/**
 * Additional environment variables to pass to cert-manager cainjector binary.
 * For example:
 * extraEnv:
 * - name: SOME_VAR
 *   value: 'some value'
 */
export type HelmValuesCainjector5 = unknown[];
/**
 * Comma separated list of feature gates that should be enabled on the cainjector pod.
 */
export type HelmValuesCainjectorFeatureGates = string;
/**
 * Setting a digest pins the image. If a tag is also set, the rendered reference will include both ("image:tag@digest"), though only the digest will be used for pulling.
 */
export type HelmValuesCainjectorImageDigest = string;
/**
 * The image name for the cert-manager cainjector.
 */
export type HelmValuesCainjectorImageName = string;
/**
 * Kubernetes imagePullPolicy on Deployment.
 */
export type HelmValuesCainjectorImagePullPolicy = string;
/**
 * Deprecated: per-component registry prefix.
 *
 * If set, this value is *prepended* to the image repository that the chart would otherwise render. This applies both when `cainjector.image.repository` is set and when the repository is computed from
 * `imageRegistry` + `imageNamespace` + `cainjector.image.name`.
 *
 * This can produce "double registry" style references such as `legacy.example.io/quay.io/jetstack/...`. Prefer using the global `imageRegistry`/`imageNamespace` values.
 */
export type HelmValuesCainjectorImageRegistry = string;
/**
 * Full repository override (takes precedence over `imageRegistry`, `imageNamespace`, and `cainjector.image.name`).
 */
export type HelmValuesCainjectorImageRepository = string;
/**
 * Override the image tag to deploy by setting this variable. If no value is set, the chart's appVersion will be used.
 */
export type HelmValuesCainjectorImageTag = string;
/**
 * Egress rule for the cainjector network policy. By default, it allows all outbound traffic to ports 80 and 443, as well as DNS ports.
 */
export type HelmValuesCainjectorNetworkPolicy = unknown[];
/**
 * Create network policies for the cainjector.
 */
export type HelmValuesCainjectorNetworkPolicyEnabled = boolean;
/**
 * Ingress rule for the webhook cainjector policy.
 * By default all pods are allowed access to:
 *   http-metrics port
 */
export type HelmValuesCainjectorNetworkPolicy1 = unknown[];
/**
 * Enable or disable the PodDisruptionBudget resource.
 *
 * This prevents downtime during voluntary disruptions such as during a Node upgrade. For example, the PodDisruptionBudget will block `kubectl drain` if it is used on the Node where the only remaining cert-manager
 * Pod is currently running.
 */
export type HelmValuesCainjectorPodDisruptionBudgetEnabled = boolean;
/**
 * This configures how to act with unhealthy pods during eviction. Note that this requires Kubernetes 1.31 or `PDBUnhealthyPodEvictionPolicy` feature gate enabled for the cluster to work.
 */
export type HelmValuesCainjectorPodDisruptionBudgetUnhealthyPodEvictionPolicy = string;
/**
 * The number of replicas of the cert-manager cainjector to run.
 *
 * The default is 1, but in production set this to 2 or 3 to provide high availability.
 *
 * If `replicas > 1`, consider setting `cainjector.podDisruptionBudget.enabled=true`.
 *
 * Note that cert-manager uses leader election to ensure that there can only be a single instance active at a time.
 */
export type HelmValuesCainjectorReplicaCount = number;
/**
 * A Kubernetes Runtime Class to apply to ACME HTTP01 solver pods, if required. For more information, see [Runtime Class](https://kubernetes.io/docs/concepts/containers/).
 *
 * For example:
 * runtimeClassName: gvisor
 */
export type HelmValuesCainjectorRuntimeClassName = string;
/**
 * Automount API credentials for a Service Account.
 */
export type HelmValuesCainjectorServiceAccountAutomountServiceAccountToken = boolean;
/**
 * Specifies whether a service account should be created.
 */
export type HelmValuesCainjectorServiceAccountCreate = boolean;
/**
 * The name of the service account to use.
 * If not set and create is true, a name is generated using the fullname template
 */
export type HelmValuesCainjectorServiceAccountName = string;
/**
 * A list of Kubernetes Tolerations, if required. For more information, see [Toleration v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core).
 *
 * For example:
 * tolerations:
 * - key: foo.bar.com/role
 *   operator: Equal
 *   value: master
 *   effect: NoSchedule
 */
export type HelmValuesCainjector18 = unknown[];
/**
 * A list of Kubernetes TopologySpreadConstraints, if required. For more information, see [Topology spread constraint v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#topologyspreadconstraint-v1-core).
 *
 * For example:
 * topologySpreadConstraints:
 * - maxSkew: 2
 *   topologyKey: topology.kubernetes.io/zone
 *   whenUnsatisfiable: ScheduleAnyway
 *   labelSelector:
 *     matchLabels:
 *       app.kubernetes.io/instance: cert-manager
 *       app.kubernetes.io/component: controller
 */
export type HelmValuesCainjector19 = unknown[];
/**
 * Additional volume mounts to add to the cert-manager controller container.
 */
export type HelmValuesCainjector20 = unknown[];
/**
 * Additional volumes to add to the cert-manager controller pod.
 */
export type HelmValuesCainjector21 = unknown[];
/**
 * Override the namespace used to store DNS provider credentials etc. for ClusterIssuer resources. By default, the same namespace as cert-manager is deployed within is used. This namespace will not be automatically created by the Helm chart.
 */
export type HelmValuesClusterResourceNamespace = string;
/**
 * This option decides if the CRDs should be installed as part of the Helm installation.
 */
export type HelmValuesCrdsEnabled = boolean;
/**
 * This option makes it so that the "helm.sh/resource-policy": keep annotation is added to the CRD. This will prevent Helm from uninstalling the CRD when the Helm release is uninstalled. WARNING: when the CRDs are removed, all cert-manager custom resources
 * (Certificates, Issuers, ...) will be removed too by the garbage collector.
 */
export type HelmValuesCrdsKeep = boolean;
/**
 * Field used by our release pipeline to produce the static manifests. The field defaults to "helm" but is set to "static" when we render the static YAML manifests.
 */
export type HelmValuesCreator = string;
/**
 * Option to disable cert-manager's build-in auto-approver. The auto-approver approves all CertificateRequests that reference issuers matching the 'approveSignerNames' option. This 'disableAutoApproval' option is useful when you want to make all approval decisions using a different approver (like approver-policy - https://github.com/cert-manager/approver-policy).
 */
export type HelmValuesDisableAutoApproval = boolean;
/**
 * A comma-separated string with the host and port of the recursive nameservers cert-manager should query.
 */
export type HelmValuesDns01RecursiveNameservers = string;
/**
 * Forces cert-manager to use only the recursive nameservers for verification. Enabling this option could cause the DNS01 self check to take longer owing to caching performed by the recursive nameservers.
 */
export type HelmValuesDns01RecursiveNameserversOnly = boolean;
/**
 * When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted.
 */
export type HelmValuesEnableCertificateOwnerRef = boolean;
/**
 * enableServiceLinks indicates whether information about services should be injected into the pod's environment variables, matching the syntax of Docker links.
 */
export type HelmValuesEnableServiceLinks = boolean;
/**
 * Field that can be used as a condition when cert-manager is a dependency. This definition is only here as a placeholder such that it is included in the json schema. See https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags for more info.
 */
export type HelmValuesEnabled = boolean;
/**
 * Additional command line flags to pass to cert-manager controller binary. To see all available flags run `docker run quay.io/jetstack/cert-manager-controller:<version> --help`.
 *
 * Use this flag to enable or disable arbitrary controllers. For example, to disable the CertificateRequests approver.
 *
 * For example:
 * extraArgs:
 *   - --controllers=*,-certificaterequests-approver
 */
export type HelmValues8 = unknown[];
/**
 * Extra containers to add to the pod spec in the deployment of the cert-manager controller. For example, to deploy the [aws_signing_helper](https://github.com/aws/rolesanywhere-credential-helper) (replacing the ARNs as relevant):
 * extraEnv:
 *   - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
 *   - value: http://127.0.0.1:9911
 * extraContainers:
 *   - name: rolesanywhere-credential-helper
 *     image: public.ecr.aws/rolesanywhere/credential-helper:latest
 *     command: [aws_signing_helper]
 *     args:
 *       - serve
 *       - --private-key
 *       - /etc/cert/tls.key
 *       - --certificate
 *       - /etc/cert/tls.crt
 *       - --role-arn
 *       - $ROLE_ARN
 *       - --profile-arn
 *       - $PROFILE_ARN
 *       - --trust-anchor-arn
 *       - $TRUST_ANCHOR_ARN
 *     volumeMounts:
 *       - name: cert
 *         mountPath: /etc/cert/
 *         readOnly: true
 * volumes:
 *   - name: cert
 *     secret:
 *       secretName: cert
 */
export type HelmValues9 = unknown[];
/**
 * Additional environment variables to pass to cert-manager controller binary.
 * For example:
 * extraEnv:
 * - name: SOME_VAR
 *   value: 'some value'
 */
export type HelmValues10 = unknown[];
/**
 * Create dynamic manifests via values.
 *
 * For example:
 * extraObjects:
 *   - |
 *     apiVersion: v1
 *     kind: ConfigMap
 *     metadata:
 *       name: '{{ template "cert-manager.fullname" . }}-extra-configmap'
 */
export type HelmValues11 = unknown[];
/**
 * A comma-separated list of feature gates that should be enabled on the controller pod.
 */
export type HelmValuesFeatureGates = string;
/**
 * Override the "cert-manager.fullname" value. This value is used as part of most of the names of the resources created by this Helm chart.
 */
export type HelmValuesFullnameOverride = string;
/**
 * Set all pods to run in a user namespace without host access. Experimental: may be removed once the Kubernetes User Namespaces feature is GA.
 *
 * Requirements:
 *   - Kubernetes ≥ 1.33, or
 *   - Kubernetes 1.27–1.32 with UserNamespacesSupport feature gate enabled.
 *
 * Set to false to run pods in a user namespace without host access.
 *
 * See [limitations](https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/#limitations) for details.
 */
export type HelmValuesGlobalHostUsers = boolean;
/**
 * Reference to one or more secrets to be used when pulling images. For more information, see [Pull an Image from a Private Registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).
 *
 * For example:
 * imagePullSecrets:
 *   - name: "image-pull-secret"
 */
export type HelmValuesGlobal1 = unknown[];
/**
 * The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate.
 */
export type HelmValuesGlobalLeaderElectionLeaseDuration = string;
/**
 * Override the namespace used for the leader election lease.
 */
export type HelmValuesGlobalLeaderElectionNamespace = string;
/**
 * The interval between attempts by the acting master to renew a leadership slot before it stops leading. This must be less than or equal to the lease duration.
 */
export type HelmValuesGlobalLeaderElectionRenewDeadline = string;
/**
 * The duration the clients should wait between attempting acquisition and renewal of a leadership.
 */
export type HelmValuesGlobalLeaderElectionRetryPeriod = string;
/**
 * Set the verbosity of cert-manager. A range of 0 - 6, with 6 being the most verbose.
 */
export type HelmValuesGlobalLogLevel = number;
/**
 * Create PodSecurityPolicy for cert-manager.
 *
 * Note that PodSecurityPolicy was deprecated in Kubernetes 1.21 and removed in Kubernetes 1.25.
 */
export type HelmValuesGlobalPodSecurityPolicyEnabled = boolean;
/**
 * Configure the PodSecurityPolicy to use AppArmor.
 */
export type HelmValuesGlobalPodSecurityPolicyUseAppArmor = boolean;
/**
 * The optional priority class to be used for the cert-manager pods.
 */
export type HelmValuesGlobalPriorityClassName = string;
/**
 * Aggregate ClusterRoles to Kubernetes default user-facing roles. For more information, see [User-facing roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)
 */
export type HelmValuesGlobalRbacAggregateClusterRoles = boolean;
/**
 * Create required ClusterRoles and ClusterRoleBindings for cert-manager.
 */
export type HelmValuesGlobalRbacCreate = boolean;
/**
 * The number of old ReplicaSets to retain to allow rollback (if not set, the default Kubernetes value is set to 10).
 */
export type HelmValuesGlobalRevisionHistoryLimit = number;
/**
 * A Kubernetes Runtime Class to apply to ACME HTTP01 solver pods, if required. For more information, see [Runtime Class](https://kubernetes.io/docs/concepts/containers/).
 *
 * For example:
 * runtimeClassName: gvisor
 */
export type HelmValuesGlobalRuntimeClassName = string;
/**
 * Optional hostAliases for cert-manager-controller pods. May be useful when performing ACME DNS-01 self checks.
 */
export type HelmValues13 = unknown[];
/**
 * Configures the HTTP_PROXY environment variable where a HTTP proxy is required.
 */
export type HelmValuesHttpProxy = string;
/**
 * Configures the HTTPS_PROXY environment variable where a HTTP proxy is required.
 */
export type HelmValuesHttpsProxy = string;
/**
 * Setting a digest pins the image. If a tag is also set, the rendered reference will include both ("image:tag@digest"), though only the digest will be used for pulling.
 */
export type HelmValuesImageDigest = string;
/**
 * The image name for the cert-manager controller.
 * This is used (together with `imageRegistry` and `imageNamespace`) to construct the full image reference.
 */
export type HelmValuesImageName = string;
/**
 * Kubernetes imagePullPolicy on Deployment.
 */
export type HelmValuesImagePullPolicy = string;
/**
 * Deprecated: per-component registry prefix.
 *
 * If set, this value is *prepended* to the image repository that the chart would otherwise render. This applies both when `image.repository` is set and when the repository is computed from
 * `imageRegistry` + `imageNamespace` + `image.name`.
 *
 * This can produce "double registry" style references such as `legacy.example.io/quay.io/jetstack/...`. Prefer using the global `imageRegistry`/`imageNamespace` values.
 */
export type HelmValuesImageRegistry = string;
/**
 * Full repository override (takes precedence over `imageRegistry`, `imageNamespace`, and `image.name`).
 * Example: quay.io/jetstack/cert-manager-controller
 */
export type HelmValuesImageRepository = string;
/**
 * Override the image tag to deploy by setting this variable. If no value is set, the chart's appVersion is used.
 */
export type HelmValuesImageTag = string;
/**
 * The repository namespace used for all cert-manager images by default.
 * Examples:
 * - jetstack
 * - cert-manager
 */
export type HelmValuesImageNamespace = string;
/**
 * The container registry used for all cert-manager images by default. This can include path prefixes (e.g. `artifactory.example.com/docker`).
 */
export type HelmValuesImageRegistry1 = string;
/**
 * Optional default issuer group to use for ingress resources.
 */
export type HelmValuesIngressShimDefaultIssuerGroup = string;
/**
 * Optional default issuer kind to use for ingress resources.
 */
export type HelmValuesIngressShimDefaultIssuerKind = string;
/**
 * Optional default issuer to use for ingress resources.
 */
export type HelmValuesIngressShimDefaultIssuerName = string;
/**
 * This option is equivalent to setting crds.enabled=true and crds.keep=true. Deprecated: use crds.enabled and crds.keep instead.
 */
export type HelmValuesInstallCRDs = boolean;
/**
 * The maximum number of challenges that can be scheduled as 'processing' at once.
 */
export type HelmValuesMaxConcurrentChallenges = number;
/**
 * Override the "cert-manager.name" value, which is used to annotate some of the resources that are created by this Chart (using "app.kubernetes.io/name"). NOTE: There are some inconsistencies in the Helm chart when it comes to these annotations (some resources use, e.g., "cainjector.name" which resolves to the value "cainjector").
 */
export type HelmValuesNameOverride = string;
/**
 * This namespace allows you to define where the services are installed into. If not set then they use the namespace of the release. This is helpful when installing cert manager as a chart dependency (sub chart).
 */
export type HelmValuesNamespace = string;
/**
 * Egress rule for the cert-manager network policy. By default, it allows all outbound traffic to ports 80 and 443, as well as DNS ports.
 */
export type HelmValuesNetworkPolicy = unknown[];
/**
 * Create network policies for cert-manager.
 */
export type HelmValuesNetworkPolicyEnabled = boolean;
/**
 * Ingress rule for the cert-manager network policy.
 * By default all pods are allowed access to:
 *   http-metrics and http-healthz ports
 */
export type HelmValuesNetworkPolicy1 = unknown[];
/**
 * Configures the NO_PROXY environment variable where a HTTP proxy is required, but certain domains should be excluded.
 */
export type HelmValuesNoProxy = string;
/**
 * Enable or disable the PodDisruptionBudget resource.
 *
 * This prevents downtime during voluntary disruptions such as during a Node upgrade. For example, the PodDisruptionBudget will block `kubectl drain` if it is used on the Node where the only remaining cert-manager
 * Pod is currently running.
 */
export type HelmValuesPodDisruptionBudgetEnabled = boolean;
/**
 * This configures how to act with unhealthy pods during eviction. Note that this requires Kubernetes 1.31 or `PDBUnhealthyPodEvictionPolicy` feature gate enabled for the cluster to work.
 */
export type HelmValuesPodDisruptionBudgetUnhealthyPodEvictionPolicy = string;
/**
 * Pod DNS policy.
 * For more information, see [Pod's DNS Policy](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy).
 */
export type HelmValuesPodDnsPolicy = string;
/**
 * Enable Prometheus monitoring for the cert-manager controller and webhook. If you use the Prometheus Operator, set prometheus.podmonitor.enabled or prometheus.servicemonitor.enabled, to create a PodMonitor or a
 * ServiceMonitor resource.
 * Otherwise, 'prometheus.io' annotations are added to the cert-manager and cert-manager-webhook Deployments. Note that you cannot enable both PodMonitor and ServiceMonitor as they are mutually exclusive. Enabling both will result in an error.
 */
export type HelmValuesPrometheusEnabled = boolean;
/**
 * Create a PodMonitor to add cert-manager to Prometheus.
 */
export type HelmValuesPrometheusPodmonitorEnabled = boolean;
/**
 * Keep labels from scraped data, overriding server-side labels.
 */
export type HelmValuesPrometheusPodmonitorHonorLabels = boolean;
/**
 * The interval to scrape metrics.
 */
export type HelmValuesPrometheusPodmonitorInterval = string;
/**
 * The namespace that the pod monitor should live in, defaults to the cert-manager namespace.
 */
export type HelmValuesPrometheusPodmonitorNamespace = string;
/**
 * Specifies the `prometheus` label on the created PodMonitor. This is used when different Prometheus instances have label selectors matching different PodMonitors.
 */
export type HelmValuesPrometheusPodmonitorPrometheusInstance = string;
/**
 * The timeout before a metrics scrape fails.
 */
export type HelmValuesPrometheusPodmonitorScrapeTimeout = string;
/**
 * Create a ServiceMonitor to add cert-manager to Prometheus.
 */
export type HelmValuesPrometheusServicemonitorEnabled = boolean;
/**
 * Keep labels from scraped data, overriding server-side labels.
 */
export type HelmValuesPrometheusServicemonitorHonorLabels = boolean;
/**
 * The interval to scrape metrics.
 */
export type HelmValuesPrometheusServicemonitorInterval = string;
/**
 * The namespace that the service monitor should live in, defaults to the cert-manager namespace.
 */
export type HelmValuesPrometheusServicemonitorNamespace = string;
/**
 * Specifies the `prometheus` label on the created ServiceMonitor. This is used when different Prometheus instances have label selectors matching different ServiceMonitors.
 */
export type HelmValuesPrometheusServicemonitorPrometheusInstance = string;
/**
 * The timeout before a metrics scrape fails.
 */
export type HelmValuesPrometheusServicemonitorScrapeTimeout = string;
/**
 * The number of replicas of the cert-manager controller to run.
 *
 * The default is 1, but in production set this to 2 or 3 to provide high availability.
 *
 * If `replicas > 1`, consider setting `podDisruptionBudget.enabled=true`.
 *
 * Note that cert-manager uses leader election to ensure that there can only be a single instance active at a time.
 */
export type HelmValuesReplicaCount = number;
/**
 * A Kubernetes Runtime Class to apply to ACME HTTP01 solver pods, if required. For more information, see [Runtime Class](https://kubernetes.io/docs/concepts/containers/).
 *
 * For example:
 * runtimeClassName: gvisor
 */
export type HelmValuesRuntimeClassName = string;
/**
 * Automount API credentials for a Service Account.
 */
export type HelmValuesServiceAccountAutomountServiceAccountToken = boolean;
/**
 * Specifies whether a service account should be created.
 */
export type HelmValuesServiceAccountCreate = boolean;
/**
 * The name of the service account to use.
 * If not set and create is true, a name is generated using the fullname template.
 */
export type HelmValuesServiceAccountName = string;
/**
 * Optionally set the IP families for the controller Service that should be supported, in the order in which they should be applied to ClusterIP. Can be IPv4 and/or IPv6.
 */
export type HelmValues28 = unknown[];
/**
 * Optionally set the IP family policy for the controller Service to configure dual-stack; see [Configure dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services).
 */
export type HelmValuesServiceIPFamilyPolicy = string;
/**
 * Automounting API credentials for a particular pod.
 */
export type HelmValuesStartupapicheckAutomountServiceAccountToken = boolean;
/**
 * Job backoffLimit
 */
export type HelmValuesStartupapicheckBackoffLimit = number;
/**
 * enableServiceLinks indicates whether information about services should be injected into pod's environment variables, matching the syntax of Docker links.
 */
export type HelmValuesStartupapicheckEnableServiceLinks = boolean;
/**
 * Enables the startup api check.
 */
export type HelmValuesStartupapicheckEnabled = boolean;
/**
 * Additional command line flags to pass to startupapicheck binary. To see all available flags run `docker run quay.io/jetstack/cert-manager-startupapicheck:<version> --help`.
 *
 * Verbose logging is enabled by default so that if startupapicheck fails, you can know what exactly caused the failure. Verbose logs include details of the webhook URL, IP address and TCP connect errors for example.
 */
export type HelmValuesStartupapicheck2 = unknown[];
/**
 * Additional environment variables to pass to cert-manager startupapicheck binary.
 * For example:
 * extraEnv:
 * - name: SOME_VAR
 *   value: 'some value'
 */
export type HelmValuesStartupapicheck3 = unknown[];
/**
 * Setting a digest pins the image. If a tag is also set, the rendered reference will include both ("image:tag@digest"), though only the digest will be used for pulling.
 */
export type HelmValuesStartupapicheckImageDigest = string;
/**
 * The image name for the cert-manager startupapicheck.
 */
export type HelmValuesStartupapicheckImageName = string;
/**
 * Kubernetes imagePullPolicy on Deployment.
 */
export type HelmValuesStartupapicheckImagePullPolicy = string;
/**
 * Deprecated: per-component registry prefix.
 *
 * If set, this value is *prepended* to the image repository that the chart would otherwise render. This applies both when `startupapicheck.image.repository` is set and when the repository is computed from
 * `imageRegistry` + `imageNamespace` + `startupapicheck.image.name`.
 *
 * This can produce "double registry" style references such as `legacy.example.io/quay.io/jetstack/...`. Prefer using the global `imageRegistry`/`imageNamespace` values.
 */
export type HelmValuesStartupapicheckImageRegistry = string;
/**
 * Full repository override (takes precedence over `imageRegistry`, `imageNamespace`, and `startupapicheck.image.name`).
 */
export type HelmValuesStartupapicheckImageRepository = string;
/**
 * Override the image tag to deploy by setting this variable. If no value is set, the chart's appVersion is used.
 */
export type HelmValuesStartupapicheckImageTag = string;
/**
 * A Kubernetes Runtime Class to apply to ACME HTTP01 solver pods, if required. For more information, see [Runtime Class](https://kubernetes.io/docs/concepts/containers/).
 *
 * For example:
 * runtimeClassName: gvisor
 */
export type HelmValuesStartupapicheckRuntimeClassName = string;
/**
 * Automount API credentials for a Service Account.
 */
export type HelmValuesStartupapicheckServiceAccountAutomountServiceAccountToken = boolean;
/**
 * Specifies whether a service account should be created.
 */
export type HelmValuesStartupapicheckServiceAccountCreate = boolean;
/**
 * The name of the service account to use.
 * If not set and create is true, a name is generated using the fullname template.
 */
export type HelmValuesStartupapicheckServiceAccountName = string;
/**
 * Timeout for 'kubectl check api' command.
 */
export type HelmValuesStartupapicheckTimeout = string;
/**
 * A list of Kubernetes Tolerations, if required. For more information, see [Toleration v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core).
 *
 * For example:
 * tolerations:
 * - key: foo.bar.com/role
 *   operator: Equal
 *   value: master
 *   effect: NoSchedule
 */
export type HelmValuesStartupapicheck13 = unknown[];
/**
 * Additional volume mounts to add to the cert-manager controller container.
 */
export type HelmValuesStartupapicheck14 = unknown[];
/**
 * Additional volumes to add to the cert-manager controller pod.
 */
export type HelmValuesStartupapicheck15 = unknown[];
/**
 * A list of Kubernetes Tolerations, if required. For more information, see [Toleration v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core).
 *
 * For example:
 * tolerations:
 * - key: foo.bar.com/role
 *   operator: Equal
 *   value: master
 *   effect: NoSchedule
 */
export type HelmValues32 = unknown[];
/**
 * A list of Kubernetes TopologySpreadConstraints, if required. For more information, see [Topology spread constraint v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#topologyspreadconstraint-v1-core
 *
 * For example:
 * topologySpreadConstraints:
 * - maxSkew: 2
 *   topologyKey: topology.kubernetes.io/zone
 *   whenUnsatisfiable: ScheduleAnyway
 *   labelSelector:
 *     matchLabels:
 *       app.kubernetes.io/instance: cert-manager
 *       app.kubernetes.io/component: controller
 */
export type HelmValues33 = unknown[];
/**
 * Additional volume mounts to add to the cert-manager controller container.
 */
export type HelmValues34 = unknown[];
/**
 * Additional volumes to add to the cert-manager controller pod.
 */
export type HelmValues35 = unknown[];
/**
 * Subject names to verify for the client certificate. Multiple values may be supplied as a comma-separated list.
 */
export type HelmValuesWebhookApiserverClientCertSubjects = string;
/**
 * Automounting API credentials for a particular pod.
 */
export type HelmValuesWebhookAutomountServiceAccountToken = boolean;
/**
 * the client CA file to be used for verification
 */
export type HelmValuesWebhookClientCAFile = string;
/**
 * enableClientVerification turns on client verification of requests made to the webhook server
 */
export type HelmValuesWebhookEnableClientVerification = boolean;
/**
 * enableServiceLinks indicates whether information about services should be injected into the pod's environment variables, matching the syntax of Docker links.
 */
export type HelmValuesWebhookEnableServiceLinks = boolean;
/**
 * Additional command line flags to pass to cert-manager webhook binary. To see all available flags run `docker run quay.io/jetstack/cert-manager-webhook:<version> --help`.
 */
export type HelmValuesWebhook4 = unknown[];
/**
 * Additional environment variables to pass to cert-manager webhook binary.
 * For example:
 * extraEnv:
 * - name: SOME_VAR
 *   value: 'some value'
 */
export type HelmValuesWebhook5 = unknown[];
/**
 * Comma separated list of feature gates that should be enabled on the webhook pod.
 */
export type HelmValuesWebhookFeatureGates = string;
/**
 * Specifies if the webhook should be started in hostNetwork mode.
 *
 * Required for use in some managed kubernetes clusters (such as AWS EKS) with custom. CNI (such as calico), because control-plane managed by AWS cannot communicate with pods' IP CIDR and admission webhooks are not working
 *
 * Since the default port for the webhook conflicts with kubelet on the host network, `webhook.securePort` should be changed to an available port if running in hostNetwork mode.
 */
export type HelmValuesWebhookHostNetwork = boolean;
/**
 * Setting a digest pins the image. If a tag is also set, the rendered reference will include both ("image:tag@digest"), though only the digest will be used for pulling.
 */
export type HelmValuesWebhookImageDigest = string;
/**
 * The image name for the cert-manager webhook.
 */
export type HelmValuesWebhookImageName = string;
/**
 * Kubernetes imagePullPolicy on Deployment.
 */
export type HelmValuesWebhookImagePullPolicy = string;
/**
 * Deprecated: per-component registry prefix.
 *
 * If set, this value is *prepended* to the image repository that the chart would otherwise render. This applies both when `webhook.image.repository` is set and when the repository is computed from
 * `imageRegistry` + `imageNamespace` + `webhook.image.name`.
 *
 * This can produce "double registry" style references such as `legacy.example.io/quay.io/jetstack/...`. Prefer using the global `imageRegistry`/`imageNamespace` values.
 */
export type HelmValuesWebhookImageRegistry = string;
/**
 * Full repository override (takes precedence over `imageRegistry`, `imageNamespace`, and `webhook.image.name`).
 */
export type HelmValuesWebhookImageRepository = string;
/**
 * Override the image tag to deploy by setting this variable. If no value is set, the chart's appVersion will be used.
 */
export type HelmValuesWebhookImageTag = string;
/**
 * Specify the load balancer IP for the created service.
 */
export type HelmValuesWebhookLoadBalancerIP = string;
/**
 * Egress rule for the webhook network policy. By default, it allows all outbound traffic to ports 80 and 443, as well as DNS ports.
 */
export type HelmValuesWebhookNetworkPolicy = unknown[];
/**
 * Create network policies for the webhooks.
 */
export type HelmValuesWebhookNetworkPolicyEnabled = boolean;
/**
 * Ingress rule for the webhook network policy.
 * By default all pods are allowed access to:
 *   https, http-metrics, and http-healthz ports
 */
export type HelmValuesWebhookNetworkPolicy1 = unknown[];
/**
 * Enable or disable the PodDisruptionBudget resource.
 *
 * This prevents downtime during voluntary disruptions such as during a Node upgrade. For example, the PodDisruptionBudget will block `kubectl drain` if it is used on the Node where the only remaining cert-manager
 * Pod is currently running.
 */
export type HelmValuesWebhookPodDisruptionBudgetEnabled = boolean;
/**
 * This configures how to act with unhealthy pods during eviction. Note that this requires Kubernetes 1.31 or `PDBUnhealthyPodEvictionPolicy` feature gate enabled for the cluster to work.
 */
export type HelmValuesWebhookPodDisruptionBudgetUnhealthyPodEvictionPolicy = string;
/**
 * Number of replicas of the cert-manager webhook to run.
 *
 * The default is 1, but in production set this to 2 or 3 to provide high availability.
 *
 * If `replicas > 1`, consider setting `webhook.podDisruptionBudget.enabled=true`.
 */
export type HelmValuesWebhookReplicaCount = number;
/**
 * A Kubernetes Runtime Class to apply to ACME HTTP01 solver pods, if required. For more information, see [Runtime Class](https://kubernetes.io/docs/concepts/containers/).
 *
 * For example:
 * runtimeClassName: gvisor
 */
export type HelmValuesWebhookRuntimeClassName = string;
/**
 * The port that the webhook listens on for requests. In GKE private clusters, by default Kubernetes apiservers are allowed to talk to the cluster nodes only on 443 and 10250. Configuring securePort: 10250, therefore will work out-of-the-box without needing to add firewall rules or requiring NET_BIND_SERVICE capabilities to bind port numbers <1000.
 */
export type HelmValuesWebhookSecurePort = number;
/**
 * Automount API credentials for a Service Account.
 */
export type HelmValuesWebhookServiceAccountAutomountServiceAccountToken = boolean;
/**
 * Specifies whether a service account should be created.
 */
export type HelmValuesWebhookServiceAccountCreate = boolean;
/**
 * The name of the service account to use.
 * If not set and create is true, a name is generated using the fullname template.
 */
export type HelmValuesWebhookServiceAccountName = string;
/**
 * Optionally set the IP families for the controller Service that should be supported, in the order in which they should be applied to ClusterIP. Can be IPv4 and/or IPv6.
 */
export type HelmValuesWebhook20 = unknown[];
/**
 * Optionally set the IP family policy for the controller Service to configure dual-stack; see [Configure dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services).
 */
export type HelmValuesWebhookServiceIPFamilyPolicy = string;
/**
 * Specifies how the service should be handled. Useful if you want to expose the webhook outside of the cluster. In some cases, the control plane cannot reach internal services.
 */
export type HelmValuesWebhookServiceType = string;
/**
 * The number of seconds the API server should wait for the webhook to respond before treating the call as a failure. The value must be between 1 and 30 seconds. For more information, see
 * [Validating webhook configuration v1](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1/).
 *
 * The default is set to the maximum value of 30 seconds as users sometimes report that the connection between the K8S API server and the cert-manager webhook server times out. If *this* timeout is reached, the error message will be "context deadline exceeded", which doesn't help the user diagnose what phase of the HTTPS connection timed out. For example, it could be during DNS resolution, TCP connection, TLS negotiation, HTTP negotiation, or slow HTTP response from the webhook server. By setting this timeout to its maximum value the underlying timeout error message has more chance of being returned to the end user.
 */
export type HelmValuesWebhookTimeoutSeconds = number;
/**
 * A list of Kubernetes Tolerations, if required. For more information, see [Toleration v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core).
 *
 * For example:
 * tolerations:
 * - key: foo.bar.com/role
 *   operator: Equal
 *   value: master
 *   effect: NoSchedule
 */
export type HelmValuesWebhook23 = unknown[];
/**
 * A list of Kubernetes TopologySpreadConstraints, if required. For more information, see [Topology spread constraint v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#topologyspreadconstraint-v1-core).
 *
 * For example:
 * topologySpreadConstraints:
 * - maxSkew: 2
 *   topologyKey: topology.kubernetes.io/zone
 *   whenUnsatisfiable: ScheduleAnyway
 *   labelSelector:
 *     matchLabels:
 *       app.kubernetes.io/instance: cert-manager
 *       app.kubernetes.io/component: controller
 */
export type HelmValuesWebhook24 = unknown[];
/**
 * Additional volume mounts to add to the cert-manager controller container.
 */
export type HelmValuesWebhook28 = unknown[];
/**
 * Additional volumes to add to the cert-manager controller pod.
 */
export type HelmValuesWebhook29 = unknown[];

export interface CertManagerValuesSchema {
  acmesolver?: HelmValues;
  affinity?: HelmValues1;
  approveSignerNames?: HelmValues2;
  automountServiceAccountToken?: HelmValuesAutomountServiceAccountToken;
  cainjector?: HelmValues3;
  clusterResourceNamespace?: HelmValuesClusterResourceNamespace;
  config?: HelmValues4;
  containerSecurityContext?: HelmValues5;
  crds?: HelmValues6;
  creator?: HelmValuesCreator;
  deploymentAnnotations?: HelmValues7;
  disableAutoApproval?: HelmValuesDisableAutoApproval;
  dns01RecursiveNameservers?: HelmValuesDns01RecursiveNameservers;
  dns01RecursiveNameserversOnly?: HelmValuesDns01RecursiveNameserversOnly;
  enableCertificateOwnerRef?: HelmValuesEnableCertificateOwnerRef;
  enableServiceLinks?: HelmValuesEnableServiceLinks;
  enabled?: HelmValuesEnabled;
  extraArgs?: HelmValues8;
  extraContainers?: HelmValues9;
  extraEnv?: HelmValues10;
  extraObjects?: HelmValues11;
  featureGates?: HelmValuesFeatureGates;
  fullnameOverride?: HelmValuesFullnameOverride;
  global?: HelmValues12;
  hostAliases?: HelmValues13;
  http_proxy?: HelmValuesHttpProxy;
  https_proxy?: HelmValuesHttpsProxy;
  image?: HelmValues14;
  imageNamespace?: HelmValuesImageNamespace;
  imageRegistry?: HelmValuesImageRegistry1;
  ingressShim?: HelmValues15;
  installCRDs?: HelmValuesInstallCRDs;
  livenessProbe?: HelmValues16;
  maxConcurrentChallenges?: HelmValuesMaxConcurrentChallenges;
  nameOverride?: HelmValuesNameOverride;
  namespace?: HelmValuesNamespace;
  networkPolicy?: HelmValues17;
  no_proxy?: HelmValuesNoProxy;
  nodeSelector?: HelmValues18;
  podAnnotations?: HelmValues19;
  podDisruptionBudget?: HelmValues20;
  podDnsConfig?: HelmValues21;
  podDnsPolicy?: HelmValuesPodDnsPolicy;
  podLabels?: HelmValues22;
  prometheus?: HelmValues23;
  replicaCount?: HelmValuesReplicaCount;
  resources?: HelmValues24;
  runtimeClassName?: HelmValuesRuntimeClassName;
  securityContext?: HelmValues25;
  serviceAccount?: HelmValues26;
  serviceAnnotations?: HelmValues27;
  serviceIPFamilies?: HelmValues28;
  serviceIPFamilyPolicy?: HelmValuesServiceIPFamilyPolicy;
  serviceLabels?: HelmValues29;
  startupapicheck?: HelmValues30;
  strategy?: HelmValues31;
  tolerations?: HelmValues32;
  topologySpreadConstraints?: HelmValues33;
  volumeMounts?: HelmValues34;
  volumes?: HelmValues35;
  webhook?: HelmValues36;
}
export interface HelmValues {
  image?: HelmValuesAcmesolver;
  runtimeClassName?: HelmValuesAcmesolverRuntimeClassName;
}
export interface HelmValuesAcmesolver {
  digest?: HelmValuesAcmesolverImageDigest;
  name?: HelmValuesAcmesolverImageName;
  pullPolicy?: HelmValuesAcmesolverImagePullPolicy;
  registry?: HelmValuesAcmesolverImageRegistry;
  repository?: HelmValuesAcmesolverImageRepository;
  tag?: HelmValuesAcmesolverImageTag;
}
/**
 * A Kubernetes Affinity, if required. For more information, see [Affinity v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core).
 *
 * For example:
 * affinity:
 *   nodeAffinity:
 *    requiredDuringSchedulingIgnoredDuringExecution:
 *      nodeSelectorTerms:
 *      - matchExpressions:
 *        - key: foo.bar.com/role
 *          operator: In
 *          values:
 *          - master
 */
export interface HelmValues1 {
  [k: string]: unknown;
}
export interface HelmValues3 {
  affinity?: HelmValuesCainjector;
  automountServiceAccountToken?: HelmValuesCainjectorAutomountServiceAccountToken;
  config?: HelmValuesCainjector1;
  containerSecurityContext?: HelmValuesCainjector2;
  deploymentAnnotations?: HelmValuesCainjector3;
  enableServiceLinks?: HelmValuesCainjectorEnableServiceLinks;
  enabled?: HelmValuesCainjectorEnabled;
  extraArgs?: HelmValuesCainjector4;
  extraEnv?: HelmValuesCainjector5;
  featureGates?: HelmValuesCainjectorFeatureGates;
  image?: HelmValuesCainjector6;
  networkPolicy?: HelmValuesCainjector7;
  nodeSelector?: HelmValuesCainjector8;
  podAnnotations?: HelmValuesCainjector9;
  podDisruptionBudget?: HelmValuesCainjector10;
  podLabels?: HelmValuesCainjector11;
  replicaCount?: HelmValuesCainjectorReplicaCount;
  resources?: HelmValuesCainjector12;
  runtimeClassName?: HelmValuesCainjectorRuntimeClassName;
  securityContext?: HelmValuesCainjector13;
  serviceAccount?: HelmValuesCainjector14;
  serviceAnnotations?: HelmValuesCainjector15;
  serviceLabels?: HelmValuesCainjector16;
  strategy?: HelmValuesCainjector17;
  tolerations?: HelmValuesCainjector18;
  topologySpreadConstraints?: HelmValuesCainjector19;
  volumeMounts?: HelmValuesCainjector20;
  volumes?: HelmValuesCainjector21;
}
/**
 * A Kubernetes Affinity, if required. For more information, see [Affinity v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core).
 *
 * For example:
 * affinity:
 *   nodeAffinity:
 *    requiredDuringSchedulingIgnoredDuringExecution:
 *      nodeSelectorTerms:
 *      - matchExpressions:
 *        - key: foo.bar.com/role
 *          operator: In
 *          values:
 *          - master
 */
export interface HelmValuesCainjector {
  [k: string]: unknown;
}
/**
 * This is used to configure options for the cainjector pod. It allows setting options that are usually provided via flags.
 *
 * If `apiVersion` and `kind` are unspecified they default to the current latest version (currently `cainjector.config.cert-manager.io/v1alpha1`). You can pin the version by specifying the `apiVersion` yourself.
 *
 * For example:
 * apiVersion: cainjector.config.cert-manager.io/v1alpha1
 * kind: CAInjectorConfiguration
 * logging:
 *  verbosity: 2
 *  format: text
 * leaderElectionConfig:
 *  namespace: kube-system
 * # Configure the metrics server for TLS
 * # See https://cert-manager.io/docs/devops-tips/prometheus-metrics/#tls
 * metricsTLSConfig:
 *   dynamic:
 *     secretNamespace: "cert-manager"
 *     secretName: "cert-manager-metrics-ca"
 *     dnsNames:
 *     - cert-manager-metrics
 */
export interface HelmValuesCainjector1 {
  [k: string]: unknown;
}
/**
 * Container Security Context to be set on the cainjector component container. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValuesCainjector2 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the cainjector Deployment.
 */
export interface HelmValuesCainjector3 {
  [k: string]: unknown;
}
export interface HelmValuesCainjector6 {
  digest?: HelmValuesCainjectorImageDigest;
  name?: HelmValuesCainjectorImageName;
  pullPolicy?: HelmValuesCainjectorImagePullPolicy;
  registry?: HelmValuesCainjectorImageRegistry;
  repository?: HelmValuesCainjectorImageRepository;
  tag?: HelmValuesCainjectorImageTag;
}
export interface HelmValuesCainjector7 {
  egress?: HelmValuesCainjectorNetworkPolicy;
  enabled?: HelmValuesCainjectorNetworkPolicyEnabled;
  ingress?: HelmValuesCainjectorNetworkPolicy1;
}
/**
 * The nodeSelector on Pods tells Kubernetes to schedule Pods on the nodes with matching labels. For more information, see [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).
 *
 * This default ensures that Pods are only scheduled to Linux nodes. It prevents Pods being scheduled to Windows nodes in a mixed OS cluster.
 */
export interface HelmValuesCainjector8 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the cainjector Pods.
 */
export interface HelmValuesCainjector9 {
  [k: string]: unknown;
}
export interface HelmValuesCainjector10 {
  enabled?: HelmValuesCainjectorPodDisruptionBudgetEnabled;
  maxUnavailable?: HelmValuesCainjectorPodDisruptionBudgetMaxUnavailable;
  minAvailable?: HelmValuesCainjectorPodDisruptionBudgetMinAvailable;
  unhealthyPodEvictionPolicy?: HelmValuesCainjectorPodDisruptionBudgetUnhealthyPodEvictionPolicy;
}
/**
 * `maxUnavailable` configures the maximum unavailable pods for disruptions. It can either be set to
 * an integer (e.g., 1) or a percentage value (e.g., 25%).
 * Cannot be used if `minAvailable` is set.
 */
export interface HelmValuesCainjectorPodDisruptionBudgetMaxUnavailable {
  [k: string]: unknown;
}
/**
 * `minAvailable` configures the minimum available pods for disruptions. It can either be set to
 * an integer (e.g., 1) or a percentage value (e.g., 25%).
 * Cannot be used if `maxUnavailable` is set.
 */
export interface HelmValuesCainjectorPodDisruptionBudgetMinAvailable {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the CA Injector Pods.
 */
export interface HelmValuesCainjector11 {
  [k: string]: unknown;
}
/**
 * Resources to provide to the cert-manager cainjector pod.
 *
 * For example:
 * requests:
 *   cpu: 10m
 *   memory: 32Mi
 * For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
 */
export interface HelmValuesCainjector12 {
  [k: string]: unknown;
}
/**
 * Pod Security Context to be set on the cainjector component Pod. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValuesCainjector13 {
  [k: string]: unknown;
}
export interface HelmValuesCainjector14 {
  annotations?: HelmValuesCainjectorServiceAccount;
  automountServiceAccountToken?: HelmValuesCainjectorServiceAccountAutomountServiceAccountToken;
  create?: HelmValuesCainjectorServiceAccountCreate;
  labels?: HelmValuesCainjectorServiceAccount1;
  name?: HelmValuesCainjectorServiceAccountName;
}
/**
 * Optional additional annotations to add to the cainjector's Service Account.
 */
export interface HelmValuesCainjectorServiceAccount {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the cainjector's Service Account.
 */
export interface HelmValuesCainjectorServiceAccount1 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the cainjector metrics Service.
 */
export interface HelmValuesCainjector15 {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the CA Injector metrics Service.
 */
export interface HelmValuesCainjector16 {
  [k: string]: unknown;
}
/**
 * Deployment update strategy for the cert-manager cainjector deployment. For more information, see the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy).
 *
 * For example:
 * strategy:
 *   type: RollingUpdate
 *   rollingUpdate:
 *     maxSurge: 0
 *     maxUnavailable: 1
 */
export interface HelmValuesCainjector17 {
  [k: string]: unknown;
}
/**
 * This property is used to configure options for the controller pod. This allows setting options that would usually be provided using flags.
 *
 * If `apiVersion` and `kind` are unspecified they default to the current latest version (currently `controller.config.cert-manager.io/v1alpha1`). You can pin the version by specifying the `apiVersion` yourself.
 *
 * For example:
 * config:
 *   apiVersion: controller.config.cert-manager.io/v1alpha1
 *   kind: ControllerConfiguration
 *   logging:
 *     verbosity: 2
 *     format: text
 *   leaderElectionConfig:
 *     namespace: kube-system
 *   kubernetesAPIQPS: 9000
 *   kubernetesAPIBurst: 9000
 *   numberOfConcurrentWorkers: 200
 *   gatewayAPI:
 *     enabled: true
 *   # Feature gates as of v1.20.0. Listed with their default values.
 *   # See https://cert-manager.io/docs/cli/controller/
 *   featureGates:
 *     AllAlpha: false # ALPHA - default=false
 *     AllBeta: false # BETA - default=false
 *     ACMEHTTP01IngressPathTypeExact: true # BETA - default=true
 *     ExperimentalCertificateSigningRequestControllers: false # ALPHA - default=false
 *     ExperimentalGatewayAPISupport: true # BETA - default=true
 *     LiteralCertificateSubject: true # BETA - default=true
 *     NameConstraints: true # BETA - default=true
 *     OtherNames: true # BETA - default=true
 *     SecretsFilteredCaching: true # BETA - default=true
 *     ServerSideApply: false # ALPHA - default=false
 *     StableCertificateRequestName: true # BETA - default=true
 *     UseCertificateRequestBasicConstraints: false # ALPHA - default=false
 *   # Configure the metrics server for TLS
 *   # See https://cert-manager.io/docs/devops-tips/prometheus-metrics/#tls
 *   metricsTLSConfig:
 *     dynamic:
 *       secretNamespace: "cert-manager"
 *       secretName: "cert-manager-metrics-ca"
 *       dnsNames:
 *       - cert-manager-metrics
 *   # Configure PEM size limits for certificate validation
 *   # Useful for certificates with many DNS names (e.g., Istio gateways with 100+ DNS names)
 *   pemSizeLimitsConfig:
 *     maxCertificateSize: 36500     # Maximum size in bytes for individual certificates (default: 36500)
 *     maxPrivateKeySize: 13000      # Maximum size in bytes for private keys (default: 13000)
 *     maxChainLength: 95000         # Maximum size in bytes for certificate chains (default: 95000)
 *     maxBundleSize: 330000         # Maximum size in bytes for certificate bundles (default: 330000)
 *   # Configure certificate request backoff durations
 *   certificateRequestMinimumBackoffDuration: 1h
 *   certificateRequestMaximumBackoffDuration: 32h
 */
export interface HelmValues4 {
  [k: string]: unknown;
}
/**
 * Container Security Context to be set on the controller component container. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValues5 {
  [k: string]: unknown;
}
export interface HelmValues6 {
  enabled?: HelmValuesCrdsEnabled;
  keep?: HelmValuesCrdsKeep;
}
/**
 * Optional additional annotations to add to the controller Deployment.
 */
export interface HelmValues7 {
  [k: string]: unknown;
}
/**
 * Global values shared across all (sub)charts
 */
export interface HelmValues12 {
  commonLabels?: HelmValuesGlobal;
  hostUsers?: HelmValuesGlobalHostUsers;
  imagePullSecrets?: HelmValuesGlobal1;
  leaderElection?: HelmValuesGlobal2;
  logLevel?: HelmValuesGlobalLogLevel;
  nodeSelector?: HelmValuesGlobal3;
  podSecurityPolicy?: HelmValuesGlobal4;
  priorityClassName?: HelmValuesGlobalPriorityClassName;
  rbac?: HelmValuesGlobal5;
  revisionHistoryLimit?: HelmValuesGlobalRevisionHistoryLimit;
  runtimeClassName?: HelmValuesGlobalRuntimeClassName;
  [k: string]: unknown;
}
/**
 * Labels to apply to all resources.
 * These labels are also applied to dynamically-created ACME HTTP01 solver resources
 * (pods, services, ingresses, or Gateway API HTTPRoutes).
 * The following ACME identity label keys are reserved and will be silently ignored on dynamically-created resources: acme.cert-manager.io/http-domain, acme.cert-manager.io/http-token, acme.cert-manager.io/http01-solver. For per-Issuer-specific labels, use the HTTP01 ingress solver podTemplate and ingressTemplate fields for pod/ingress resources, or the gatewayHTTPRoute solver labels field for Gateway API HTTPRoute resources.
 */
export interface HelmValuesGlobal {
  [k: string]: unknown;
}
export interface HelmValuesGlobal2 {
  leaseDuration?: HelmValuesGlobalLeaderElectionLeaseDuration;
  namespace?: HelmValuesGlobalLeaderElectionNamespace;
  renewDeadline?: HelmValuesGlobalLeaderElectionRenewDeadline;
  retryPeriod?: HelmValuesGlobalLeaderElectionRetryPeriod;
  [k: string]: unknown;
}
/**
 * Global node selector
 *
 * The nodeSelector on Pods tells Kubernetes to schedule Pods on the nodes with matching labels. For more information, see [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).
 *
 * If a component-specific nodeSelector is also set, it will be merged and take precedence.
 */
export interface HelmValuesGlobal3 {
  [k: string]: unknown;
}
export interface HelmValuesGlobal4 {
  enabled?: HelmValuesGlobalPodSecurityPolicyEnabled;
  useAppArmor?: HelmValuesGlobalPodSecurityPolicyUseAppArmor;
  [k: string]: unknown;
}
export interface HelmValuesGlobal5 {
  aggregateClusterRoles?: HelmValuesGlobalRbacAggregateClusterRoles;
  create?: HelmValuesGlobalRbacCreate;
  [k: string]: unknown;
}
export interface HelmValues14 {
  digest?: HelmValuesImageDigest;
  name?: HelmValuesImageName;
  pullPolicy?: HelmValuesImagePullPolicy;
  registry?: HelmValuesImageRegistry;
  repository?: HelmValuesImageRepository;
  tag?: HelmValuesImageTag;
}
export interface HelmValues15 {
  defaultIssuerGroup?: HelmValuesIngressShimDefaultIssuerGroup;
  defaultIssuerKind?: HelmValuesIngressShimDefaultIssuerKind;
  defaultIssuerName?: HelmValuesIngressShimDefaultIssuerName;
}
/**
 * LivenessProbe settings for the controller container of the controller Pod.
 *
 * This is enabled by default, in order to enable the clock-skew liveness probe that restarts the controller in case of a skew between the system clock and the monotonic clock. LivenessProbe durations and thresholds are based on those used for the Kubernetes controller-manager. For more information see the following on the
 * [Kubernetes GitHub repository](https://github.com/kubernetes/kubernetes/blob/806b30170c61a38fedd54cc9ede4cd6275a1ad3b/cmd/kubeadm/app/util/staticpod/utils.go#L241-L245)
 */
export interface HelmValues16 {
  [k: string]: unknown;
}
export interface HelmValues17 {
  egress?: HelmValuesNetworkPolicy;
  enabled?: HelmValuesNetworkPolicyEnabled;
  ingress?: HelmValuesNetworkPolicy1;
}
/**
 * The nodeSelector on Pods tells Kubernetes to schedule Pods on the nodes with matching labels. For more information, see [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).
 *
 * This default ensures that Pods are only scheduled to Linux nodes. It prevents Pods being scheduled to Windows nodes in a mixed OS cluster.
 */
export interface HelmValues18 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the controller Pods.
 */
export interface HelmValues19 {
  [k: string]: unknown;
}
export interface HelmValues20 {
  enabled?: HelmValuesPodDisruptionBudgetEnabled;
  maxUnavailable?: HelmValuesPodDisruptionBudgetMaxUnavailable;
  minAvailable?: HelmValuesPodDisruptionBudgetMinAvailable;
  unhealthyPodEvictionPolicy?: HelmValuesPodDisruptionBudgetUnhealthyPodEvictionPolicy;
}
/**
 * This configures the maximum unavailable pods for disruptions. It can either be set to an integer (e.g., 1) or a percentage value (e.g., 25%). it cannot be used if `minAvailable` is set.
 */
export interface HelmValuesPodDisruptionBudgetMaxUnavailable {
  [k: string]: unknown;
}
/**
 * This configures the minimum available pods for disruptions. It can either be set to an integer (e.g., 1) or a percentage value (e.g., 25%).
 * It cannot be used if `maxUnavailable` is set.
 */
export interface HelmValuesPodDisruptionBudgetMinAvailable {
  [k: string]: unknown;
}
/**
 * Pod DNS configuration. The podDnsConfig field is optional and can work with any podDnsPolicy settings. However, when a Pod's dnsPolicy is set to "None", the dnsConfig field has to be specified. For more information, see [Pod's DNS Config](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config).
 */
export interface HelmValues21 {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the controller Pods.
 */
export interface HelmValues22 {
  [k: string]: unknown;
}
export interface HelmValues23 {
  enabled?: HelmValuesPrometheusEnabled;
  podmonitor?: HelmValuesPrometheus;
  servicemonitor?: HelmValuesPrometheus1;
}
export interface HelmValuesPrometheus {
  annotations?: HelmValuesPrometheusPodmonitor;
  enabled?: HelmValuesPrometheusPodmonitorEnabled;
  endpointAdditionalProperties?: HelmValuesPrometheusPodmonitor1;
  honorLabels?: HelmValuesPrometheusPodmonitorHonorLabels;
  interval?: HelmValuesPrometheusPodmonitorInterval;
  labels?: HelmValuesPrometheusPodmonitor2;
  namespace?: HelmValuesPrometheusPodmonitorNamespace;
  prometheusInstance?: HelmValuesPrometheusPodmonitorPrometheusInstance;
  scrapeTimeout?: HelmValuesPrometheusPodmonitorScrapeTimeout;
}
/**
 * Additional annotations to add to the PodMonitor.
 */
export interface HelmValuesPrometheusPodmonitor {
  [k: string]: unknown;
}
/**
 * EndpointAdditionalProperties allows setting additional properties on the endpoint such as relabelings, metricRelabelings etc.
 *
 * For example:
 * endpointAdditionalProperties:
 *  relabelings:
 *  - action: replace
 *    sourceLabels:
 *    - __meta_kubernetes_pod_node_name
 *    targetLabel: instance
 *  # Configure the PodMonitor for TLS connections
 *  # See https://cert-manager.io/docs/devops-tips/prometheus-metrics/#tls
 *  scheme: https
 *  tlsConfig:
 *    serverName: cert-manager-metrics
 *    ca:
 *      secret:
 *        name: cert-manager-metrics-ca
 *        key: "tls.crt"
 */
export interface HelmValuesPrometheusPodmonitor1 {
  [k: string]: unknown;
}
/**
 * Additional labels to add to the PodMonitor.
 */
export interface HelmValuesPrometheusPodmonitor2 {
  [k: string]: unknown;
}
export interface HelmValuesPrometheus1 {
  annotations?: HelmValuesPrometheusServicemonitor;
  enabled?: HelmValuesPrometheusServicemonitorEnabled;
  endpointAdditionalProperties?: HelmValuesPrometheusServicemonitor1;
  honorLabels?: HelmValuesPrometheusServicemonitorHonorLabels;
  interval?: HelmValuesPrometheusServicemonitorInterval;
  labels?: HelmValuesPrometheusServicemonitor2;
  namespace?: HelmValuesPrometheusServicemonitorNamespace;
  prometheusInstance?: HelmValuesPrometheusServicemonitorPrometheusInstance;
  scrapeTimeout?: HelmValuesPrometheusServicemonitorScrapeTimeout;
}
/**
 * Additional annotations to add to the ServiceMonitor.
 */
export interface HelmValuesPrometheusServicemonitor {
  [k: string]: unknown;
}
/**
 * EndpointAdditionalProperties allows setting additional properties on the endpoint such as relabelings, metricRelabelings etc.
 *
 * For example:
 * endpointAdditionalProperties:
 *  relabelings:
 *  - action: replace
 *    sourceLabels:
 *    - __meta_kubernetes_pod_node_name
 *    targetLabel: instance
 */
export interface HelmValuesPrometheusServicemonitor1 {
  [k: string]: unknown;
}
/**
 * Additional labels to add to the ServiceMonitor.
 */
export interface HelmValuesPrometheusServicemonitor2 {
  [k: string]: unknown;
}
/**
 * Resources to provide to the cert-manager controller pod.
 *
 * For example:
 * requests:
 *   cpu: 10m
 *   memory: 32Mi
 * For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
 */
export interface HelmValues24 {
  [k: string]: unknown;
}
/**
 * Pod Security Context.
 * For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValues25 {
  [k: string]: unknown;
}
export interface HelmValues26 {
  annotations?: HelmValuesServiceAccount;
  automountServiceAccountToken?: HelmValuesServiceAccountAutomountServiceAccountToken;
  create?: HelmValuesServiceAccountCreate;
  labels?: HelmValuesServiceAccount1;
  name?: HelmValuesServiceAccountName;
}
/**
 * Optional additional annotations to add to the controller's Service Account. Templates are allowed for both keys and values.
 * Example using templating:
 * annotations:
 *   "{{ .Chart.Name }}-helm-chart/version": "{{ .Chart.Version }}"
 */
export interface HelmValuesServiceAccount {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the controller's Service Account.
 */
export interface HelmValuesServiceAccount1 {
  [k: string]: unknown;
}
/**
 * Optional annotations to add to the controller Service.
 */
export interface HelmValues27 {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the controller Service.
 */
export interface HelmValues29 {
  [k: string]: unknown;
}
export interface HelmValues30 {
  affinity?: HelmValuesStartupapicheck;
  automountServiceAccountToken?: HelmValuesStartupapicheckAutomountServiceAccountToken;
  backoffLimit?: HelmValuesStartupapicheckBackoffLimit;
  containerSecurityContext?: HelmValuesStartupapicheck1;
  enableServiceLinks?: HelmValuesStartupapicheckEnableServiceLinks;
  enabled?: HelmValuesStartupapicheckEnabled;
  extraArgs?: HelmValuesStartupapicheck2;
  extraEnv?: HelmValuesStartupapicheck3;
  image?: HelmValuesStartupapicheck4;
  jobAnnotations?: HelmValuesStartupapicheck5;
  nodeSelector?: HelmValuesStartupapicheck6;
  podAnnotations?: HelmValuesStartupapicheck7;
  podLabels?: HelmValuesStartupapicheck8;
  rbac?: HelmValuesStartupapicheck9;
  resources?: HelmValuesStartupapicheck10;
  runtimeClassName?: HelmValuesStartupapicheckRuntimeClassName;
  securityContext?: HelmValuesStartupapicheck11;
  serviceAccount?: HelmValuesStartupapicheck12;
  timeout?: HelmValuesStartupapicheckTimeout;
  tolerations?: HelmValuesStartupapicheck13;
  ttlSecondsAfterFinished?: HelmValuesStartupapicheckTtlSecondsAfterFinished;
  volumeMounts?: HelmValuesStartupapicheck14;
  volumes?: HelmValuesStartupapicheck15;
}
/**
 * A Kubernetes Affinity, if required. For more information, see [Affinity v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core).
 * For example:
 * affinity:
 *   nodeAffinity:
 *    requiredDuringSchedulingIgnoredDuringExecution:
 *      nodeSelectorTerms:
 *      - matchExpressions:
 *        - key: foo.bar.com/role
 *          operator: In
 *          values:
 *          - master
 */
export interface HelmValuesStartupapicheck {
  [k: string]: unknown;
}
/**
 * Container Security Context to be set on the controller component container. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValuesStartupapicheck1 {
  [k: string]: unknown;
}
export interface HelmValuesStartupapicheck4 {
  digest?: HelmValuesStartupapicheckImageDigest;
  name?: HelmValuesStartupapicheckImageName;
  pullPolicy?: HelmValuesStartupapicheckImagePullPolicy;
  registry?: HelmValuesStartupapicheckImageRegistry;
  repository?: HelmValuesStartupapicheckImageRepository;
  tag?: HelmValuesStartupapicheckImageTag;
}
/**
 * Optional additional annotations to add to the startupapicheck Job.
 */
export interface HelmValuesStartupapicheck5 {
  [k: string]: unknown;
}
/**
 * The nodeSelector on Pods tells Kubernetes to schedule Pods on the nodes with matching labels. For more information, see [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).
 *
 * This default ensures that Pods are only scheduled to Linux nodes. It prevents Pods being scheduled to Windows nodes in a mixed OS cluster.
 */
export interface HelmValuesStartupapicheck6 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the startupapicheck Pods.
 */
export interface HelmValuesStartupapicheck7 {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the startupapicheck Pods.
 */
export interface HelmValuesStartupapicheck8 {
  [k: string]: unknown;
}
export interface HelmValuesStartupapicheck9 {
  annotations?: HelmValuesStartupapicheckRbac;
}
/**
 * annotations for the startup API Check job RBAC and PSP resources.
 */
export interface HelmValuesStartupapicheckRbac {
  [k: string]: unknown;
}
/**
 * Resources to provide to the cert-manager startupapicheck pod.
 *
 * For example:
 * requests:
 *   cpu: 10m
 *   memory: 32Mi
 * For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
 */
export interface HelmValuesStartupapicheck10 {
  [k: string]: unknown;
}
/**
 * Pod Security Context to be set on the startupapicheck component Pod. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValuesStartupapicheck11 {
  [k: string]: unknown;
}
export interface HelmValuesStartupapicheck12 {
  annotations?: HelmValuesStartupapicheckServiceAccount;
  automountServiceAccountToken?: HelmValuesStartupapicheckServiceAccountAutomountServiceAccountToken;
  create?: HelmValuesStartupapicheckServiceAccountCreate;
  labels?: HelmValuesStartupapicheckServiceAccount1;
  name?: HelmValuesStartupapicheckServiceAccountName;
}
/**
 * Optional additional annotations to add to the Job's Service Account.
 */
export interface HelmValuesStartupapicheckServiceAccount {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the startupapicheck's Service Account.
 */
export interface HelmValuesStartupapicheckServiceAccount1 {
  [k: string]: unknown;
}
/**
 * Limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, once the Job finishes, it will be automatically cleaned up after ttlSecondsAfterFinished seconds. This is disabled by default (field is not set) to preserve backward compatibility and avoid issues with GitOps tools (e.g. Argo CD) that may attempt to reconcile or recreate Jobs after they are automatically deleted. For more information, see [Automatic Cleanup for Finished Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/).
 */
export interface HelmValuesStartupapicheckTtlSecondsAfterFinished {
  [k: string]: unknown;
}
/**
 * Deployment update strategy for the cert-manager controller deployment. For more information, see the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy).
 *
 * For example:
 * strategy:
 *   type: RollingUpdate
 *   rollingUpdate:
 *     maxSurge: 0
 *     maxUnavailable: 1
 */
export interface HelmValues31 {
  [k: string]: unknown;
}
export interface HelmValues36 {
  affinity?: HelmValuesWebhook;
  apiserverClientCertSubjects?: HelmValuesWebhookApiserverClientCertSubjects;
  automountServiceAccountToken?: HelmValuesWebhookAutomountServiceAccountToken;
  clientCAFile?: HelmValuesWebhookClientCAFile;
  config?: HelmValuesWebhook1;
  containerSecurityContext?: HelmValuesWebhook2;
  deploymentAnnotations?: HelmValuesWebhook3;
  enableClientVerification?: HelmValuesWebhookEnableClientVerification;
  enableServiceLinks?: HelmValuesWebhookEnableServiceLinks;
  extraArgs?: HelmValuesWebhook4;
  extraEnv?: HelmValuesWebhook5;
  featureGates?: HelmValuesWebhookFeatureGates;
  hostNetwork?: HelmValuesWebhookHostNetwork;
  image?: HelmValuesWebhook6;
  livenessProbe?: HelmValuesWebhook7;
  loadBalancerIP?: HelmValuesWebhookLoadBalancerIP;
  mutatingWebhookConfiguration?: HelmValuesWebhook8;
  mutatingWebhookConfigurationAnnotations?: HelmValuesWebhook9;
  networkPolicy?: HelmValuesWebhook10;
  nodeSelector?: HelmValuesWebhook11;
  podAnnotations?: HelmValuesWebhook12;
  podDisruptionBudget?: HelmValuesWebhook13;
  podLabels?: HelmValuesWebhook14;
  readinessProbe?: HelmValuesWebhook15;
  replicaCount?: HelmValuesWebhookReplicaCount;
  resources?: HelmValuesWebhook16;
  runtimeClassName?: HelmValuesWebhookRuntimeClassName;
  securePort?: HelmValuesWebhookSecurePort;
  securityContext?: HelmValuesWebhook17;
  serviceAccount?: HelmValuesWebhook18;
  serviceAnnotations?: HelmValuesWebhook19;
  serviceIPFamilies?: HelmValuesWebhook20;
  serviceIPFamilyPolicy?: HelmValuesWebhookServiceIPFamilyPolicy;
  serviceLabels?: HelmValuesWebhook21;
  serviceType?: HelmValuesWebhookServiceType;
  strategy?: HelmValuesWebhook22;
  timeoutSeconds?: HelmValuesWebhookTimeoutSeconds;
  tolerations?: HelmValuesWebhook23;
  topologySpreadConstraints?: HelmValuesWebhook24;
  url?: HelmValuesWebhook25;
  validatingWebhookConfiguration?: HelmValuesWebhook26;
  validatingWebhookConfigurationAnnotations?: HelmValuesWebhook27;
  volumeMounts?: HelmValuesWebhook28;
  volumes?: HelmValuesWebhook29;
}
/**
 * A Kubernetes Affinity, if required. For more information, see [Affinity v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core).
 *
 * For example:
 * affinity:
 *   nodeAffinity:
 *    requiredDuringSchedulingIgnoredDuringExecution:
 *      nodeSelectorTerms:
 *      - matchExpressions:
 *        - key: foo.bar.com/role
 *          operator: In
 *          values:
 *          - master
 */
export interface HelmValuesWebhook {
  [k: string]: unknown;
}
/**
 * This is used to configure options for the webhook pod. This allows setting options that would usually be provided using flags.
 *
 * If `apiVersion` and `kind` are unspecified they default to the current latest version (currently `webhook.config.cert-manager.io/v1alpha1`). You can pin the version by specifying the `apiVersion` yourself.
 *
 * For example:
 * apiVersion: webhook.config.cert-manager.io/v1alpha1
 * kind: WebhookConfiguration
 * # The port that the webhook listens on for requests.
 * # In GKE private clusters, by default Kubernetes apiservers are allowed to
 * # talk to the cluster nodes only on 443 and 10250. Configuring
 * # securePort: 10250 therefore will work out-of-the-box without needing to add firewall
 * # rules or requiring NET_BIND_SERVICE capabilities to bind port numbers < 1000.
 * # This should be uncommented and set as a default by the chart once
 * # the apiVersion of WebhookConfiguration graduates beyond v1alpha1.
 * securePort: 10250
 * # Configure the metrics server for TLS
 * # See https://cert-manager.io/docs/devops-tips/prometheus-metrics/#tls
 * metricsTLSConfig:
 *   dynamic:
 *     secretNamespace: "cert-manager"
 *     secretName: "cert-manager-metrics-ca"
 *     dnsNames:
 *     - cert-manager-metrics
 */
export interface HelmValuesWebhook1 {
  [k: string]: unknown;
}
/**
 * Container Security Context to be set on the webhook component container. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValuesWebhook2 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the webhook Deployment.
 */
export interface HelmValuesWebhook3 {
  [k: string]: unknown;
}
export interface HelmValuesWebhook6 {
  digest?: HelmValuesWebhookImageDigest;
  name?: HelmValuesWebhookImageName;
  pullPolicy?: HelmValuesWebhookImagePullPolicy;
  registry?: HelmValuesWebhookImageRegistry;
  repository?: HelmValuesWebhookImageRepository;
  tag?: HelmValuesWebhookImageTag;
}
/**
 * Liveness probe values.
 * For more information, see [Container probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes).
 */
export interface HelmValuesWebhook7 {
  [k: string]: unknown;
}
export interface HelmValuesWebhook8 {
  namespaceSelector?: HelmValuesWebhookMutatingWebhookConfiguration;
}
/**
 * Configure spec.namespaceSelector for mutating webhooks.
 */
export interface HelmValuesWebhookMutatingWebhookConfiguration {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the webhook MutatingWebhookConfiguration.
 */
export interface HelmValuesWebhook9 {
  [k: string]: unknown;
}
export interface HelmValuesWebhook10 {
  egress?: HelmValuesWebhookNetworkPolicy;
  enabled?: HelmValuesWebhookNetworkPolicyEnabled;
  ingress?: HelmValuesWebhookNetworkPolicy1;
}
/**
 * The nodeSelector on Pods tells Kubernetes to schedule Pods on the nodes with matching labels. For more information, see [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).
 *
 * This default ensures that Pods are only scheduled to Linux nodes. It prevents Pods being scheduled to Windows nodes in a mixed OS cluster.
 */
export interface HelmValuesWebhook11 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the webhook Pods.
 */
export interface HelmValuesWebhook12 {
  [k: string]: unknown;
}
export interface HelmValuesWebhook13 {
  enabled?: HelmValuesWebhookPodDisruptionBudgetEnabled;
  maxUnavailable?: HelmValuesWebhookPodDisruptionBudgetMaxUnavailable;
  minAvailable?: HelmValuesWebhookPodDisruptionBudgetMinAvailable;
  unhealthyPodEvictionPolicy?: HelmValuesWebhookPodDisruptionBudgetUnhealthyPodEvictionPolicy;
}
/**
 * This property configures the maximum unavailable pods for disruptions. Can either be set to an integer (e.g., 1) or a percentage value (e.g., 25%).
 * It cannot be used if `minAvailable` is set.
 */
export interface HelmValuesWebhookPodDisruptionBudgetMaxUnavailable {
  [k: string]: unknown;
}
/**
 * This property configures the minimum available pods for disruptions. Can either be set to an integer (e.g., 1) or a percentage value (e.g., 25%).
 * It cannot be used if `maxUnavailable` is set.
 */
export interface HelmValuesWebhookPodDisruptionBudgetMinAvailable {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the Webhook Pods.
 */
export interface HelmValuesWebhook14 {
  [k: string]: unknown;
}
/**
 * Readiness probe values.
 * For more information, see [Container probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes).
 */
export interface HelmValuesWebhook15 {
  [k: string]: unknown;
}
/**
 * Resources to provide to the cert-manager webhook pod.
 *
 * For example:
 * requests:
 *   cpu: 10m
 *   memory: 32Mi
 * For more information, see [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
 */
export interface HelmValuesWebhook16 {
  [k: string]: unknown;
}
/**
 * Pod Security Context to be set on the webhook component Pod. For more information, see [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
 */
export interface HelmValuesWebhook17 {
  [k: string]: unknown;
}
export interface HelmValuesWebhook18 {
  annotations?: HelmValuesWebhookServiceAccount;
  automountServiceAccountToken?: HelmValuesWebhookServiceAccountAutomountServiceAccountToken;
  create?: HelmValuesWebhookServiceAccountCreate;
  labels?: HelmValuesWebhookServiceAccount1;
  name?: HelmValuesWebhookServiceAccountName;
}
/**
 * Optional additional annotations to add to the webhook's Service Account.
 */
export interface HelmValuesWebhookServiceAccount {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the webhook's Service Account.
 */
export interface HelmValuesWebhookServiceAccount1 {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the webhook Service.
 */
export interface HelmValuesWebhook19 {
  [k: string]: unknown;
}
/**
 * Optional additional labels to add to the Webhook Service.
 */
export interface HelmValuesWebhook21 {
  [k: string]: unknown;
}
/**
 * The update strategy for the cert-manager webhook deployment. For more information, see the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy)
 *
 * For example:
 * strategy:
 *   type: RollingUpdate
 *   rollingUpdate:
 *     maxSurge: 0
 *     maxUnavailable: 1
 */
export interface HelmValuesWebhook22 {
  [k: string]: unknown;
}
/**
 * Overrides the mutating webhook and validating webhook so they reach the webhook service using the `url` field instead of a service.
 */
export interface HelmValuesWebhook25 {
  [k: string]: unknown;
}
export interface HelmValuesWebhook26 {
  namespaceSelector?: HelmValuesWebhookValidatingWebhookConfiguration;
}
/**
 * Configure spec.namespaceSelector for validating webhooks.
 */
export interface HelmValuesWebhookValidatingWebhookConfiguration {
  [k: string]: unknown;
}
/**
 * Optional additional annotations to add to the webhook ValidatingWebhookConfiguration.
 */
export interface HelmValuesWebhook27 {
  [k: string]: unknown;
}
