/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The metadata_files attribute is used to define Metadata Files by specifying the path of the files that will be executed against the parent library.
 */
export type MetadataFiles = (string | FilePath | FolderPath | UrlPath | GitPath | RepoPath)[];
export type KometaDefaultCollectionPath = {
  default:
    | "actor"
    | "anilist"
    | "aspect"
    | "audio_language"
    | "bafta"
    | "based"
    | "basic"
    | "berlinale"
    | "cannes"
    | "cesar"
    | "choice"
    | "collectionless"
    | "content_rating_au"
    | "content_rating_cs"
    | "content_rating_de"
    | "content_rating_nz"
    | "content_rating_mal"
    | "content_rating_uk"
    | "content_rating_us"
    | "continent"
    | "country"
    | "decade"
    | "director"
    | "emmy"
    | "flixpatrol"
    | "franchise"
    | "genre"
    | "golden"
    | "imdb"
    | "letterboxd"
    | "myanimelist"
    | "network"
    | "nfr"
    | "oscars"
    | "other_chart"
    | "pca"
    | "producer"
    | "razzie"
    | "region"
    | "resolution"
    | "sag"
    | "seasonal"
    | "separator_award"
    | "separator_chart"
    | "simkl"
    | "spirit"
    | "streaming"
    | "studio"
    | "subtitle_language"
    | "sundance"
    | "tautulli"
    | "tracearr"
    | "tiff"
    | "tmdb"
    | "trakt"
    | "universe"
    | "venice"
    | "writer"
    | "year";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: {
    [k: string]: unknown;
  };
};
/**
 * The collection_files attribute is used to define Collection Files by specifying the path type and path of the files that will be executed against the parent library.
 */
export type CollectionFiles = (
  | string
  | LegacyDefaultCollectionPath
  | KometaDefaultCollectionPath
  | FilePath
  | FilePathCollectionWithTemplateVariables
  | FolderPath
  | UrlPath
  | UrlPathCollectionWithTemplateVariables
  | GitPath
  | GitPathCollectionWithTemplateVariables
  | RepoPath
  | RepoPathCollectionWithTemplateVariables
)[];
/**
 * The overlay_files attribute is used to define Overlay Files by specifying the path type and path of the files that will be executed against the parent library.
 */
export type OverlayFiles = (
  | string
  | LegacyDefaultOverlayPath
  | KometaDefaultOverlayPath
  | FilePath
  | FilePathOverlayWithTemplateVariables
  | FolderPath
  | UrlPath
  | UrlPathOverlayWithTemplateVariables
  | GitPath
  | GitPathOverlayWithTemplateVariables
  | RepoPath
  | RepoPathOverlayWithTemplateVariables
)[];
/**
 * DEPRECATED! Use: metadata_files.
 * The metadata_path attribute is used to define Metadata Files by specifying the path of the files that will be executed against the parent library.
 */
export type MetadataPath = (
  | LegacyDefaultCollectionPath1
  | KometaDefaultCollectionPath
  | FilePath
  | FilePathCollectionWithTemplateVariables
  | FolderPath
  | UrlPath
  | UrlPathCollectionWithTemplateVariables
  | GitPath
  | GitPathCollectionWithTemplateVariables
  | RepoPath
  | RepoPathCollectionWithTemplateVariables
)[];
/**
 * DEPRECATED! Use: overlay_files.
 * The overlay_path attribute is used to define Overlay Files by specifying the path type and path of the files that will be executed against the parent library.
 */
export type OverlayPath = (
  | LegacyDefaultOverlayPath1
  | KometaDefaultOverlayPath
  | FilePath
  | FilePathOverlayWithTemplateVariables
  | FolderPath
  | UrlPath
  | UrlPathOverlayWithTemplateVariables
  | GitPath
  | GitPathOverlayWithTemplateVariables
  | RepoPath
  | RepoPathOverlayWithTemplateVariables
)[];
export type MassMetadataSource = (string | number) | ((string | number) | string[])[];
export type MassMetadataScheduledCollectionMode =
  | ("default" | "hide" | "hide_items" | "show_items")
  | {
      schedule?: string;
      mode: "default" | "hide" | "hide_items" | "show_items";
    };
export type MassMetadataScheduledLabels =
  | ("none" | "mild" | "moderate" | "severe")
  | {
      schedule?: string;
      severity: "none" | "mild" | "moderate" | "severe";
    };
export type MassMetadataScheduledSource =
  | MassMetadataSource
  | {
      schedule?: string;
      source?: MassMetadataSource;
    };
export type MassMetadataImage =
  | string
  | {
      schedule?: string;
      source?: string | string[];
      language?: string;
      seasons?: boolean;
      episodes?: boolean;
      ignore_locked?: boolean;
      ignore_overlays?: boolean;
    };
export type PlaylistFiles = (
  | LegacyDefaultPlaylistPath
  | KometaDefaultPlaylistPath
  | FilePath
  | FilePathPlaylistWithTemplateVariables
  | FolderPath
  | UrlPath
  | UrlPathPlaylistWithTemplateVariables
  | GitPath
  | GitPathPlaylistWithTemplateVariables
  | RepoPath
  | RepoPathPlaylistWithTemplateVariables
)[];

export interface KometaConfigSchema {
  libraries?: Libraries;
  plex: Plex1;
  tmdb: Tmdb;
  tautulli?: Tautulli;
  tracearr?: Tracearr;
  webhooks?: Webhooks;
  omdb?: Omdb;
  mdblist?: Mdblist;
  notifiarr?: Notifiarr;
  gotify?: Gotify;
  ntfy?: Ntfy;
  anidb?: Anidb;
  sonarr?: Sonarr1;
  radarr?: Radarr1;
  settings?: Settings;
  mal?: Mal;
  trakt?: Trakt;
  yamtrack?: Yamtrack;
  serializd?: Serializd;
  floppy?: Floppy;
  github?: Github;
  playlist_files?: PlaylistFiles;
  [k: string]: unknown;
}
export interface Libraries {
  /**
   * This interface was referenced by `Libraries`'s JSON-Schema definition
   * via the `patternProperty` "^(?!plex|tmdb|tautulli|webhooks|omdb|mdblist|notifiarr|gotify|ntfy|anidb|radarr|sonarr|trakt|yamtrack|serializd|floppy|mal).+$".
   *
   * This interface was referenced by `Libraries`'s JSON-Schema definition
   * via the `patternProperty` "^schedule_.*$".
   */
  [k: string]:
    | {
        metadata_files?: MetadataFiles;
        collection_files?: CollectionFiles;
        overlay_files?: OverlayFiles;
        metadata_path?: MetadataPath;
        overlay_path?: OverlayPath;
        /**
         * Used to specify Library Operations to run.
         */
        operations?:
          | Operations
          | {
              [k: string]: unknown;
            }[];
        /**
         * Used to specify the Library's name.
         * Required only when trying to use multiple servers with the same name. Each library that the user wants Kometa to interact with must be documented with a library attribute. A library attribute is represented by the mapping name (i.e. Movies or TV Shows), this must have a unique name that correlates with a library of the same name within the Plex Media Server. In the situation that two servers are being connected to which both have libraries of the same name, the library_name attribute can be utilized to specify the real Library Name, whilst the library attribute's mapping name can be made into a placeholder.
         */
        library_name?: string;
        /**
         * Location to save the YAML Report file for a library.
         * The report_path attribute is used to define where to save the YAML Report file. This file is used to store information about what media is added, removed, filtered, and missing from the Plex library compared to what is expected from the Collection, Metadata, Overlay or Playlist file. If your Collection file creates a collection with Movie 1, Movie 2 and Movie 3 but your Plex library only has Movie 1 and Movie 3, then the missing YAML file will be updated to inform the user that Movie 2 was missing from the library.
         */
        report_path?: string;
        settings?: Settings;
        plex?: Plex;
        radarr?: Radarr;
        sonarr?: Sonarr;
        tautulli?: Tautulli;
        tracearr?: Tracearr;
        template_variables?: TemplateVariables2;
        /**
         * Used to schedule when a library is run using the schedule options.
         */
        schedule?: string;
        /**
         * Used to schedule when overlays are run for this library.
         */
        schedule_overlays?: string;
        /**
         * Used to remove overlays from this library only.
         * When set to true, this will remove all overlays from your library every run, but will not delete the overlaid images from your system, resulting in image bloat.
         */
        remove_overlays?: boolean;
        /**
         * Used to reapply overlays from this library only. This will reapply overlays to every item in your library.
         * When set to true, this will reapply all overlays on each run even if there is no need to do so, which will result in image bloat.
         */
        reapply_overlays?: boolean;
        /**
         * Used to reset overlays from this library only. This will reset overlays to every item in your library to your source choice. This will use the reset image when overlaying items in your library.
         * This will reset all posters to the desired source on each run and will reapply all overlays on each run, which will result in image bloat.
         */
        reset_overlays?: "tmdb" | "plex";
        run_order?: ("collections" | "metadata" | "operations" | "overlays")[];
      }
    | string;
}
export interface FilePath {
  file: string;
  schedule?: string;
  asset_directory?: string | string[];
}
export interface FolderPath {
  folder: string;
  schedule?: string;
  asset_directory?: string | string[];
}
export interface UrlPath {
  url: string;
  schedule?: string;
  asset_directory?: string | string[];
}
export interface GitPath {
  git: string;
  schedule?: string;
  asset_directory?: string | string[];
}
export interface RepoPath {
  repo: string;
  schedule?: string;
  asset_directory?: string | string[];
}
/**
 * @deprecated
 */
export interface LegacyDefaultCollectionPath {
  pmm:
    | "actor"
    | "anilist"
    | "aspect"
    | "audio_language"
    | "bafta"
    | "based"
    | "basic"
    | "berlinale"
    | "cannes"
    | "cesar"
    | "choice"
    | "collectionless"
    | "content_rating_au"
    | "content_rating_cs"
    | "content_rating_de"
    | "content_rating_nz"
    | "content_rating_mal"
    | "content_rating_uk"
    | "content_rating_us"
    | "continent"
    | "country"
    | "decade"
    | "director"
    | "emmy"
    | "flixpatrol"
    | "franchise"
    | "genre"
    | "golden"
    | "imdb"
    | "letterboxd"
    | "myanimelist"
    | "network"
    | "nfr"
    | "oscars"
    | "other_chart"
    | "pca"
    | "producer"
    | "razzie"
    | "region"
    | "resolution"
    | "sag"
    | "seasonal"
    | "separator_award"
    | "separator_chart"
    | "simkl"
    | "spirit"
    | "streaming"
    | "studio"
    | "subtitle_language"
    | "sundance"
    | "tautulli"
    | "tracearr"
    | "tiff"
    | "tmdb"
    | "trakt"
    | "universe"
    | "venice"
    | "writer"
    | "year";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables;
}
/**
 * Template variables shared across all collection defaults files. Per-key variants (use_<<key>>, name_<<key>>, etc.) are accepted via patternProperties.
 */
export interface TemplateVariables {
  /**
   * Data object used by dynamic collection defaults (e.g. year ranges).
   */
  data?: {
    starting?: number | string;
    ending?: number | string;
    increment?: number;
    depth?: number;
    limit?: number;
  };
  /**
   * Image style used by defaults that support multiple poster styles.
   */
  style?:
    | "color"
    | "white"
    | "bw"
    | "diiivoy"
    | "diiivoycolor"
    | "rainier"
    | "signature"
    | "orig"
    | "transparent"
    | "default"
    | "standards";
  /**
   * Controls the collection mode of all collections in this defaults file.
   */
  collection_mode?: "default" | "hide" | "hide_items" | "show_items";
  /**
   * Changes the sort order of this defaults file's section against other default sections. Use quotes to preserve leading zeros.
   */
  collection_section?: string | number;
  /**
   * Delete any Plex collections with these names before running.
   */
  delete_collections_named?: string | string[];
  /**
   * Sets the background filepath for all collections in this defaults file.
   */
  file_background?: string;
  /**
   * Sets the poster filepath for all collections in this defaults file.
   */
  file_poster?: string;
  /**
   * TMDb/TVDb IDs to ignore across all collections in this defaults file.
   */
  ignore_ids?: string | (number | string)[];
  /**
   * IMDb IDs to ignore across all collections in this defaults file.
   */
  ignore_imdb_ids?: string | string[];
  /**
   * Append a Radarr tag to every movie found by all collections in this defaults file.
   */
  item_radarr_tag?: string | string[];
  /**
   * Append a Sonarr tag to every series found by all collections in this defaults file.
   */
  item_sonarr_tag?: string | string[];
  /**
   * Language for collection names and summaries.
   */
  language?:
    "default" | "en" | "fr" | "ar" | "da" | "nl" | "de" | "it" | "pt-br" | "nb-no" | "es" | "sv" | "ru" | "bg" | "hu";
  /**
   * Minimum number of items required for any collection in this defaults file to be created.
   */
  minimum_items?: number;
  /**
   * Priority position for all collections in this defaults file's Recommendation Hub rows. Lower numbers appear first.
   */
  hub_priority?: number;
  /**
   * Changes the name_mapping for all collections. Use <<key_name>> as a placeholder.
   */
  name_mapping?: string;
  /**
   * Override Radarr add_missing for all collections in this defaults file.
   */
  radarr_add_missing?: boolean;
  /**
   * Override Radarr root_folder_path for all collections in this defaults file.
   */
  radarr_folder?: string;
  /**
   * Override Radarr monitor_existing for all collections in this defaults file.
   */
  radarr_monitor_existing?: boolean;
  /**
   * Override Radarr search for all collections in this defaults file.
   */
  radarr_search?: boolean;
  /**
   * Override Radarr tag for all collections in this defaults file.
   */
  radarr_tag?: string | string[];
  /**
   * Override Radarr upgrade_existing for all collections in this defaults file.
   */
  radarr_upgrade_existing?: boolean;
  /**
   * Set the schedule for all collections in this defaults file.
   */
  schedule?: string;
  /**
   * Override Sonarr add_missing for all collections in this defaults file.
   */
  sonarr_add_missing?: boolean;
  /**
   * Override Sonarr root_folder_path for all collections in this defaults file.
   */
  sonarr_folder?: string;
  /**
   * Override Sonarr monitor_existing for all collections in this defaults file.
   */
  sonarr_monitor_existing?: boolean;
  /**
   * Override Sonarr search for all collections in this defaults file.
   */
  sonarr_search?: boolean;
  /**
   * Override Sonarr tag for all collections in this defaults file.
   */
  sonarr_tag?: string | string[];
  /**
   * Override Sonarr upgrade_existing for all collections in this defaults file.
   */
  sonarr_upgrade_existing?: boolean;
  /**
   * Changes the prefix of the sort title. Default: '!'
   */
  sort_prefix?: string;
  /**
   * Changes the sort title for all collections.
   */
  sort_title?: string;
  /**
   * Sets the background URL for all collections in this defaults file.
   */
  url_background?: string;
  /**
   * Changes the poster URL for all collections in this defaults file.
   */
  url_poster?: string;
  /**
   * Set to false to disable all collections in this defaults file.
   */
  use_all?: boolean;
  /**
   * Controls Home Tab visibility for all collections. true/false or a schedule string.
   */
  visible_home?: boolean | string;
  /**
   * Controls Library Recommended Tab visibility for all collections. true/false or a schedule string.
   */
  visible_library?: boolean | string;
  /**
   * Controls Shared Users' Home Tab visibility for all collections. true/false or a schedule string.
   */
  visible_shared?: boolean | string;
  /**
   * Limit the number of items for all collections in this defaults file.
   */
  limit?: number;
  /**
   * Changes the Collection Order for all collections in a Defaults File.
   */
  collection_order?: string;
  /**
   * Changes the Sync Mode for all collections in a Defaults File.
   */
  sync_mode?: "sync" | "append";
  /**
   * Add a placeholder Movie/Show to the Separator.
   */
  placeholder_imdb_id?: string;
  /**
   * Choose the Separator Style.
   */
  sep_style?:
    | "amethyst"
    | "aqua"
    | "blue"
    | "forest"
    | "fuchsia"
    | "gold"
    | "gray"
    | "green"
    | "navy"
    | "ocean"
    | "olive"
    | "orchid"
    | "orig"
    | "pink"
    | "plum"
    | "purple"
    | "red"
    | "rust"
    | "salmon"
    | "sand"
    | "stb"
    | "tan";
  /**
   * Turn the Separator Collection off.
   */
  use_separator?: boolean;
  /**
   * Changes the name of the Separator collection.
   */
  name_separator?: string;
  /**
   * Changes the summary of the Separator collection.
   */
  summary_separator?: string;
  /**
   * Changes the poster URL of the Separator collection.
   */
  url_poster_separator?: string;
  /**
   * Changes the Smart Filter Sort for all collections in a Defaults File.
   */
  sort_by?: string;
  /**
   * Add a placeholder Movie to the Separator. Movie libraries only.
   */
  placeholder_tmdb_movie?: number | string;
  /**
   * Add a placeholder Show to the Separator. Show libraries only.
   */
  placeholder_tvdb_show?: number | string;
  /**
   * Changes the title format of the Dynamic Collections.
   */
  name_format?: string;
  /**
   * Changes the summary format of the Dynamic Collections.
   */
  summary_format?: string;
  /**
   * Exclude specific keys from creating a Dynamic Collection.
   */
  exclude?: string | (string | number)[];
  /**
   * Overrides the default addons dictionary.
   */
  addons?: {
    [k: string]: string | string[];
  };
  /**
   * Appends to the default addons dictionary.
   */
  append_addons?: {
    [k: string]: string | string[];
  };
  /**
   * Removes from the default addons dictionary.
   */
  remove_addons?: string | string[];
  /**
   * Limits which library types this default applies to.
   */
  allowed_libraries?: string | string[];
  /**
   * Filter to only show winning entries.
   */
  winning?: boolean;
  /**
   * Turn the individual year collections off.
   */
  use_year_collections?: boolean;
  /**
   * Change the collection section for year collections only.
   */
  year_collection_section?: number | string;
  /**
   * Changes Streaming Service lists to only show original content.
   */
  originals_only?: boolean;
  /**
   * Changes some Streaming Service lists to regional variants.
   */
  region?: string;
  /**
   * Disable a specific collection by key. Set to false to turn off.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^use_(?!all$).+$".
   *
   * Override the name of a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^name_.+$".
   *
   * Override the summary of a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^summary_.+$".
   *
   * Override the sort order of a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^order_.+$".
   *
   * Set the schedule for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^schedule_.+$".
   *
   * Override minimum_items for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^minimum_items_.+$".
   *
   * Override hub_priority for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^hub_priority_.+$".
   *
   * Override the poster URL for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^url_poster_.+$".
   *
   * Override the poster filepath for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^file_poster_.+$".
   *
   * Override the background URL for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^url_background_.+$".
   *
   * Override the background filepath for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^file_background_.+$".
   *
   * Override Home Tab visibility for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^visible_home_.+$".
   *
   * Override Library Tab visibility for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^visible_library_.+$".
   *
   * Override Shared Home visibility for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^visible_shared_.+$".
   *
   * Override Radarr add_missing for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^radarr_add_missing_.+$".
   *
   * Override Radarr root_folder_path for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^radarr_folder_.+$".
   *
   * Override Radarr monitor_existing for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^radarr_monitor_existing_.+$".
   *
   * Override Radarr search for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^radarr_search_.+$".
   *
   * Override Radarr tag for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^radarr_tag_.+$".
   *
   * Override Radarr upgrade_existing for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^radarr_upgrade_existing_.+$".
   *
   * Override Sonarr add_missing for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sonarr_add_missing_.+$".
   *
   * Override Sonarr root_folder_path for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sonarr_folder_.+$".
   *
   * Override Sonarr monitor_existing for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sonarr_monitor_existing_.+$".
   *
   * Override Sonarr search for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sonarr_search_.+$".
   *
   * Override Sonarr tag for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sonarr_tag_.+$".
   *
   * Override Sonarr upgrade_existing for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sonarr_upgrade_existing_.+$".
   *
   * Override item_radarr_tag for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^item_radarr_tag_.+$".
   *
   * Override item_sonarr_tag for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^item_sonarr_tag_.+$".
   *
   * Override limit for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^limit_.+$".
   *
   * Override the mdblist_list URL for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^mdblist_list_.+$".
   *
   * Override the trakt_list URL for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^trakt_list_.+$".
   *
   * Override the imdb_list for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^imdb_list_.+$".
   *
   * Override the letterboxd_list URL for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^letterboxd_list_.+$".
   *
   * Override the Collection Order for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^collection_order_.+$".
   *
   * Override the Sync Mode for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sync_mode_.+$".
   *
   * Override how far back the filter looks for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^in_the_last_.+$".
   *
   * Override the Smart Filter Sort for a specific collection by key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^sort_by_.+$".
   *
   * Overrides the TMDb Watch Provider used for the specified key.
   *
   * This interface was referenced by `TemplateVariables`'s JSON-Schema definition
   * via the `patternProperty` "^discover_with_.+$".
   */
  [k: string]:
    | boolean
    | string
    | number
    | string[]
    | "sync"
    | "append"
    | {
        starting?: number | string;
        ending?: number | string;
        increment?: number;
        depth?: number;
        limit?: number;
      }
    | "color"
    | "white"
    | "bw"
    | "diiivoy"
    | "diiivoycolor"
    | "rainier"
    | "signature"
    | "orig"
    | "transparent"
    | "default"
    | "standards"
    | "hide"
    | "hide_items"
    | "show_items"
    | (number | string)[]
    | "en"
    | "fr"
    | "ar"
    | "da"
    | "nl"
    | "de"
    | "it"
    | "pt-br"
    | "nb-no"
    | "es"
    | "sv"
    | "ru"
    | "bg"
    | "hu"
    | "amethyst"
    | "aqua"
    | "blue"
    | "forest"
    | "fuchsia"
    | "gold"
    | "gray"
    | "green"
    | "navy"
    | "ocean"
    | "olive"
    | "orchid"
    | "pink"
    | "plum"
    | "purple"
    | "red"
    | "rust"
    | "salmon"
    | "sand"
    | "stb"
    | "tan"
    | (string | number)[]
    | {
        [k: string]: string | string[];
      }
    | undefined;
}
export interface FilePathCollectionWithTemplateVariables {
  file: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables;
}
export interface UrlPathCollectionWithTemplateVariables {
  url: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables;
}
export interface GitPathCollectionWithTemplateVariables {
  git: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables;
}
export interface RepoPathCollectionWithTemplateVariables {
  repo: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables;
}
/**
 * @deprecated
 */
export interface LegacyDefaultOverlayPath {
  pmm:
    | "aspect"
    | "audio_codec"
    | "commonsense"
    | "content_rating_au"
    | "content_rating_de"
    | "content_rating_nz"
    | "content_rating_uk"
    | "content_rating_us_movie"
    | "content_rating_us_show"
    | "direct_play"
    | "episode_info"
    | "language_count"
    | "flixpatrol"
    | "languages"
    | "mediastinger"
    | "network"
    | "ratings"
    | "resolution"
    | "ribbon"
    | "runtimes"
    | "status"
    | "streaming"
    | "studio"
    | "versions"
    | "video_format";
  remove_overlays?: boolean;
  reapply_overlays?: boolean;
  reapply_overlay?: boolean;
  reset_overlays?: "tmdb" | "plex";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
export interface TemplateVariables1 {
  addon_offset?: number;
  addon_position?: "left" | "top" | "bottom" | "right";
  back_align?: "left" | "right" | "center" | "top" | "bottom";
  back_color?: string;
  back_height?: number;
  back_line_color?: string;
  back_line_width?: number;
  back_padding?: number;
  back_radius?: number;
  back_width?: number;
  builder_level?: "show" | "season" | "episode";
  /**
   * Toggles color styling for applicable overlays like content ratings.
   */
  color?: boolean;
  file?: string;
  final_name?: string;
  flag_alignment?: "left" | "right";
  font_color?: string;
  font_size?: number;
  font_style?: "Any" | "Italic" | "Normal" | "Oblique";
  font?: string;
  format?: string;
  git?: string;
  group_alignment?: "horizontal" | "vertical";
  hide_text?: boolean;
  horizontal_align?: "left" | "center" | "right";
  horizontal_offset?: string | number;
  horizontal_position?: "left" | "left2" | "center" | "center_left" | "center_right" | "right" | "right2";
  horizontal_spacing?: number;
  initial_horizontal_align?: "left" | "center" | "right";
  initial_horizontal_offset?: number;
  initial_vertical_align?: "top" | "center" | "bottom";
  initial_vertical_offset?: number;
  languages?: string[];
  last?: number;
  limit?: number;
  location?:
    | "world"
    | "albania"
    | "argentina"
    | "armenia"
    | "australia"
    | "austria"
    | "azerbaijan"
    | "bahamas"
    | "bahrain"
    | "bangladesh"
    | "belarus"
    | "belgium"
    | "belize"
    | "benin"
    | "bolivia"
    | "bosnia_and_herzegovina"
    | "botswana"
    | "brazil"
    | "bulgaria"
    | "burkina_faso"
    | "cambodia"
    | "canada"
    | "chile"
    | "colombia"
    | "costa_rica"
    | "croatia"
    | "cyprus"
    | "czech_republic"
    | "denmark"
    | "dominican_republic"
    | "ecuador"
    | "egypt"
    | "estonia"
    | "finland"
    | "france"
    | "gabon"
    | "germany"
    | "ghana"
    | "greece"
    | "guatemala"
    | "guinea_bissau"
    | "haiti"
    | "honduras"
    | "hong_kong"
    | "hungary"
    | "iceland"
    | "india"
    | "indonesia"
    | "ireland"
    | "israel"
    | "italy"
    | "ivory_coast"
    | "jamaica"
    | "japan"
    | "jordan"
    | "kazakhstan"
    | "kenya"
    | "kuwait"
    | "kyrgyzstan"
    | "laos"
    | "latvia"
    | "lebanon"
    | "lithuania"
    | "luxembourg"
    | "malaysia"
    | "maldives"
    | "mali"
    | "malta"
    | "mexico"
    | "moldova"
    | "mongolia"
    | "montenegro"
    | "morocco"
    | "mozambique"
    | "namibia"
    | "netherlands"
    | "new_zealand"
    | "nicaragua"
    | "niger"
    | "nigeria"
    | "north_macedonia"
    | "norway"
    | "oman"
    | "pakistan"
    | "panama"
    | "papua_new_guinea"
    | "paraguay"
    | "peru"
    | "philippines"
    | "poland"
    | "portugal"
    | "qatar"
    | "romania"
    | "russia"
    | "rwanda"
    | "salvador"
    | "saudi_arabia"
    | "senegal"
    | "serbia"
    | "singapore"
    | "slovakia"
    | "slovenia"
    | "south_africa"
    | "south_korea"
    | "spain"
    | "sri_lanka"
    | "sweden"
    | "switzerland"
    | "taiwan"
    | "tajikistan"
    | "tanzania"
    | "thailand"
    | "togo"
    | "trinidad_and_tobago"
    | "turkey"
    | "turkmenistan"
    | "uganda"
    | "ukraine"
    | "united_arab_emirates"
    | "united_kingdom"
    | "united_states"
    | "uruguay"
    | "uzbekistan"
    | "venezuela"
    | "vietnam"
    | "zambia"
    | "zimbabwe";
  minimum?: number;
  offset?: number;
  /**
   * Changes Streaming Service overlays to only apply to original content produced by the service.
   * Note: Cannot be used with region, and only produces overlays for amazon, appletv, disney, max, hulu, netflix, paramount, peacock
   */
  originals_only?: boolean;
  /**
   * Choose the number of overlay this queue displays.
   * Default: 3
   * Values: 1, 2, 3, 4, or 5
   */
  overlay_limit?: number;
  position?: "left" | "right";
  /**
   * Choose the text after the 'nr' key for the Overlay.
   * Values: Any String
   */
  post_nr_text?: string;
  /**
   * Choose the text after the key for the Overlay.
   * Default: +
   * Values: Any String
   */
  post_text?: string;
  /**
   * Choose the text before the 'nr' key for the Overlay.
   * Values: Any String
   */
  pre_nr_text?: string;
  /**
   * Choose the text before the key for the Overlay.
   * Values: Any String
   */
  pre_text?: string;
  rating_alignment?: "vertical" | "horizontal";
  rating1?: "critic" | "audience" | "user" | "floppy";
  rating1_image?:
    | "anidb"
    | "imdb"
    | "letterboxd"
    | "tmdb"
    | "metacritic"
    | "rt_popcorn"
    | "rt_tomato"
    | "trakt"
    | "mal"
    | "mdb"
    | "star";
  rating1_font?: string;
  rating1_font_size?: number;
  rating1_font_color?: string;
  rating1_stroke_width?: number;
  rating1_stroke_color?: string;
  rating1_horizontal_offset?: string | number;
  rating1_vertical_offset?: string | number;
  rating2?: "critic" | "audience" | "user" | "floppy";
  rating2_image?:
    | "anidb"
    | "imdb"
    | "letterboxd"
    | "tmdb"
    | "metacritic"
    | "rt_popcorn"
    | "rt_tomato"
    | "trakt"
    | "mal"
    | "mdb"
    | "star";
  rating2_font?: string;
  rating2_font_size?: number;
  rating2_font_color?: string;
  rating2_stroke_width?: number;
  rating2_stroke_color?: string;
  rating2_horizontal_offset?: string | number;
  rating2_vertical_offset?: string | number;
  rating3?: "critic" | "audience" | "user" | "floppy";
  rating3_image?:
    | "anidb"
    | "imdb"
    | "letterboxd"
    | "tmdb"
    | "metacritic"
    | "rt_popcorn"
    | "rt_tomato"
    | "trakt"
    | "mal"
    | "mdb"
    | "star";
  rating3_font?: string;
  rating3_font_size?: number;
  rating3_font_color?: string;
  rating3_stroke_width?: number;
  rating3_stroke_color?: string;
  rating3_horizontal_offset?: string | number;
  rating3_vertical_offset?: string | number;
  region?: "us" | "uk" | "ca" | "da" | "de" | "es" | "fr" | "it" | "pt-br";
  remove_overlays?: boolean;
  reapply_overlays?: boolean;
  reset_overlays?: "tmdb" | "plex";
  repo?: string;
  scale_height?: string | number;
  scale_width?: string | number;
  size?: "small" | "big";
  stroke_color?: string;
  stroke_width?: number;
  style?:
    | "compact"
    | "standard"
    | "bigger"
    | "round"
    | "square"
    | "half"
    | "red"
    | "black"
    | "yellow"
    | "gray"
    | "color"
    | "white";
  text?: string;
  time_window?:
    "today" | "yesterday" | "this_week" | "last_week" | "this_month" | "last_month" | "this_year" | "last_year";
  url?: string;
  use_edition?: boolean;
  use_lowercase?: boolean;
  use_resolution?: boolean;
  use_subtitles?: boolean;
  vertical_align?: "top" | "center" | "bottom";
  vertical_offset?: string | number;
  vertical_position?:
    "top" | "top2" | "top3" | "center" | "center_top" | "center_bottom" | "bottom" | "bottom2" | "bottom3";
  vertical_spacing?: number;
  fresh_rating?: number;
  maximum_rating?: number;
  minimum_rating?: number;
  rating1_addon_offset?: number;
  rating1_addon_position?: string;
  rating1_extra?: string;
  rating1_style?: string;
  rating2_addon_offset?: number;
  rating2_addon_position?: string;
  rating2_extra?: string;
  rating2_style?: string;
  rating3_addon_offset?: number;
  rating3_addon_position?: string;
  rating3_extra?: string;
  rating3_style?: string;
  [k: string]: unknown;
}
export interface KometaDefaultOverlayPath {
  default?:
    | "aspect"
    | "audio_codec"
    | "commonsense"
    | "content_rating_au"
    | "content_rating_de"
    | "content_rating_nz"
    | "content_rating_uk"
    | "content_rating_us_movie"
    | "content_rating_us_show"
    | "direct_play"
    | "episode_info"
    | "language_count"
    | "flixpatrol"
    | "languages"
    | "mediastinger"
    | "network"
    | "ratings"
    | "resolution"
    | "ribbon"
    | "runtimes"
    | "status"
    | "streaming"
    | "studio"
    | "versions"
    | "video_format";
  remove_overlays?: boolean;
  reapply_overlays?: boolean;
  reapply_overlay?: boolean;
  reset_overlays?: "tmdb" | "plex";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
export interface FilePathOverlayWithTemplateVariables {
  file: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
export interface UrlPathOverlayWithTemplateVariables {
  url: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
export interface GitPathOverlayWithTemplateVariables {
  git: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
export interface RepoPathOverlayWithTemplateVariables {
  repo: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
/**
 * @deprecated
 */
export interface LegacyDefaultCollectionPath1 {
  pmm:
    | "actor"
    | "anilist"
    | "aspect"
    | "audio_language"
    | "bafta"
    | "based"
    | "basic"
    | "berlinale"
    | "cannes"
    | "cesar"
    | "choice"
    | "collectionless"
    | "content_rating_au"
    | "content_rating_cs"
    | "content_rating_de"
    | "content_rating_nz"
    | "content_rating_mal"
    | "content_rating_uk"
    | "content_rating_us"
    | "continent"
    | "country"
    | "decade"
    | "director"
    | "emmy"
    | "flixpatrol"
    | "franchise"
    | "genre"
    | "golden"
    | "imdb"
    | "letterboxd"
    | "myanimelist"
    | "network"
    | "nfr"
    | "oscars"
    | "other_chart"
    | "pca"
    | "producer"
    | "razzie"
    | "region"
    | "resolution"
    | "sag"
    | "seasonal"
    | "separator_award"
    | "separator_chart"
    | "simkl"
    | "spirit"
    | "streaming"
    | "studio"
    | "subtitle_language"
    | "sundance"
    | "tautulli"
    | "tracearr"
    | "tiff"
    | "tmdb"
    | "trakt"
    | "universe"
    | "venice"
    | "writer"
    | "year";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables;
}
/**
 * @deprecated
 */
export interface LegacyDefaultOverlayPath1 {
  pmm:
    | "aspect"
    | "audio_codec"
    | "commonsense"
    | "content_rating_au"
    | "content_rating_de"
    | "content_rating_nz"
    | "content_rating_uk"
    | "content_rating_us_movie"
    | "content_rating_us_show"
    | "direct_play"
    | "episode_info"
    | "language_count"
    | "flixpatrol"
    | "languages"
    | "mediastinger"
    | "network"
    | "ratings"
    | "resolution"
    | "ribbon"
    | "runtimes"
    | "status"
    | "streaming"
    | "studio"
    | "versions"
    | "video_format";
  remove_overlays?: boolean;
  reapply_overlays?: boolean;
  reapply_overlay?: boolean;
  reset_overlays?: "tmdb" | "plex";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables1;
}
export interface Operations {
  assets_for_all?: boolean;
  assets_for_all_collections?: boolean;
  /**
   * Skip item operations for items with any of these labels.
   */
  ignore_labels?: string | [string, ...string[]];
  /**
   * When true, this library operations run skips items listed in ignore_ids or ignore_imdb_ids.
   */
  respect_ignore_ids?: boolean;
  update_blank_track_titles?: boolean;
  remove_title_parentheses?: boolean;
  split_duplicates?: boolean;
  /**
   * Add episodes watched by the Plex server owner to the authenticated Serializd account. Serializd does not support importing Plex watch dates.
   */
  sync_watchlist_to_serializd?: boolean;
  radarr_add_all?: boolean;
  sonarr_add_all?: boolean;
  mass_metadata_update?: {
    genre?:
      | MassMetadataSource
      | {
          schedule?: string;
          source?: MassMetadataSource;
          mappings?: MetadataMapping;
        };
    content_rating?:
      | MassMetadataSource
      | {
          schedule?: string;
          source?: MassMetadataSource;
          mappings?: MetadataMapping;
        };
    collections?: MassMetadataScheduledCollectionMode;
    labels?: MassMetadataScheduledLabels;
    original_title?: MassMetadataScheduledSource;
    studio?: MassMetadataScheduledSource;
    originally_available?: MassMetadataScheduledSource;
    added_at?: MassMetadataScheduledSource;
    ratings?: {
      schedule?: string;
      user?: MassMetadataScheduledSource;
      critic?: MassMetadataScheduledSource;
      audience?: MassMetadataScheduledSource;
      episode_user?: MassMetadataScheduledSource;
      episode_critic?: MassMetadataScheduledSource;
      episode_audience?: MassMetadataScheduledSource;
    };
    poster?: MassMetadataImage;
    background?: MassMetadataImage;
    logo?: MassMetadataImage;
    square_art?: MassMetadataImage;
    backup?: {
      schedule?: string;
      path?: string;
      exclude?: string | string[];
      sync_tags?: boolean;
      add_blank_entries?: boolean;
    };
  };
  mass_genre_update?:
    | (
        | "tmdb"
        | "tvdb"
        | "serializd"
        | "serializd_nanogenres"
        | "serializd_all"
        | "imdb"
        | "omdb"
        | "anidb"
        | "anidb_3_0"
        | "anidb_2_5"
        | "anidb_2_0"
        | "anidb_1_5"
        | "anidb_1_0"
        | "anidb_0_5"
        | "mal"
        | "lock"
        | "unlock"
        | "remove"
        | "reset"
      )
    | (
        | (
            | "tmdb"
            | "tvdb"
            | "serializd"
            | "serializd_nanogenres"
            | "serializd_all"
            | "imdb"
            | "omdb"
            | "anidb"
            | "anidb_3_0"
            | "anidb_2_5"
            | "anidb_2_0"
            | "anidb_1_5"
            | "anidb_1_0"
            | "anidb_0_5"
            | "mal"
            | "lock"
            | "unlock"
            | "remove"
            | "reset"
          )
        | string[]
      )[];
  mass_content_rating_update?: ((
    | (
        | "mdb"
        | "mdb_commonsense"
        | "mdb_commonsense0"
        | "plex_csm"
        | "plex_csm0"
        | "omdb"
        | "mal"
        | "lock"
        | "unlock"
        | "remove"
        | "reset"
      )
    | {
        [k: string]: unknown;
      }
  ) &
    string)[];
  mass_original_title_update?: ((
    | ("anidb" | "anidb_official" | "mal" | "mal_english" | "mal_japanese" | "lock" | "unlock" | "remove" | "reset")
    | {
        [k: string]: unknown;
      }
  ) &
    string)[];
  mass_studio_update?:
    | ("anidb" | "mal" | "tmdb" | "lock" | "unlock" | "remove" | "reset")
    | (("anidb" | "mal" | "tmdb" | "lock" | "unlock" | "remove" | "reset") | string)[];
  mass_originally_available_update?:
    | (
        | "tmdb"
        | "tmdb_premiere"
        | "tmdb_theatrical"
        | "tmdb_theatricallimited"
        | "tmdb_digital"
        | "tmdb_physical"
        | "tmdb_tv"
        | "tvdb"
        | "omdb"
        | "mdb"
        | "mdb_digital"
        | "anidb"
        | "mal"
        | "lock"
        | "unlock"
        | "remove"
        | "reset"
      )
    | string
    | (
        | (
            | "tmdb"
            | "tmdb_premiere"
            | "tmdb_theatrical"
            | "tmdb_theatricallimited"
            | "tmdb_digital"
            | "tmdb_physical"
            | "tmdb_tv"
            | "tvdb"
            | "omdb"
            | "mdb"
            | "mdb_digital"
            | "anidb"
            | "mal"
            | "lock"
            | "unlock"
            | "remove"
            | "reset"
          )
        | string
      )[];
  mass_added_at_update?:
    | (
        | "tmdb"
        | "tmdb_premiere"
        | "tmdb_theatrical"
        | "tmdb_theatricallimited"
        | "tmdb_digital"
        | "tmdb_physical"
        | "tmdb_tv"
        | "tvdb"
        | "omdb"
        | "mdb"
        | "mdb_digital"
        | "anidb"
        | "mal"
        | "lock"
        | "unlock"
        | "remove"
        | "reset"
      )
    | string
    | (
        | (
            | "tmdb"
            | "tmdb_premiere"
            | "tmdb_theatrical"
            | "tmdb_theatricallimited"
            | "tmdb_digital"
            | "tmdb_physical"
            | "tmdb_tv"
            | "tvdb"
            | "omdb"
            | "mdb"
            | "mdb_digital"
            | "anidb"
            | "mal"
            | "lock"
            | "unlock"
            | "remove"
            | "reset"
          )
        | string
      )[];
  mass_audience_rating_update?:
    | number
    | (
        | "anidb_average"
        | "anidb_rating"
        | "anidb_score"
        | "imdb"
        | "lock"
        | "mal"
        | "mdb"
        | "mdb_average"
        | "mdb_imdb"
        | "mdb_letterboxd"
        | "mdb_metacritic"
        | "mdb_metacriticuser"
        | "mdb_myanimelist"
        | "mdb_tomatoes"
        | "mdb_tomatoesaudience"
        | "mdb_tmdb"
        | "mdb_trakt"
        | "omdb"
        | "omdb_metascore"
        | "omdb_tomatoes"
        | "plex_imdb"
        | "plex_tmdb"
        | "plex_tomatoes"
        | "plex_tomatoesaudience"
        | "remove"
        | "reset"
        | "tmdb"
        | "trakt"
        | "trakt_user"
        | "serializd"
        | "floppy"
        | "unlock"
      )
    | (
        | (
            | "anidb_average"
            | "anidb_rating"
            | "anidb_score"
            | "imdb"
            | "lock"
            | "mal"
            | "mdb"
            | "mdb_average"
            | "mdb_imdb"
            | "mdb_letterboxd"
            | "mdb_metacritic"
            | "mdb_metacriticuser"
            | "mdb_myanimelist"
            | "mdb_tomatoes"
            | "mdb_tomatoesaudience"
            | "mdb_tmdb"
            | "mdb_trakt"
            | "omdb"
            | "omdb_metascore"
            | "omdb_tomatoes"
            | "plex_imdb"
            | "plex_tmdb"
            | "plex_tomatoes"
            | "plex_tomatoesaudience"
            | "remove"
            | "reset"
            | "tmdb"
            | "trakt"
            | "trakt_user"
            | "serializd"
            | "floppy"
            | "unlock"
          )
        | number
      )[];
  mass_critic_rating_update?:
    | number
    | (
        | "anidb_average"
        | "anidb_rating"
        | "anidb_score"
        | "imdb"
        | "lock"
        | "mal"
        | "mdb"
        | "mdb_average"
        | "mdb_imdb"
        | "mdb_letterboxd"
        | "mdb_metacritic"
        | "mdb_metacriticuser"
        | "mdb_myanimelist"
        | "mdb_tomatoes"
        | "mdb_tomatoesaudience"
        | "mdb_tmdb"
        | "mdb_trakt"
        | "omdb"
        | "omdb_metascore"
        | "omdb_tomatoes"
        | "plex_imdb"
        | "plex_tmdb"
        | "plex_tomatoes"
        | "plex_tomatoesaudience"
        | "remove"
        | "reset"
        | "tmdb"
        | "trakt"
        | "trakt_user"
        | "serializd"
        | "floppy"
        | "unlock"
      )
    | (
        | (
            | "anidb_average"
            | "anidb_rating"
            | "anidb_score"
            | "imdb"
            | "lock"
            | "mal"
            | "mdb"
            | "mdb_average"
            | "mdb_imdb"
            | "mdb_letterboxd"
            | "mdb_metacritic"
            | "mdb_metacriticuser"
            | "mdb_myanimelist"
            | "mdb_tomatoes"
            | "mdb_tomatoesaudience"
            | "mdb_tmdb"
            | "mdb_trakt"
            | "omdb"
            | "omdb_metascore"
            | "omdb_tomatoes"
            | "plex_imdb"
            | "plex_tmdb"
            | "plex_tomatoes"
            | "plex_tomatoesaudience"
            | "remove"
            | "reset"
            | "tmdb"
            | "trakt"
            | "trakt_user"
            | "serializd"
            | "floppy"
            | "unlock"
          )
        | number
      )[];
  mass_user_rating_update?:
    | number
    | (
        | "anidb_average"
        | "anidb_rating"
        | "anidb_score"
        | "imdb"
        | "lock"
        | "mal"
        | "mdb"
        | "mdb_average"
        | "mdb_imdb"
        | "mdb_letterboxd"
        | "mdb_metacritic"
        | "mdb_metacriticuser"
        | "mdb_myanimelist"
        | "mdb_tomatoes"
        | "mdb_tomatoesaudience"
        | "mdb_tmdb"
        | "mdb_trakt"
        | "omdb"
        | "omdb_metascore"
        | "omdb_tomatoes"
        | "plex_imdb"
        | "plex_tmdb"
        | "plex_tomatoes"
        | "plex_tomatoesaudience"
        | "remove"
        | "reset"
        | "tmdb"
        | "trakt"
        | "trakt_user"
        | "serializd"
        | "floppy"
        | "unlock"
      )
    | (
        | (
            | "anidb_average"
            | "anidb_rating"
            | "anidb_score"
            | "imdb"
            | "lock"
            | "mal"
            | "mdb"
            | "mdb_average"
            | "mdb_imdb"
            | "mdb_letterboxd"
            | "mdb_metacritic"
            | "mdb_metacriticuser"
            | "mdb_myanimelist"
            | "mdb_tomatoes"
            | "mdb_tomatoesaudience"
            | "mdb_tmdb"
            | "mdb_trakt"
            | "omdb"
            | "omdb_metascore"
            | "omdb_tomatoes"
            | "plex_imdb"
            | "plex_tmdb"
            | "plex_tomatoes"
            | "plex_tomatoesaudience"
            | "remove"
            | "reset"
            | "tmdb"
            | "trakt"
            | "trakt_user"
            | "serializd"
            | "floppy"
            | "unlock"
          )
        | number
      )[];
  mass_episode_audience_rating_update?:
    | number
    | (
        | "anidb_average"
        | "anidb_rating"
        | "anidb_score"
        | "imdb"
        | "lock"
        | "mal"
        | "mdb"
        | "mdb_average"
        | "mdb_imdb"
        | "mdb_letterboxd"
        | "mdb_metacritic"
        | "mdb_metacriticuser"
        | "mdb_myanimelist"
        | "mdb_tomatoes"
        | "mdb_tomatoesaudience"
        | "mdb_tmdb"
        | "mdb_trakt"
        | "omdb"
        | "omdb_metascore"
        | "omdb_tomatoes"
        | "plex_imdb"
        | "plex_tmdb"
        | "plex_tomatoes"
        | "plex_tomatoesaudience"
        | "remove"
        | "reset"
        | "tmdb"
        | "trakt"
        | "trakt_user"
        | "serializd"
        | "serializd_user"
        | "floppy"
        | "unlock"
      )
    | (
        | (
            | "anidb_average"
            | "anidb_rating"
            | "anidb_score"
            | "imdb"
            | "lock"
            | "mal"
            | "mdb"
            | "mdb_average"
            | "mdb_imdb"
            | "mdb_letterboxd"
            | "mdb_metacritic"
            | "mdb_metacriticuser"
            | "mdb_myanimelist"
            | "mdb_tomatoes"
            | "mdb_tomatoesaudience"
            | "mdb_tmdb"
            | "mdb_trakt"
            | "omdb"
            | "omdb_metascore"
            | "omdb_tomatoes"
            | "plex_imdb"
            | "plex_tmdb"
            | "plex_tomatoes"
            | "plex_tomatoesaudience"
            | "remove"
            | "reset"
            | "tmdb"
            | "trakt"
            | "trakt_user"
            | "serializd"
            | "serializd_user"
            | "floppy"
            | "unlock"
          )
        | number
      )[];
  mass_episode_critic_rating_update?:
    | number
    | (
        | "anidb_average"
        | "anidb_rating"
        | "anidb_score"
        | "imdb"
        | "lock"
        | "mal"
        | "mdb"
        | "mdb_average"
        | "mdb_imdb"
        | "mdb_letterboxd"
        | "mdb_metacritic"
        | "mdb_metacriticuser"
        | "mdb_myanimelist"
        | "mdb_tomatoes"
        | "mdb_tomatoesaudience"
        | "mdb_tmdb"
        | "mdb_trakt"
        | "omdb"
        | "omdb_metascore"
        | "omdb_tomatoes"
        | "plex_imdb"
        | "plex_tmdb"
        | "plex_tomatoes"
        | "plex_tomatoesaudience"
        | "remove"
        | "reset"
        | "tmdb"
        | "trakt"
        | "trakt_user"
        | "serializd"
        | "serializd_user"
        | "floppy"
        | "unlock"
      )
    | (
        | (
            | "anidb_average"
            | "anidb_rating"
            | "anidb_score"
            | "imdb"
            | "lock"
            | "mal"
            | "mdb"
            | "mdb_average"
            | "mdb_imdb"
            | "mdb_letterboxd"
            | "mdb_metacritic"
            | "mdb_metacriticuser"
            | "mdb_myanimelist"
            | "mdb_tomatoes"
            | "mdb_tomatoesaudience"
            | "mdb_tmdb"
            | "mdb_trakt"
            | "omdb"
            | "omdb_metascore"
            | "omdb_tomatoes"
            | "plex_imdb"
            | "plex_tmdb"
            | "plex_tomatoes"
            | "plex_tomatoesaudience"
            | "remove"
            | "reset"
            | "tmdb"
            | "trakt"
            | "trakt_user"
            | "serializd"
            | "serializd_user"
            | "floppy"
            | "unlock"
          )
        | number
      )[];
  mass_episode_user_rating_update?:
    | number
    | (
        | "anidb_average"
        | "anidb_rating"
        | "anidb_score"
        | "imdb"
        | "lock"
        | "mal"
        | "mdb"
        | "mdb_average"
        | "mdb_imdb"
        | "mdb_letterboxd"
        | "mdb_metacritic"
        | "mdb_metacriticuser"
        | "mdb_myanimelist"
        | "mdb_tomatoes"
        | "mdb_tomatoesaudience"
        | "mdb_tmdb"
        | "mdb_trakt"
        | "omdb"
        | "omdb_metascore"
        | "omdb_tomatoes"
        | "plex_imdb"
        | "plex_tmdb"
        | "plex_tomatoes"
        | "plex_tomatoesaudience"
        | "remove"
        | "reset"
        | "tmdb"
        | "trakt"
        | "trakt_user"
        | "serializd"
        | "serializd_user"
        | "floppy"
        | "unlock"
      )
    | (
        | (
            | "anidb_average"
            | "anidb_rating"
            | "anidb_score"
            | "imdb"
            | "lock"
            | "mal"
            | "mdb"
            | "mdb_average"
            | "mdb_imdb"
            | "mdb_letterboxd"
            | "mdb_metacritic"
            | "mdb_metacriticuser"
            | "mdb_myanimelist"
            | "mdb_tomatoes"
            | "mdb_tomatoesaudience"
            | "mdb_tmdb"
            | "mdb_trakt"
            | "omdb"
            | "omdb_metascore"
            | "omdb_tomatoes"
            | "plex_imdb"
            | "plex_tmdb"
            | "plex_tomatoes"
            | "plex_tomatoesaudience"
            | "remove"
            | "reset"
            | "tmdb"
            | "trakt"
            | "trakt_user"
            | "serializd"
            | "serializd_user"
            | "floppy"
            | "unlock"
          )
        | number
      )[];
  mass_poster_update?: {
    source?:
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")[];
    language?: string;
    seasons?: boolean;
    episodes?: boolean;
    ignore_locked?: boolean;
    ignore_overlays?: boolean;
  };
  mass_background_update?: {
    source?:
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")[];
    language?: string;
    seasons?: boolean;
    episodes?: boolean;
    ignore_locked?: boolean;
    ignore_overlays?: boolean;
  };
  mass_image_update?: {
    poster?:
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
      | {
          source?:
            | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
            | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")[];
          language?: string;
          seasons?: boolean;
          episodes?: boolean;
          ignore_locked?: boolean;
          ignore_overlays?: boolean;
        };
    background?:
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
      | {
          source?:
            | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
            | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")[];
          language?: string;
          seasons?: boolean;
          episodes?: boolean;
          ignore_locked?: boolean;
          ignore_overlays?: boolean;
        };
    logo?:
      | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
      | {
          source?:
            | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")
            | ("tmdb" | "trakt" | "tvdb" | "plex" | "lock" | "unlock")[];
          language?: string;
          ignore_locked?: boolean;
        };
    square_art?:
      | ("tvdb" | "plex" | "lock" | "unlock")
      | {
          source?: ("tvdb" | "plex" | "lock" | "unlock") | ("tvdb" | "plex" | "lock" | "unlock")[];
          ignore_locked?: boolean;
        };
  };
  mass_imdb_parental_labels?: "none" | "mild" | "moderate" | "severe";
  mass_collection_mode?: "default" | "hide" | "hide_items" | "show_items";
  radarr_remove_by_tag?: string[];
  sonarr_remove_by_tag?: string[];
  delete_collections?: {
    configured?: boolean;
    managed?: boolean;
    less?: number;
    ignore_empty_smart_collections?: boolean;
    [k: string]: unknown;
  };
  genre_mapper?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string | null;
  };
  content_rating_mapper?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string | null;
  };
  metadata_backup?: {
    path?: string;
    exclude?: string | string[];
    sync_tags?: boolean;
    add_blank_entries?: boolean;
    [k: string]: unknown;
  };
}
export interface MetadataMapping {
  /**
   * This interface was referenced by `MetadataMapping`'s JSON-Schema definition
   * via the `patternProperty` "^.*$".
   */
  [k: string]: string | number | null;
}
export interface Settings {
  /**
   * Used to control Kometa's cache database.
   * Allow Kometa to create and maintain a local cache database for faster subsequent processing. The cache file is created in the same directory as the configuration file.
   */
  cache?: boolean;
  /**
   * Used to control how long data is cached for.
   * Set the number of days before each cache mapping expires and has to be re-cached. An integer greater than 0 in days
   */
  cache_expiration?: number;
  /**
   * Used to specify the run order of the library components.
   * Specify the run order of the library components [Library Operations, Collection Files and Overlay Files]
   */
  run_order?: ("operations" | "metadata" | "collections" | "overlays")[];
  /**
   * Used to define where local assets are located.
   * Specify the directories where assets (posters, backgrounds, etc) are located.
   */
  asset_directory?: string | string[] | null;
  /**
   * Used to control the asset directory folder structure.
   * While true, Kometa will search the asset_directory for a dedicated folder per item vs while false will look for an image.
   */
  asset_folders?: boolean;
  /**
   * Used to control the depth of search in the asset directory.
   * At each asset level, Kometa will look for either medianame.ext [such as Star Wars.png] or a dedicated folder containing poster.ext. i.e. <path_to_assets>/Star Wars/poster.png and <path_to_assets>/Star Wars.png are both asset depth 0, whilst <path_to_assets>/Movies/Star Wars/poster.png and <path_to_assets>/Movies/Star Wars.png are both asset level 1.
   */
  asset_depth?: number;
  /**
   * Used to automatically create asset folders when none exist.
   * Whilst searching for assets, if an asset folder cannot be found within the asset_directory one will be created. Asset Searches can happen in a number of ways.
   */
  create_asset_folders?: boolean;
  /**
   * Used to prioritize asset_directory images over all other images types.
   * When determining which image to use on an item prioritize the asset_directory over all other images types.
   */
  prioritize_assets?: boolean;
  /**
   * Used to automatically rename asset files based on their dimensions.
   * Whilst searching for assets, scan the folders within the asset_directory and if an asset poster (i.e. /ASSET_NAME/poster.ext) was not found, rename the first image found that has a height greater than or equal to its width to poster.ext. If an asset background (i.e. /ASSET_NAME/background.ext), rename the first image found that has a width greater than its height to background.ext.
   */
  dimensional_asset_rename?: boolean;
  /**
   * Used to download url images into the asset directory.
   * Whilst searching for assets, download images set within Collection/Metadata/Playlist files( i.e. images set by url_poster or url_background) into the asset folder if none are already present.
   */
  download_url_assets?: boolean;
  /**
   *  Used to show any missing season assets.
   * Whilst searching for assets, when scanning for assets for a TV Show, if Season posters are found (i.e. /ASSET_NAME/Season##.ext), notify the user of any seasons which do not have an asset image.
   */
  show_missing_season_assets?: boolean;
  /**
   * Used to show any missing episode assets.
   * Whilst searching for assets, when scanning for assets for a TV Show, if an Episode Title Card is found (i.e. /ASSET_NAME/S##E##.ext), notify the user of any episodes which do not have an asset image.
   */
  show_missing_episode_assets?: boolean;
  /**
   * Used to show/hide the update not needed messages.
   * Whilst searching for assets, show or hide the update not needed messages.
   */
  show_asset_not_needed?: boolean;
  /**
   * Used to set the sync_mode for collections and playlists.
   * Sets the sync_mode for collections and playlists. Setting the sync_mode directly in a collection or playlist definition will override the sync_mode for that definition.
   */
  sync_mode?: "sync" | "append";
  /**
   * Used to control minimum items requires to build a collection/playlist.
   * Set the minimum number of items that must be found in order to build or update a collection/playlist.
   */
  minimum_items?: number;
  /**
   * Priority position for all collections in this defaults file's Recommendation Hub rows. Lower numbers appear first.
   */
  hub_priority?: number;
  /**
   * Used to set the collection_order for every collection run.
   * Set the collection_order for every collection run by Kometa unless the collection has a specific collection_order
   * TIP: 'custom' cannot be used if more than one builder is being used for the collection (such as imdb_list and trakt_list within the same collection).
   */
  default_collection_order?:
    | "added.asc"
    | "added.desc"
    | "alpha"
    | "audience_rating.asc"
    | "audience_rating.desc"
    | "bitrate.asc"
    | "bitrate.desc"
    | "content_rating.asc"
    | "content_rating.desc"
    | "critic_rating.asc"
    | "critic_rating.desc"
    | "custom"
    | "duration.asc"
    | "duration.desc"
    | "originally_available.asc"
    | "originally_available.desc"
    | "plays.asc"
    | "plays.desc"
    | "progress.asc"
    | "progress.desc"
    | "random"
    | "release"
    | "release.asc"
    | "release.desc"
    | "resolution.asc"
    | "resolution.desc"
    | "title.asc"
    | "title.desc"
    | "user_rating.asc"
    | "user_rating.desc"
    | "viewed.asc"
    | "viewed.desc"
    | "year.asc"
    | "year.desc"
    | null;
  /**
   * Used to delete collections below minimum_items.
   * When a collection is run, delete the collection if it is below the minimum number specified by minimum_items.
   */
  delete_below_minimum?: boolean;
  /**
   * Used to delete collections not scheduled.
   * If a collection is skipped due to it not being scheduled, delete the collection.
   */
  delete_not_scheduled?: boolean;
  /**
   * Used to sort Recommendation Hub rows after all collections are processed.
   * Sorts the library Recommendation Hub rows on the Plex home screen and/or library Recommended tab.
   */
  auto_sort_hubs?:
    "sort_title" | "sort_title.desc" | "alpha" | "alpha.desc" | "configured" | "configured.desc" | "random" | null;
  /**
   * Used to control the number of minutes to delay running run_again collections.
   * Set the number of minutes to delay running run_again collections after daily run is finished. For example, if a collection adds items to Sonarr/Radarr, the library can automatically re-run 'X' amount of time later so that any downloaded items are processed.
   */
  run_again_delay?: number;
  /**
   * Used to filter unreleased items from missing lists.
   * Whilst running a collection or playlist, when Kometa handles missing items to either report it to the user, report it to a file, or send it to Radarr/Sonarr all unreleased items will be filtered out.
   */
  missing_only_released?: boolean;
  /**
   * Used to have the filter only apply to missing items.
   * Only items missing from a collection will be filtered. Only specific filters can filter missing. See Filters for more information.
   */
  only_filter_missing?: boolean;
  /**
   * Used to show collections not managed by Kometa.
   * List all collections not managed by Kometa at the end of each run.
   */
  show_unmanaged?: boolean;
  /**
   * Used to show collections not in the current run.
   * List all collections not configured in the current Kometa run at the end of each run.
   */
  show_unconfigured?: boolean;
  /**
   * Used to show filtered items.
   * List all items which have been filtered out of a collection or playlist (i.e. if it doesn't meet the filter criteria)
   */
  show_filtered?: boolean;
  /**
   * Used to show unfiltered items.
   * List all items which make it through a filter into a collection or playlist (i.e. if it MEETS the filter criteria)
   */
  show_unfiltered?: boolean;
  /**
   * Used to show attribute options from plex.
   * While show_options is true the available options for an attribute when using plex_search, smart_filter or filters will be shown. i.e. a smart_filter on the genre attribute will return all of the attributes within the specified library.
   */
  show_options?: boolean;
  /**
   * Used to show missing items from collections or playlists.
   * While show_missing is true items missing from collections or playlists will be displayed.
   */
  show_missing?: boolean;
  /**
   * Used to print a message when assets are missing.
   * Display missing asset warnings for items, collections, and playlists.
   */
  show_missing_assets?: boolean;
  /**
   * Used to save a report YAML file.
   * Save a report of the items added, removed, filtered, or missing from collections to a YAML file in the same directory as the file run.
   */
  save_report?: boolean;
  /**
   * Specify the language to query TVDb in.
   * This field can be either null or a valid ISO 639-2 language code.
   */
  tvdb_language?:
    | (
        | ""
        | "default"
        | "aar"
        | "abk"
        | "afr"
        | "aka"
        | "alb"
        | "amh"
        | "ara"
        | "arg"
        | "arm"
        | "asm"
        | "ava"
        | "ave"
        | "aym"
        | "aze"
        | "bak"
        | "bam"
        | "baq"
        | "bel"
        | "ben"
        | "bis"
        | "bos"
        | "bre"
        | "bul"
        | "bur"
        | "cat"
        | "cha"
        | "che"
        | "chi"
        | "chu"
        | "chv"
        | "cor"
        | "cos"
        | "cre"
        | "cze"
        | "dan"
        | "div"
        | "dut"
        | "dzo"
        | "eng"
        | "epo"
        | "est"
        | "ewe"
        | "fao"
        | "fij"
        | "fin"
        | "fre"
        | "fry"
        | "ful"
        | "geo"
        | "ger"
        | "gla"
        | "gle"
        | "glg"
        | "glv"
        | "gre"
        | "grn"
        | "guj"
        | "hat"
        | "hau"
        | "heb"
        | "her"
        | "hin"
        | "hmo"
        | "hrv"
        | "hun"
        | "ibo"
        | "ice"
        | "ido"
        | "iii"
        | "iku"
        | "ile"
        | "ina"
        | "ind"
        | "ipk"
        | "ita"
        | "jav"
        | "jpn"
        | "kal"
        | "kan"
        | "kas"
        | "kau"
        | "kaz"
        | "khm"
        | "kik"
        | "kin"
        | "kir"
        | "kom"
        | "kon"
        | "kor"
        | "kua"
        | "kur"
        | "lao"
        | "lat"
        | "lav"
        | "lim"
        | "lin"
        | "lit"
        | "ltz"
        | "lub"
        | "lug"
        | "mac"
        | "mah"
        | "mal"
        | "mao"
        | "mar"
        | "may"
        | "mlg"
        | "mlt"
        | "mon"
        | "nau"
        | "nav"
        | "nbl"
        | "nde"
        | "ndo"
        | "nep"
        | "nno"
        | "nob"
        | "nor"
        | "nya"
        | "oci"
        | "oji"
        | "ori"
        | "orm"
        | "oss"
        | "pan"
        | "per"
        | "pli"
        | "pol"
        | "por"
        | "pus"
        | "que"
        | "roh"
        | "rum"
        | "run"
        | "rus"
        | "sag"
        | "san"
        | "sin"
        | "slo"
        | "slv"
        | "sme"
        | "smo"
        | "sna"
        | "snd"
        | "som"
        | "sot"
        | "spa"
        | "srd"
        | "srp"
        | "ssw"
        | "sun"
        | "swa"
        | "swe"
        | "tah"
        | "tam"
        | "tat"
        | "tel"
        | "tgk"
        | "tgl"
        | "tha"
        | "tib"
        | "tir"
        | "ton"
        | "tsn"
        | "tso"
        | "tuk"
        | "tur"
        | "twi"
        | "uig"
        | "ukr"
        | "urd"
        | "uzb"
        | "ven"
        | "vie"
        | "vol"
        | "wel"
        | "wln"
        | "wol"
        | "xho"
        | "yid"
        | "yor"
        | "zha"
        | "zul"
      )
    | null;
  /**
   * List of TMDb/TVDb IDs to ignore.
   * Set a null, a single TMDb/TVDb ID, or a comma-separated string of TMDb/TVDb IDs to ignore in all collections.
   */
  ignore_ids?: null | [number, ...number[]] | string | number;
  /**
   * List of IMDb IDs to ignore.
   * Set a null, a single IMDb ID, or a comma-separated string of IMDb IDs to ignore in all collections.
   */
  ignore_imdb_ids?: null | string | [string, ...string[]];
  /**
   * Time to wait between each item_refresh.
   * Specify the amount of time to wait between each item_refresh of every movie/show in a collection/playlist.
   */
  item_refresh_delay?: number;
  /**
   * Set the default playlist sync_to_users.
   * To Sync a playlist to only yourself, leave playlist_sync_to_users blank/null. Therefore, leaving it blank, 'all', a list of users, or a comma-separated string of users is accepted
   */
  playlist_sync_to_users?: "all" | [string, ...string[]] | string | null;
  /**
   * Set the default playlist exclude_users.
   * Provide a null value, a list of users, or a comma-separated string of users to be excluded in the playlist.
   */
  playlist_exclude_users?: null | [string, ...string[]] | string;
  /**
   * Used to print out a playlist report.
   * Set playlist_report to true to print out a playlist report at the end of the log.
   */
  playlist_report?: boolean;
  /**
   * Turn SSL Verification on or off.
   */
  verify_ssl?: boolean;
  /**
   * Used to set up the custom repo file block type.
   * Specify where the repo attribute's base is when defining collection_files, metadata_files, playlist_file, and overlay_files.
   */
  custom_repo?: null | string;
  /**
   * Used to control the filetype used with overlay images.
   */
  overlay_artwork_filetype?: "jpg" | "png" | "webp_lossy" | "webp_lossless";
  /**
   * Used to control the JPG or Lossy WEBP quality used with overlay images.
   */
  overlay_artwork_quality?: number | null;
}
/**
 * Describes the Plex server where this library is found.
 */
export interface Plex {
  /**
   * URL at which Kometa can connect to this plex server.  NOT app.plex.tv
   */
  url?: string | null;
  /**
   * Admin token for this Plex server
   */
  token?: string | null;
  /**
   * Connection timeout in seconds for this Plex server
   */
  timeout?: number;
  /**
   * Sets DB Cache value for this Plex server in MB
   */
  db_cache?: number | string | null;
  /**
   * true/false - If 'true', cleans metadata bundles on this Plex server
   */
  clean_bundles?: boolean;
  /**
   * true/false - If 'true', empties trash on this Plex server
   */
  empty_trash?: boolean;
  /**
   * true/false - If 'true', optimizes database on this Plex server
   */
  optimize?: boolean;
  /**
   * Turn SSL Verification on or off for this library's Plex server.
   */
  verify_ssl?: boolean | null;
}
export interface Radarr {
  url?: string | null;
  token?: string | null;
  add_missing?: boolean;
  add_existing?: boolean;
  ignore_cache?: boolean;
  upgrade_existing?: boolean;
  search?: boolean;
  root_folder_path?: string | null;
  monitor?: boolean;
  monitor_existing?: boolean;
  quality_profile?: string | null;
  availability?: "announced" | "cinemas" | "released" | "db";
  tag?: string | null;
  radarr_path?: string | null;
  plex_path?: string | null;
}
export interface Sonarr {
  url?: string | null;
  token?: string | null;
  add_missing?: boolean;
  add_existing?: boolean;
  ignore_cache?: boolean;
  upgrade_existing?: boolean;
  season_folder?: boolean;
  search?: boolean;
  cutoff_search?: boolean;
  root_folder_path?: string | null;
  monitor?: "all" | "future" | "missing" | "existing" | "pilot" | "first" | "latest" | "none";
  /**
   * Ensures all existing shows in collections match your monitor setting.
   */
  monitor_existing?: boolean;
  quality_profile?: string | null;
  language_profile?: string;
  series_type?: "standard" | "daily" | "anime";
  tag?: string | null;
  sonarr_path?: string | null;
  plex_path?: string | null;
}
export interface Tautulli {
  apikey?: string | null;
  url?: string | null;
}
export interface Tracearr {
  apikey?: string | null;
  server_id?: string | null;
  url?: string | null;
}
export interface TemplateVariables2 {
  /**
   * Multiple styles are available for Separators, to match Plex's 'categories' feature.
   */
  sep_style?:
    | "amethyst"
    | "aqua"
    | "blue"
    | "forest"
    | "fuchsia"
    | "gold"
    | "gray"
    | "green"
    | "navy"
    | "ocean"
    | "olive"
    | "orchid"
    | "orig"
    | "pink"
    | "plum"
    | "purple"
    | "red"
    | "rust"
    | "salmon"
    | "sand"
    | "stb"
    | "tan";
  /**
   * Controls the collection mode of all collections in a Defaults file.
   */
  collection_mode?: "default" | "hide" | "hide_items" | "show_items";
  /**
   * Set the language of Collection Names and Summaries that Kometa has been translated to with weblate
   */
  language?: "en" | "fr" | "ar" | "da" | "nl" | "de" | "it" | "pt-br" | "nb-no" | "es" | "sv" | "ru" | "bg" | "hu";
  /**
   * Add a placeholder Movie/Show to the Separator to ensure Plex sees a collection with 1 item because 0 item collections can be problematic for Plex.
   * Valid for Movie or Show libraries assuming the ID points to an item of the correct type and that its in your library.
   */
  placeholder_imdb_id?: string;
  [k: string]: unknown;
}
/**
 * Describes the primary Plex server to which Kometa can connect.
 * This attribute is REQUIRED.  It can be overridden at the library level.
 */
export interface Plex1 {
  /**
   * URL at which Kometa can connect to your plex server. NOT app.plex.tv
   */
  url: string | null;
  /**
   * Admin token for this Plex server
   */
  token: string | null;
  /**
   * Connection timeout in seconds for this Plex server
   */
  timeout?: number;
  /**
   * Sets DB Cache value for this Plex server in MB
   */
  db_cache?: number | string | null;
  /**
   * true/false - If 'true', cleans metadata bundles on this Plex server
   */
  clean_bundles?: boolean;
  /**
   * true/false - If 'true', empties trash on this Plex server
   */
  empty_trash?: boolean;
  /**
   * true/false - If 'true', optimizes database on this Plex server
   */
  optimize?: boolean;
  /**
   * Turn SSL Verification on or off for only Plex.
   */
  verify_ssl?: boolean | null;
}
/**
 * API Information to connect to TMDb; REQUIRED for the script to run
 */
export interface Tmdb {
  /**
   * API Key to connect to TMDb; REQUIRED for the script to run
   */
  apikey: string | null;
  /**
   * This field can be either null or a valid ISO 639 language code.
   */
  language?:
    | (
        | ""
        | "aa"
        | "ab"
        | "ae"
        | "af"
        | "ak"
        | "am"
        | "an"
        | "ar"
        | "as"
        | "av"
        | "ay"
        | "az"
        | "ba"
        | "be"
        | "bg"
        | "bi"
        | "bm"
        | "bn"
        | "bo"
        | "br"
        | "bs"
        | "ca"
        | "ce"
        | "ch"
        | "co"
        | "cr"
        | "cs"
        | "cu"
        | "cv"
        | "cy"
        | "da"
        | "de"
        | "dv"
        | "dz"
        | "ee"
        | "el"
        | "en"
        | "eo"
        | "es"
        | "et"
        | "eu"
        | "fa"
        | "ff"
        | "fi"
        | "fj"
        | "fo"
        | "fr"
        | "fy"
        | "ga"
        | "gd"
        | "gl"
        | "gn"
        | "gu"
        | "gv"
        | "ha"
        | "he"
        | "hi"
        | "ho"
        | "hr"
        | "ht"
        | "hu"
        | "hy"
        | "hz"
        | "ia"
        | "id"
        | "ie"
        | "ig"
        | "ii"
        | "ik"
        | "io"
        | "is"
        | "it"
        | "iu"
        | "ja"
        | "jv"
        | "ka"
        | "kg"
        | "ki"
        | "kj"
        | "kk"
        | "kl"
        | "km"
        | "kn"
        | "ko"
        | "kr"
        | "ks"
        | "ku"
        | "kv"
        | "kw"
        | "ky"
        | "la"
        | "lb"
        | "lg"
        | "li"
        | "ln"
        | "lo"
        | "lt"
        | "lu"
        | "lv"
        | "mg"
        | "mh"
        | "mi"
        | "mk"
        | "ml"
        | "mn"
        | "mr"
        | "ms"
        | "mt"
        | "my"
        | "na"
        | "nb"
        | "nd"
        | "ne"
        | "ng"
        | "nl"
        | "nn"
        | "no"
        | "nr"
        | "nv"
        | "ny"
        | "oc"
        | "oj"
        | "om"
        | "or"
        | "os"
        | "pa"
        | "pi"
        | "pl"
        | "ps"
        | "pt"
        | "qu"
        | "rm"
        | "rn"
        | "ro"
        | "ru"
        | "rw"
        | "sa"
        | "sc"
        | "sd"
        | "se"
        | "sg"
        | "si"
        | "sk"
        | "sl"
        | "sm"
        | "sn"
        | "so"
        | "sq"
        | "sr"
        | "ss"
        | "st"
        | "su"
        | "sv"
        | "sw"
        | "ta"
        | "te"
        | "tg"
        | "th"
        | "ti"
        | "tk"
        | "tl"
        | "tn"
        | "to"
        | "tr"
        | "ts"
        | "tt"
        | "tw"
        | "ty"
        | "ug"
        | "uk"
        | "ur"
        | "uz"
        | "ve"
        | "vi"
        | "vo"
        | "wa"
        | "wo"
        | "xh"
        | "yi"
        | "yo"
        | "za"
        | "zh"
        | "zu"
      )
    | null;
  /**
   * This field can be either null or a valid ISO 3166-1 Code.
   */
  region?:
    | (
        | ""
        | "AD"
        | "AE"
        | "AF"
        | "AG"
        | "AI"
        | "AL"
        | "AM"
        | "AO"
        | "AQ"
        | "AR"
        | "AS"
        | "AT"
        | "AU"
        | "AW"
        | "AX"
        | "AZ"
        | "BA"
        | "BB"
        | "BD"
        | "BE"
        | "BF"
        | "BG"
        | "BH"
        | "BI"
        | "BJ"
        | "BL"
        | "BM"
        | "BN"
        | "BO"
        | "BQ"
        | "BR"
        | "BS"
        | "BT"
        | "BV"
        | "BW"
        | "BY"
        | "BZ"
        | "CA"
        | "CC"
        | "CD"
        | "CF"
        | "CG"
        | "CH"
        | "CI"
        | "CK"
        | "CL"
        | "CM"
        | "CN"
        | "CO"
        | "CR"
        | "CU"
        | "CV"
        | "CW"
        | "CX"
        | "CY"
        | "CZ"
        | "DE"
        | "DJ"
        | "DK"
        | "DM"
        | "DO"
        | "DZ"
        | "EC"
        | "EE"
        | "EG"
        | "EH"
        | "ER"
        | "ES"
        | "ET"
        | "FI"
        | "FJ"
        | "FK"
        | "FM"
        | "FO"
        | "FR"
        | "GA"
        | "GB"
        | "GD"
        | "GE"
        | "GF"
        | "GG"
        | "GH"
        | "GI"
        | "GL"
        | "GM"
        | "GN"
        | "GP"
        | "GQ"
        | "GR"
        | "GS"
        | "GT"
        | "GU"
        | "GW"
        | "GY"
        | "HK"
        | "HM"
        | "HN"
        | "HR"
        | "HT"
        | "HU"
        | "ID"
        | "IE"
        | "IL"
        | "IM"
        | "IN"
        | "IO"
        | "IQ"
        | "IR"
        | "IS"
        | "IT"
        | "JE"
        | "JM"
        | "JO"
        | "JP"
        | "KE"
        | "KG"
        | "KH"
        | "KI"
        | "KM"
        | "KN"
        | "KP"
        | "KR"
        | "KW"
        | "KY"
        | "KZ"
        | "LA"
        | "LB"
        | "LC"
        | "LI"
        | "LK"
        | "LR"
        | "LS"
        | "LT"
        | "LU"
        | "LV"
        | "LY"
        | "MA"
        | "MC"
        | "MD"
        | "ME"
        | "MF"
        | "MG"
        | "MH"
        | "MK"
        | "ML"
        | "MM"
        | "MN"
        | "MO"
        | "MP"
        | "MQ"
        | "MR"
        | "MS"
        | "MT"
        | "MU"
        | "MV"
        | "MW"
        | "MX"
        | "MY"
        | "MZ"
        | "NA"
        | "NC"
        | "NE"
        | "NF"
        | "NG"
        | "NI"
        | "NL"
        | "NO"
        | "NP"
        | "NR"
        | "NU"
        | "NZ"
        | "OM"
        | "PA"
        | "PE"
        | "PF"
        | "PG"
        | "PH"
        | "PK"
        | "PL"
        | "PM"
        | "PN"
        | "PR"
        | "PS"
        | "PT"
        | "PW"
        | "PY"
        | "QA"
        | "RE"
        | "RO"
        | "RS"
        | "RU"
        | "RW"
        | "SA"
        | "SB"
        | "SC"
        | "SD"
        | "SE"
        | "SG"
        | "SH"
        | "SI"
        | "SJ"
        | "SK"
        | "SL"
        | "SM"
        | "SN"
        | "SO"
        | "SR"
        | "SS"
        | "ST"
        | "SV"
        | "SX"
        | "SY"
        | "SZ"
        | "TC"
        | "TD"
        | "TF"
        | "TG"
        | "TH"
        | "TJ"
        | "TK"
        | "TL"
        | "TM"
        | "TN"
        | "TO"
        | "TR"
        | "TT"
        | "TV"
        | "TW"
        | "TZ"
        | "UA"
        | "UG"
        | "UM"
        | "US"
        | "UY"
        | "UZ"
        | "VA"
        | "VC"
        | "VE"
        | "VG"
        | "VI"
        | "VN"
        | "VU"
        | "WF"
        | "WS"
        | "YE"
        | "YT"
        | "ZA"
        | "ZM"
        | "ZW"
      )
    | null;
  /**
   * An integer greater than 0 in days
   */
  cache_expiration?: number;
}
export interface Webhooks {
  error?: string | null;
  version?: string | null;
  run_start?: string | null;
  run_end?: string | null;
  changes?: string | null;
  delete?: string | null;
}
export interface Omdb {
  apikey?: string | null;
  /**
   * An integer greater than 0 in days
   */
  cache_expiration?: number;
}
export interface Mdblist {
  apikey?: string | null;
  /**
   * An integer greater than 0 in days
   */
  cache_expiration?: number;
}
export interface Notifiarr {
  apikey?: string | null;
  url?: string | null;
}
export interface Gotify {
  url: string;
  token: string;
}
export interface Ntfy {
  url: string;
  token: string;
  topic: string;
}
export interface Anidb {
  /**
   * This field can be either null or a valid ISO 639 language code.
   */
  language?:
    | (
        | ""
        | "aa"
        | "ab"
        | "ae"
        | "af"
        | "ak"
        | "am"
        | "an"
        | "ar"
        | "as"
        | "av"
        | "ay"
        | "az"
        | "ba"
        | "be"
        | "bg"
        | "bi"
        | "bm"
        | "bn"
        | "bo"
        | "br"
        | "bs"
        | "ca"
        | "ce"
        | "ch"
        | "co"
        | "cr"
        | "cs"
        | "cu"
        | "cv"
        | "cy"
        | "da"
        | "de"
        | "dv"
        | "dz"
        | "ee"
        | "el"
        | "en"
        | "eo"
        | "es"
        | "et"
        | "eu"
        | "fa"
        | "ff"
        | "fi"
        | "fj"
        | "fo"
        | "fr"
        | "fy"
        | "ga"
        | "gd"
        | "gl"
        | "gn"
        | "gu"
        | "gv"
        | "ha"
        | "he"
        | "hi"
        | "ho"
        | "hr"
        | "ht"
        | "hu"
        | "hy"
        | "hz"
        | "ia"
        | "id"
        | "ie"
        | "ig"
        | "ii"
        | "ik"
        | "io"
        | "is"
        | "it"
        | "iu"
        | "ja"
        | "jv"
        | "ka"
        | "kg"
        | "ki"
        | "kj"
        | "kk"
        | "kl"
        | "km"
        | "kn"
        | "ko"
        | "kr"
        | "ks"
        | "ku"
        | "kv"
        | "kw"
        | "ky"
        | "la"
        | "lb"
        | "lg"
        | "li"
        | "ln"
        | "lo"
        | "lt"
        | "lu"
        | "lv"
        | "mg"
        | "mh"
        | "mi"
        | "mk"
        | "ml"
        | "mn"
        | "mr"
        | "ms"
        | "mt"
        | "my"
        | "na"
        | "nb"
        | "nd"
        | "ne"
        | "ng"
        | "nl"
        | "nn"
        | "no"
        | "nr"
        | "nv"
        | "ny"
        | "oc"
        | "oj"
        | "om"
        | "or"
        | "os"
        | "pa"
        | "pi"
        | "pl"
        | "ps"
        | "pt"
        | "qu"
        | "rm"
        | "rn"
        | "ro"
        | "ru"
        | "rw"
        | "sa"
        | "sc"
        | "sd"
        | "se"
        | "sg"
        | "si"
        | "sk"
        | "sl"
        | "sm"
        | "sn"
        | "so"
        | "sq"
        | "sr"
        | "ss"
        | "st"
        | "su"
        | "sv"
        | "sw"
        | "ta"
        | "te"
        | "tg"
        | "th"
        | "ti"
        | "tk"
        | "tl"
        | "tn"
        | "to"
        | "tr"
        | "ts"
        | "tt"
        | "tw"
        | "ty"
        | "ug"
        | "uk"
        | "ur"
        | "uz"
        | "ve"
        | "vi"
        | "vo"
        | "wa"
        | "wo"
        | "xh"
        | "yi"
        | "yo"
        | "za"
        | "zh"
        | "zu"
      )
    | null;
  /**
   * An integer greater than 0 in days
   */
  cache_expiration?: number;
  /**
   * Enable access to mature/restricted content
   */
  enable_mature?: boolean;
}
export interface Sonarr1 {
  url?: string | null;
  token?: string | null;
  add_missing?: boolean;
  add_existing?: boolean;
  ignore_cache?: boolean;
  upgrade_existing?: boolean;
  season_folder?: boolean;
  search?: boolean;
  cutoff_search?: boolean;
  root_folder_path?: string | null;
  monitor?: "all" | "future" | "missing" | "existing" | "pilot" | "first" | "latest" | "none";
  /**
   * Ensures all existing shows in collections match your monitor setting.
   * Use the sonarr_monitor_existing Sonarr Setting in the collection definition to match the monitor setting per collection.
   */
  monitor_existing?: boolean;
  quality_profile?: string | null;
  language_profile?: string;
  series_type?: "standard" | "daily" | "anime";
  tag?: string | null;
  cutoff?: string;
  plex_path?: string | null;
  sonarr_path?: string | null;
}
export interface Radarr1 {
  url?: string | null;
  token?: string | null;
  add_missing?: boolean;
  add_existing?: boolean;
  ignore_cache?: boolean;
  upgrade_existing?: boolean;
  search?: boolean;
  root_folder_path?: string | null;
  monitor?: boolean;
  monitor_existing?: boolean;
  quality_profile?: string | null;
  availability?: "announced" | "cinemas" | "released" | "db";
  tag?: string | null;
  radarr_path?: string | null;
  plex_path?: string | null;
}
export interface Mal {
  client_id?: string | null;
  client_secret?: string | null;
  [k: string]: unknown;
}
export interface Trakt {
  client_id?: string | null;
  client_secret?: string | null;
  [k: string]: unknown;
}
export interface Yamtrack {
  url?: string;
  username?: string;
  password?: string;
}
export interface Serializd {
  email: string;
  password: string;
  timeout?: number;
}
export interface Floppy {
  url: string;
  token?: string | null;
}
/**
 * GitHub API credentials. Optional — providing a token raises the rate limit for GitHub requests.
 */
export interface Github {
  /**
   * GitHub Personal Access Token. Generate at https://github.com/settings/tokens
   */
  token?: string;
}
/**
 * @deprecated
 */
export interface LegacyDefaultPlaylistPath {
  pmm: "playlist";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables3;
}
/**
 * Template variables for playlist defaults files.
 */
export interface TemplateVariables3 {
  /**
   * Image style used by defaults that support multiple poster styles.
   */
  style?:
    | "color"
    | "white"
    | "bw"
    | "diiivoy"
    | "diiivoycolor"
    | "rainier"
    | "signature"
    | "orig"
    | "transparent"
    | "default"
    | "standards";
  /**
   * Which users to sync the playlist to. 'all' for all users.
   */
  sync_to_users?: string | null | string[];
  /**
   * Users to exclude from the playlist sync.
   */
  exclude_users?: string | null | string[];
  /**
   * Libraries to pull items from for all playlists in this defaults file. When omitted, playlists use every library processed as part of the run.
   */
  libraries?: string | string[];
  /**
   * Minimum items required for any playlist to be created.
   */
  minimum_items?: number;
  /**
   * Priority position for all collections in this defaults file's Recommendation Hub rows. Lower numbers appear first.
   */
  hub_priority?: number;
  /**
   * Poster URL for all playlists in this defaults file.
   */
  url_poster?: string;
  /**
   * Poster filepath for all playlists in this defaults file.
   */
  file_poster?: string;
  /**
   * Set the schedule for all playlists in this defaults file.
   */
  schedule?: string;
  /**
   * Delete playlists when not scheduled.
   */
  delete_not_scheduled?: boolean;
  /**
   * Maximum number of items for all playlists in this defaults file.
   */
  limit?: number;
  delete_playlist?: boolean;
  exclude_user?: string | unknown[];
  ignore_ids?: string | unknown[] | number;
  ignore_imdb_ids?: string | unknown[];
  item_radarr_tag?: string | unknown[];
  item_sonarr_tag?: string | unknown[];
  radarr_add_missing?: boolean;
  radarr_folder?: string;
  radarr_tag?: string | unknown[];
  sonarr_add_missing?: boolean;
  sonarr_folder?: string;
  sonarr_tag?: string | unknown[];
  [k: string]: unknown;
}
export interface KometaDefaultPlaylistPath {
  default: "playlist";
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables3;
}
export interface FilePathPlaylistWithTemplateVariables {
  file: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables3;
}
export interface UrlPathPlaylistWithTemplateVariables {
  url: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables3;
}
export interface GitPathPlaylistWithTemplateVariables {
  git: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables3;
}
export interface RepoPathPlaylistWithTemplateVariables {
  repo: string;
  schedule?: string;
  asset_directory?: string | string[];
  template_variables?: TemplateVariables3;
}
