{
 "title": "Network Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Internet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"gateway\",device=\"igb0\"}[$__rate_interval])*8",
     "legendFormat": "outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"gateway\",device=\"igb0\"}[$__rate_interval])*8",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"gateway\",device=\"igb0\"}[$__rate_interval])*8"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"gateway\",device=\"igb0\"}[$__rate_interval])*8"
    }
   ]
  },
  {
   "title": "Internet Usage - 30d moving average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"gateway\",device=\"igb0\"}[30d])\n",
     "legendFormat": "Incoming"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"gateway\",device=\"igb0\"}[30d])\n",
     "legendFormat": "Outgoing"
    }
   ]
  },
  { "title": "Lakelair site-to-site", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Site-to-Site - lakelair.net",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"gateway\",device=\"wg0\"}[$__rate_interval])*8",
     "legendFormat": "outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"gateway\",device=\"wg0\"}[$__rate_interval])*8",
     "legendFormat": "inbound"
    }
   ]
  },
  {
   "title": "Latency - lakelair.net",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_icmp_duration_seconds{phase=\"rtt\",job=\"blackbox-ping-lakelair\",instance=\"192.168.0.1\"}[$__range])"
    }
   ]
  },
  {
   "title": "Site-to-Site Data - 30d moving average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=\"gateway\",device=\"wg0\"}[30d])\n",
     "legendFormat": "Incoming"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"gateway\",device=\"wg0\"}[30d])\n",
     "legendFormat": "Outgoing"
    }
   ]
  },
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Which DNS is best?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_icmp_duration_seconds{phase=\"rtt\",job=\"blackbox-ping-dns\"}[$__range])",
     "legendFormat": "Avg {{instance}}"
    }
   ]
  },
  {
   "title": "Is this loss?",
   "type": "gauge",
   "description": "Ping loss ratio",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(1 - avg(probe_success{job!=\"blackbox-ping-lakelair\"}))",
     "legendFormat": "Average loss"
    },
    {
     "expr": "abs(1 - max(probe_success{job!=\"blackbox-ping-lakelair\"}))",
     "legendFormat": "Worst loss"
    }
   ]
  }
 ]
}