#!/usr/bin/env bash
#MISE description="Synthesize all apps"
#MISE depends=["install"]
#MISE sources=["apps/**/*.ts", "lib/**/*.ts", "imports/**/*.ts", "package.json", "bun.lockb"]
#MISE outputs=["dist/**/*.yaml"]

set -euo pipefail

find dist -type f ! \( -name '.argocd-source-*.yaml' -o -name 'sealedsecret.*.yaml' \) -delete
find dist -type d -empty -delete

NPROC=$(getconf _NPROCESSORS_ONLN)
apps=($(find apps -maxdepth 1 -mindepth 1 -type d | sort))
printf '%s\n' "${apps[@]}" | xargs -P "$NPROC" -I{} sh -c 'echo "bun run {}/app.ts"; bun run "{}/app.ts"'
