// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * ImageUpdater is the Schema for the imageupdaters API
 *
 * @schema ImageUpdater
 */
export class ImageUpdater extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ImageUpdater"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'argocd-image-updater.argoproj.io/v1alpha1',
    kind: 'ImageUpdater',
  }

  /**
   * Renders a Kubernetes manifest for "ImageUpdater".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ImageUpdaterProps = {}): any {
    return {
      ...ImageUpdater.GVK,
      ...toJson_ImageUpdaterProps(props),
    };
  }

  /**
   * Defines a "ImageUpdater" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ImageUpdaterProps = {}) {
    super(scope, id, {
      ...ImageUpdater.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...ImageUpdater.GVK,
      ...toJson_ImageUpdaterProps(resolved),
    };
  }
}

/**
 * ImageUpdater is the Schema for the imageupdaters API
 *
 * @schema ImageUpdater
 */
export interface ImageUpdaterProps {
  /**
   * @schema ImageUpdater#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * ImageUpdaterSpec defines the desired state of ImageUpdater
   * It specifies which applications to target, default update strategies,
   * and a list of images to manage.
   *
   * @schema ImageUpdater#spec
   */
  readonly spec?: ImageUpdaterSpec;

}

/**
 * Converts an object of type 'ImageUpdaterProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterProps(obj: ImageUpdaterProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ImageUpdaterSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ImageUpdaterSpec defines the desired state of ImageUpdater
 * It specifies which applications to target, default update strategies,
 * and a list of images to manage.
 *
 * @schema ImageUpdaterSpec
 */
export interface ImageUpdaterSpec {
  /**
   * ApplicationRefs indicates the set of applications to be managed.
   * ApplicationRefs is a list of rules to select Argo CD Applications within the `spec.namespace`.
   * Each reference can also provide specific overrides for the global settings defined above.
   *
   * @schema ImageUpdaterSpec#applicationRefs
   */
  readonly applicationRefs: ImageUpdaterSpecApplicationRefs[];

  /**
   * CommonUpdateSettings provides global default settings for update strategies,
   * tag filtering, pull secrets, etc., for all applications matched by this CR.
   * These can be overridden at the ApplicationRef or ImageConfig level.
   *
   * @schema ImageUpdaterSpec#commonUpdateSettings
   */
  readonly commonUpdateSettings?: ImageUpdaterSpecCommonUpdateSettings;

  /**
   * Namespace indicates the target namespace of the applications.
   * This is the namespace where the controller will look for Argo CD Applications
   * matching the criteria in ApplicationRefs.
   *
   * @schema ImageUpdaterSpec#namespace
   */
  readonly namespace: string;

  /**
   * WriteBackConfig provides global default settings for how and where to write back image updates.
   * This can be overridden at the ApplicationRef level.
   *
   * @schema ImageUpdaterSpec#writeBackConfig
   */
  readonly writeBackConfig?: ImageUpdaterSpecWriteBackConfig;

}

/**
 * Converts an object of type 'ImageUpdaterSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpec(obj: ImageUpdaterSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'applicationRefs': obj.applicationRefs?.map(y => toJson_ImageUpdaterSpecApplicationRefs(y)),
    'commonUpdateSettings': toJson_ImageUpdaterSpecCommonUpdateSettings(obj.commonUpdateSettings),
    'namespace': obj.namespace,
    'writeBackConfig': toJson_ImageUpdaterSpecWriteBackConfig(obj.writeBackConfig),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ApplicationRef contains various criteria by which to include applications for managing by image updater
 *
 * @schema ImageUpdaterSpecApplicationRefs
 */
export interface ImageUpdaterSpecApplicationRefs {
  /**
   * CommonUpdateSettings overrides the global CommonUpdateSettings for applications
   * matched by this selector.
   *
   * @schema ImageUpdaterSpecApplicationRefs#commonUpdateSettings
   */
  readonly commonUpdateSettings?: ImageUpdaterSpecApplicationRefsCommonUpdateSettings;

  /**
   * Images contains a list of configurations that how images should be updated.
   * These rules apply to applications selected by namePattern in ApplicationRefs, and each
   * image can override global/ApplicationRef settings.
   *
   * @schema ImageUpdaterSpecApplicationRefs#images
   */
  readonly images: ImageUpdaterSpecApplicationRefsImages[];

  /**
   * LabelSelectors indicates the label selectors to apply for application selection
   *
   * @schema ImageUpdaterSpecApplicationRefs#labelSelectors
   */
  readonly labelSelectors?: ImageUpdaterSpecApplicationRefsLabelSelectors;

  /**
   * NamePattern indicates the glob pattern for application name
   *
   * @schema ImageUpdaterSpecApplicationRefs#namePattern
   */
  readonly namePattern: string;

  /**
   * WriteBackConfig overrides the global WriteBackConfig settings for applications
   * matched by this selector.
   *
   * @schema ImageUpdaterSpecApplicationRefs#writeBackConfig
   */
  readonly writeBackConfig?: ImageUpdaterSpecApplicationRefsWriteBackConfig;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefs' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefs(obj: ImageUpdaterSpecApplicationRefs | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'commonUpdateSettings': toJson_ImageUpdaterSpecApplicationRefsCommonUpdateSettings(obj.commonUpdateSettings),
    'images': obj.images?.map(y => toJson_ImageUpdaterSpecApplicationRefsImages(y)),
    'labelSelectors': toJson_ImageUpdaterSpecApplicationRefsLabelSelectors(obj.labelSelectors),
    'namePattern': obj.namePattern,
    'writeBackConfig': toJson_ImageUpdaterSpecApplicationRefsWriteBackConfig(obj.writeBackConfig),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * CommonUpdateSettings provides global default settings for update strategies,
 * tag filtering, pull secrets, etc., for all applications matched by this CR.
 * These can be overridden at the ApplicationRef or ImageConfig level.
 *
 * @schema ImageUpdaterSpecCommonUpdateSettings
 */
export interface ImageUpdaterSpecCommonUpdateSettings {
  /**
   * AllowTags is a regex pattern for tags to allow.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecCommonUpdateSettings#allowTags
   */
  readonly allowTags?: string;

  /**
   * ForceUpdate specifies whether updates should be forced.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecCommonUpdateSettings#forceUpdate
   */
  readonly forceUpdate?: boolean;

  /**
   * IgnoreTags is a list of glob-like patterns of tags to ignore.
   * This acts as the default and can be overridden at more specific levels.
   *
   * @schema ImageUpdaterSpecCommonUpdateSettings#ignoreTags
   */
  readonly ignoreTags?: string[];

  /**
   * Platforms specifies a list of target platforms (e.g., "linux/amd64", "linux/arm64").
   * If specified, the image updater will consider these platforms when checking for new versions or digests.
   *
   * @schema ImageUpdaterSpecCommonUpdateSettings#platforms
   */
  readonly platforms?: string[];

  /**
   * PullSecret is the pull secret to use for images.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecCommonUpdateSettings#pullSecret
   */
  readonly pullSecret?: string;

  /**
   * UpdateStrategy defines the update strategy to apply.
   * Examples: "semver", "latest", "digest", "name".
   * This acts as the default if not overridden at a more specific level.
   *
   * @schema ImageUpdaterSpecCommonUpdateSettings#updateStrategy
   */
  readonly updateStrategy?: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecCommonUpdateSettings' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecCommonUpdateSettings(obj: ImageUpdaterSpecCommonUpdateSettings | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allowTags': obj.allowTags,
    'forceUpdate': obj.forceUpdate,
    'ignoreTags': obj.ignoreTags?.map(y => y),
    'platforms': obj.platforms?.map(y => y),
    'pullSecret': obj.pullSecret,
    'updateStrategy': obj.updateStrategy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * WriteBackConfig provides global default settings for how and where to write back image updates.
 * This can be overridden at the ApplicationRef level.
 *
 * @schema ImageUpdaterSpecWriteBackConfig
 */
export interface ImageUpdaterSpecWriteBackConfig {
  /**
   * GitConfig provides Git configuration settings if the write-back method involves Git.
   * This can only be used when method is "git" or starts with "git:".
   *
   * @schema ImageUpdaterSpecWriteBackConfig#gitConfig
   */
  readonly gitConfig?: ImageUpdaterSpecWriteBackConfigGitConfig;

  /**
   * Method defines the method for writing back updated image versions.
   * This acts as the default if not overridden. If not specified, defaults to "argocd".
   *
   * @schema ImageUpdaterSpecWriteBackConfig#method
   */
  readonly method: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecWriteBackConfig' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecWriteBackConfig(obj: ImageUpdaterSpecWriteBackConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'gitConfig': toJson_ImageUpdaterSpecWriteBackConfigGitConfig(obj.gitConfig),
    'method': obj.method,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * CommonUpdateSettings overrides the global CommonUpdateSettings for applications
 * matched by this selector.
 *
 * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings
 */
export interface ImageUpdaterSpecApplicationRefsCommonUpdateSettings {
  /**
   * AllowTags is a regex pattern for tags to allow.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings#allowTags
   */
  readonly allowTags?: string;

  /**
   * ForceUpdate specifies whether updates should be forced.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings#forceUpdate
   */
  readonly forceUpdate?: boolean;

  /**
   * IgnoreTags is a list of glob-like patterns of tags to ignore.
   * This acts as the default and can be overridden at more specific levels.
   *
   * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings#ignoreTags
   */
  readonly ignoreTags?: string[];

  /**
   * Platforms specifies a list of target platforms (e.g., "linux/amd64", "linux/arm64").
   * If specified, the image updater will consider these platforms when checking for new versions or digests.
   *
   * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings#platforms
   */
  readonly platforms?: string[];

  /**
   * PullSecret is the pull secret to use for images.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings#pullSecret
   */
  readonly pullSecret?: string;

  /**
   * UpdateStrategy defines the update strategy to apply.
   * Examples: "semver", "latest", "digest", "name".
   * This acts as the default if not overridden at a more specific level.
   *
   * @schema ImageUpdaterSpecApplicationRefsCommonUpdateSettings#updateStrategy
   */
  readonly updateStrategy?: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsCommonUpdateSettings' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsCommonUpdateSettings(obj: ImageUpdaterSpecApplicationRefsCommonUpdateSettings | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allowTags': obj.allowTags,
    'forceUpdate': obj.forceUpdate,
    'ignoreTags': obj.ignoreTags?.map(y => y),
    'platforms': obj.platforms?.map(y => y),
    'pullSecret': obj.pullSecret,
    'updateStrategy': obj.updateStrategy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ImageConfig defines how a specific container image should be discovered, updated,
 * and how those updates should be reflected in application manifests.
 *
 * @schema ImageUpdaterSpecApplicationRefsImages
 */
export interface ImageUpdaterSpecApplicationRefsImages {
  /**
   * Alias is a short, user-defined name for this image configuration.
   * It MUST be unique within a single ApplicationRef's list of images.
   * This field is mandatory.
   *
   * @schema ImageUpdaterSpecApplicationRefsImages#alias
   */
  readonly alias: string;

  /**
   * CommonUpdateSettings overrides the effective default CommonUpdateSettings for this specific image.
   *
   * @schema ImageUpdaterSpecApplicationRefsImages#commonUpdateSettings
   */
  readonly commonUpdateSettings?: ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings;

  /**
   * ImageName is the full identifier of the image to be tracked,
   * including the registry (if not Docker Hub), the image name, and an initial/current tag or version.
   * This is the string used to query the container registry and also as a base for finding updates.
   * Example: "docker.io/library/nginx:1.17.10", "quay.io/prometheus/node-exporter:v1.5.0".
   * This field is mandatory.
   *
   * @schema ImageUpdaterSpecApplicationRefsImages#imageName
   */
  readonly imageName: string;

  /**
   * ManifestTarget defines how and where to update this image in Kubernetes manifests.
   * Only one of Helm or Kustomize should be specified within this block.
   * This whole block is optional if the image update isn't written to a manifest in a structured way.
   *
   * @schema ImageUpdaterSpecApplicationRefsImages#manifestTargets
   */
  readonly manifestTargets?: ImageUpdaterSpecApplicationRefsImagesManifestTargets;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsImages' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsImages(obj: ImageUpdaterSpecApplicationRefsImages | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'alias': obj.alias,
    'commonUpdateSettings': toJson_ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings(obj.commonUpdateSettings),
    'imageName': obj.imageName,
    'manifestTargets': toJson_ImageUpdaterSpecApplicationRefsImagesManifestTargets(obj.manifestTargets),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * LabelSelectors indicates the label selectors to apply for application selection
 *
 * @schema ImageUpdaterSpecApplicationRefsLabelSelectors
 */
export interface ImageUpdaterSpecApplicationRefsLabelSelectors {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema ImageUpdaterSpecApplicationRefsLabelSelectors#matchExpressions
   */
  readonly matchExpressions?: ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
   * map is equivalent to an element of matchExpressions, whose key field is "key", the
   * operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema ImageUpdaterSpecApplicationRefsLabelSelectors#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsLabelSelectors' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsLabelSelectors(obj: ImageUpdaterSpecApplicationRefsLabelSelectors | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchExpressions': obj.matchExpressions?.map(y => toJson_ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions(y)),
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * WriteBackConfig overrides the global WriteBackConfig settings for applications
 * matched by this selector.
 *
 * @schema ImageUpdaterSpecApplicationRefsWriteBackConfig
 */
export interface ImageUpdaterSpecApplicationRefsWriteBackConfig {
  /**
   * GitConfig provides Git configuration settings if the write-back method involves Git.
   * This can only be used when method is "git" or starts with "git:".
   *
   * @schema ImageUpdaterSpecApplicationRefsWriteBackConfig#gitConfig
   */
  readonly gitConfig?: ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig;

  /**
   * Method defines the method for writing back updated image versions.
   * This acts as the default if not overridden. If not specified, defaults to "argocd".
   *
   * @schema ImageUpdaterSpecApplicationRefsWriteBackConfig#method
   */
  readonly method: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsWriteBackConfig' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsWriteBackConfig(obj: ImageUpdaterSpecApplicationRefsWriteBackConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'gitConfig': toJson_ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig(obj.gitConfig),
    'method': obj.method,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * GitConfig provides Git configuration settings if the write-back method involves Git.
 * This can only be used when method is "git" or starts with "git:".
 *
 * @schema ImageUpdaterSpecWriteBackConfigGitConfig
 */
export interface ImageUpdaterSpecWriteBackConfigGitConfig {
  /**
   * Branch to commit updates to.
   * Required if write-back method is Git and this is not specified at the spec level.
   *
   * @schema ImageUpdaterSpecWriteBackConfigGitConfig#branch
   */
  readonly branch?: string;

  /**
   * Repository URL to commit changes to.
   * If not specified here or at the spec level, the controller MUST infer it from the
   * Argo CD Application's `spec.source.repoURL`. This field allows overriding that.
   *
   * @schema ImageUpdaterSpecWriteBackConfigGitConfig#repository
   */
  readonly repository?: string;

  /**
   * WriteBackTarget defines the path and type of file to update in the Git repository.
   * Examples: "helmvalues:./helm/values.yaml", "kustomization:./kustomize/overlays/production".
   * For ApplicationSet usage, `{{ .app.path.path }}` should be resolved by ApplicationSet
   * before this CR is generated, resulting in a concrete path here.
   * Required if write-back method is Git and this is not specified at the spec level.
   *
   * @schema ImageUpdaterSpecWriteBackConfigGitConfig#writeBackTarget
   */
  readonly writeBackTarget?: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecWriteBackConfigGitConfig' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecWriteBackConfigGitConfig(obj: ImageUpdaterSpecWriteBackConfigGitConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'repository': obj.repository,
    'writeBackTarget': obj.writeBackTarget,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * CommonUpdateSettings overrides the effective default CommonUpdateSettings for this specific image.
 *
 * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings
 */
export interface ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings {
  /**
   * AllowTags is a regex pattern for tags to allow.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings#allowTags
   */
  readonly allowTags?: string;

  /**
   * ForceUpdate specifies whether updates should be forced.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings#forceUpdate
   */
  readonly forceUpdate?: boolean;

  /**
   * IgnoreTags is a list of glob-like patterns of tags to ignore.
   * This acts as the default and can be overridden at more specific levels.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings#ignoreTags
   */
  readonly ignoreTags?: string[];

  /**
   * Platforms specifies a list of target platforms (e.g., "linux/amd64", "linux/arm64").
   * If specified, the image updater will consider these platforms when checking for new versions or digests.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings#platforms
   */
  readonly platforms?: string[];

  /**
   * PullSecret is the pull secret to use for images.
   * This acts as the default if not overridden.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings#pullSecret
   */
  readonly pullSecret?: string;

  /**
   * UpdateStrategy defines the update strategy to apply.
   * Examples: "semver", "latest", "digest", "name".
   * This acts as the default if not overridden at a more specific level.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings#updateStrategy
   */
  readonly updateStrategy?: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings(obj: ImageUpdaterSpecApplicationRefsImagesCommonUpdateSettings | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allowTags': obj.allowTags,
    'forceUpdate': obj.forceUpdate,
    'ignoreTags': obj.ignoreTags?.map(y => y),
    'platforms': obj.platforms?.map(y => y),
    'pullSecret': obj.pullSecret,
    'updateStrategy': obj.updateStrategy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * ManifestTarget defines how and where to update this image in Kubernetes manifests.
 * Only one of Helm or Kustomize should be specified within this block.
 * This whole block is optional if the image update isn't written to a manifest in a structured way.
 *
 * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargets
 */
export interface ImageUpdaterSpecApplicationRefsImagesManifestTargets {
  /**
   * Helm specifies update parameters if the target manifest is managed by Helm
   * and updates are to be made to Helm values files.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargets#helm
   */
  readonly helm?: ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm;

  /**
   * Kustomize specifies update parameters if the target manifest is managed by Kustomize
   * and updates involve changing image tags in Kustomize configurations.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargets#kustomize
   */
  readonly kustomize?: ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsImagesManifestTargets' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsImagesManifestTargets(obj: ImageUpdaterSpecApplicationRefsImagesManifestTargets | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'helm': toJson_ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm(obj.helm),
    'kustomize': toJson_ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize(obj.kustomize),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that
 * relates the key and values.
 *
 * @schema ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions
 */
export interface ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values.
   * Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn,
   * the values array must be non-empty. If the operator is Exists or DoesNotExist,
   * the values array must be empty. This array is replaced during a strategic
   * merge patch.
   *
   * @schema ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions(obj: ImageUpdaterSpecApplicationRefsLabelSelectorsMatchExpressions | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'operator': obj.operator,
    'values': obj.values?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * GitConfig provides Git configuration settings if the write-back method involves Git.
 * This can only be used when method is "git" or starts with "git:".
 *
 * @schema ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig
 */
export interface ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig {
  /**
   * Branch to commit updates to.
   * Required if write-back method is Git and this is not specified at the spec level.
   *
   * @schema ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig#branch
   */
  readonly branch?: string;

  /**
   * Repository URL to commit changes to.
   * If not specified here or at the spec level, the controller MUST infer it from the
   * Argo CD Application's `spec.source.repoURL`. This field allows overriding that.
   *
   * @schema ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig#repository
   */
  readonly repository?: string;

  /**
   * WriteBackTarget defines the path and type of file to update in the Git repository.
   * Examples: "helmvalues:./helm/values.yaml", "kustomization:./kustomize/overlays/production".
   * For ApplicationSet usage, `{{ .app.path.path }}` should be resolved by ApplicationSet
   * before this CR is generated, resulting in a concrete path here.
   * Required if write-back method is Git and this is not specified at the spec level.
   *
   * @schema ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig#writeBackTarget
   */
  readonly writeBackTarget?: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig(obj: ImageUpdaterSpecApplicationRefsWriteBackConfigGitConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'repository': obj.repository,
    'writeBackTarget': obj.writeBackTarget,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Helm specifies update parameters if the target manifest is managed by Helm
 * and updates are to be made to Helm values files.
 *
 * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm
 */
export interface ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm {
  /**
   * Name is the dot-separated path to the Helm key for the image repository/name part.
   * Example: "image.repository", "frontend.deployment.image.name".
   * This field is required if the Helm target is used.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm#name
   */
  readonly name: string;

  /**
   * Spec is an optional dot-separated path to a Helm key where the full image string
   * (e.g., "image/name:1.0") should be written.
   * Use this if your Helm chart expects the entire image reference in a single field,
   * rather than separate name/tag fields. If this is set, other Helm parameter-related
   * options will be ignored.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm#spec
   */
  readonly spec?: string;

  /**
   * Tag is the dot-separated path to the Helm key for the image tag part.
   * Example: "image.tag", "frontend.deployment.image.version".
   * This field is required if the Helm target is used.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm#tag
   */
  readonly tag: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm(obj: ImageUpdaterSpecApplicationRefsImagesManifestTargetsHelm | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'spec': obj.spec,
    'tag': obj.tag,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * Kustomize specifies update parameters if the target manifest is managed by Kustomize
 * and updates involve changing image tags in Kustomize configurations.
 *
 * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize
 */
export interface ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize {
  /**
   * Name is the image name (which can include the registry and an initial tag)
   * as it appears in the `images` list of a kustomization.yaml file that needs to be updated.
   * The updater will typically change the tag or add a digest to this entry.
   * Example: "docker.io/library/nginx".
   * This field is required if the Kustomize target is used.
   *
   * @schema ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize#name
   */
  readonly name: string;

}

/**
 * Converts an object of type 'ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize(obj: ImageUpdaterSpecApplicationRefsImagesManifestTargetsKustomize | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

