{
 "title": "GitLab Omnibus - Overview",
 "description": "GitLab Omnibus Dashboard (>= 10.3)",
 "tags": [ "GitLab" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values({job=\"gitlab-node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unicorn Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=~\"gitlab-(rails|unicorn)\",instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Postgres Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(pg_up{instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Sidekiq Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitlab-sidekiq\",instance=~\"($node):.*\"}[$__interval])\n) "
    }
   ]
  },
  {
   "title": "Workhorse Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitlab-workhorse\",instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Redis Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(redis_up{instance=~\"($node):9121\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Gitaly Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(up{job=\"gitaly\",instance=~\"($node):.*\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Node Available Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemAvailable_bytes{instance=~\"$node:9100\"} or\n  (node_memory_MemFree_bytes{instance=~\"$node:9100\"} + node_memory_Buffers_bytes{instance=~\"$node:9100\"} + node_memory_Cached_bytes{instance=~\"$node:9100\"})\n) / node_memory_MemTotal_bytes{instance=~\"$node:9100\"}"
    }
   ]
  },
  {
   "title": "Node Disk Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{fstype!~\"tmpfs\",instance=~\"($node):9100\"}) / sum(node_filesystem_size_bytes{fstype!~\"tmpfs\",instance=~\"($node):9100\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  1 -\n  avg without (mode,cpu) (\n    rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"($node):9100\"}[$__interval])\n  )\n)"
    }
   ]
  },
  {
   "title": "Sidekiq Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    sidekiq_queue_size{instance=~\"($node):.*\"}[$__interval]\n  )\n)",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Workhorse Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{instance=~\"($node):9229\"}[$__interval])\n)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}