{
 "title": "Rails App",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(puma_active_connections, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ruby Memory per Worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(ruby_process_resident_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or \navg(avg_over_time(ruby_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(max_over_time(ruby_process_resident_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or\nmax(max_over_time(ruby_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(min_over_time(ruby_process_resident_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or\nmin(min_over_time(ruby_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(unicorn_queued_connections{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or\nsum(avg_over_time(puma_queued_connections{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))\n",
     "legendFormat": "Queued Requests"
    }
   ]
  },
  {
   "title": "Ruby CPU per Worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(ruby_process_cpu_seconds_total{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rate(ruby_process_cpu_seconds_total{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(rate(ruby_process_cpu_seconds_total{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(unicorn_active_connections{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or\nsum(avg_over_time(puma_active_connections{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(max_over_time(unicorn_active_connections{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or\nsum(max_over_time(puma_active_connections{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "count(avg_over_time(ruby_memory_bytes{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval])) or\nsum(avg_over_time(puma_max_threads{job=\"gitlab-rails\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Available Workers"
    }
   ]
  }
 ]
}